#!/usr/bin/env node
const fs=require('fs'),path=require('path'),crypto=require('crypto'); const {Client}=require('./http.cjs');
const mysql=require('../../backend/node_modules/mysql2/promise');
const fixture=JSON.parse(fs.readFileSync(path.resolve(process.env.KTC_ZERO_COST_FIXTURE||'validation-artifacts/fixture.json'),'utf8'));
const outDir=path.resolve(process.env.KTC_VALIDATION_DIR||'validation-artifacts'); fs.mkdirSync(outDir,{recursive:true});
const runId=`KTC_E2E_LOCAL_${new Date().toISOString().replace(/[-:.TZ]/g,'')}`; const base=process.env.LOCAL_BACKEND_URL||'http://127.0.0.1:19080'; const w=new Client(base),m=new Client(base); const rows=[]; const artifacts={runId,tempIds:[],approvedIds:[],machineEventIds:[],excel:[]};
const dbCfg={host:process.env.DB_HOST,port:Number(process.env.DB_PORT||3306),user:process.env.DB_USER,password:process.env.DB_PASSWORD,database:process.env.DB_NAME};
function d(days){const x=new Date();x.setUTCDate(x.getUTCDate()+days);return x.toISOString().slice(0,10)}
function basePayload(p,days=0,extra={}){const proc=fixture.processes[p]; const one=proc.machines[0]; return {process_id:proc.id,work_date:d(days),shift:'A',operation_type:'NORMAL',operation_mode:one?'MACHINE':'MANUAL',machine_no:one?.code||'',product_name:proc.product,training_percent:100,total_time:1,deduction_time:0,actual_time:1,standard_output:100,actual_output:10,tt_ok:10,tt_ng:0,defects:[],deductions:[],client_request_id:crypto.randomUUID(),note:`${runId} ${p}`,...extra};}
async function tc(n,name,fn){try{const ev=await fn(); const ok=ev.ok!==false; rows.push({n,name,result:ok?'PASS':'FAIL',...ev}); if(!ok)process.exitCode=1;}catch(e){rows.push({n,name,result:'FAIL',evidence:e.message});process.exitCode=1;}}
async function cleanupRun(db){
 if(process.env.KTC_E2E_KEEP_DATA==='1') return;
 const like=`%${runId}%`;
 const statements=[
   ['production_reports_temp','note'],
   ['production_reports','note'],
   ['machine_production_events','note']
 ];
 for(const [table,column] of statements){
   try{
     const [tables]=await db.query(`SELECT COUNT(*) AS n FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?`,[table]);
     if(Number(tables[0]?.n||0)>0) await db.query(`DELETE FROM \`${table}\` WHERE \`${column}\` LIKE ?`,[like]);
   }catch(error){
     console.warn(`[KTC] E2E cleanup skipped for ${table}: ${error.message}`);
   }
 }
}

async function main(){const db=await mysql.createConnection(dbCfg);
 await tc(1,'Worker login',async()=>{const r=await w.req('POST','/api/auth/login',{username:fixture.worker.code,access_type:'worker'});return {ok:r.status===200,status:r.status,code:r.data?.code||'',evidence:`${r.ms.toFixed(1)}ms`}});
 const oldCookie=w.cookies; await tc(2,'Refresh',async()=>{const r=await w.req('POST','/api/auth/refresh',{});return {ok:r.status===200&&w.cookies!==oldCookie,status:r.status,code:r.data?.code||'',evidence:'successor cookie issued'}});
 await tc(3,'Logout + relogin',async()=>{const a=await w.req('POST','/api/auth/logout',{}); const old=w.token; w.token='';w.cookies=''; const b=await w.req('POST','/api/auth/login',{username:fixture.worker.code,access_type:'worker'}); return {ok:[200,204].includes(a.status)&&b.status===200&&w.token!==old,status:b.status,evidence:`logout=${a.status},relogin=${b.status}`}});
 let normalPayload=basePayload('DO'); await tc(4,'Normal report',async()=>{const r=await w.req('POST','/api/production-temp',normalPayload); if(r.data?.id)artifacts.tempIds.push(r.data.id);return {ok:r.status===201,status:r.status,code:r.data?.code||'',recordId:r.data?.id}});
 let dupToken=''; await tc(5,'Duplicate detection',async()=>{const p={...normalPayload,client_request_id:crypto.randomUUID()}; const r=await w.req('POST','/api/production-temp',p);dupToken=r.data?.duplicate_confirmation_token||'';return {ok:r.status===409&&!!dupToken,status:r.status,code:r.data?.code||'',evidence:'challenge token present'}});
 await tc(6,'Intentional duplicate',async()=>{const p={...normalPayload,client_request_id:crypto.randomUUID(),duplicate_confirmation_token:dupToken,force_create:true}; const r=await w.req('POST','/api/production-temp',p);if(r.data?.id)artifacts.tempIds.push(r.data.id);return {ok:r.status===201,status:r.status,recordId:r.data?.id}});
 await tc(7,'Backdate -14',async()=>{const r=await w.req('POST','/api/production-temp',basePayload('DO',-14));if(r.data?.id)artifacts.tempIds.push(r.data.id);return {ok:r.status===201,status:r.status,recordId:r.data?.id}});
 await tc(8,'Backdate -15',async()=>{const r=await w.req('POST','/api/production-temp',basePayload('DO',-15));return {ok:r.status===422,status:r.status,code:r.data?.code||''}});
 await tc(9,'Future date',async()=>{const r=await w.req('POST','/api/production-temp',basePayload('DO',1));return {ok:r.status===422,status:r.status}});
 const multi=(code,count)=>{const p=basePayload(code); const proc=fixture.processes[code]; p.machine_no='';p.machine_lines=proc.machines.slice(0,count).map(x=>({machine_code:x.code,product_code:proc.product,machine_time_hours:1,ok_quantity:10,ng_quantity:0,defects:[]})); return p;};
 await tc(10,'MAI multi-machine',async()=>{const r=await w.req('POST','/api/production-temp',multi('MAI',2));if(r.data?.id)artifacts.tempIds.push(r.data.id);return {ok:r.status===201,status:r.status,recordId:r.data?.id}});
 for(const [n,code] of [[11,'DO'],[12,'EP'],[13,'CAN']]) await tc(n,`${code} 1:1`,async()=>{const p=basePayload(code); const proc=fixture.processes[code];p.machine_no='';p.machine_lines=[0,1].map(i=>({machine_code:proc.machines[0].code,product_code:proc.product,machine_time_hours:1,ok_quantity:5,ng_quantity:0,defects:[]})); const r=await w.req('POST','/api/production-temp',p);return {ok:r.status===422,status:r.status}});
 await tc(14,'K1/K2 single/manual',async()=>{const p=basePayload('K1');const proc=fixture.processes.K1;p.machine_no='';p.machine_lines=[{machine_code:proc.machines[0].code,product_code:proc.product,machine_time_hours:1,ok_quantity:5,ng_quantity:0,defects:[]},{machine_code:proc.machines[0].code,product_code:proc.product,machine_time_hours:1,ok_quantity:5,ng_quantity:0,defects:[]}];const r=await w.req('POST','/api/production-temp',p);return {ok:r.status===422,status:r.status}});
 await tc(15,'GC 5/6/7/11 max4',async()=>{const proc=fixture.processes.GC;const codes=['5','6','7','11'];const results=[];for(const code of codes){const valid={...basePayload('GC'),machine_no:'',machine_lines:Array.from({length:4},()=>({machine_code:code,product_code:proc.product,machine_time_hours:1,ok_quantity:1,ng_quantity:0,defects:[]}))};const a=await w.req('POST','/api/production-temp',valid);if(a.data?.id)artifacts.tempIds.push(a.data.id);const invalid={...valid,client_request_id:crypto.randomUUID(),machine_lines:[...valid.machine_lines,{machine_code:code,product_code:proc.product,machine_time_hours:1,ok_quantity:1,ng_quantity:0,defects:[]}]};const b=await w.req('POST','/api/production-temp',invalid);results.push({code,valid:a.status,overflow:b.status});}return {ok:results.every(x=>x.valid===201&&x.overflow===422),status:results.find(x=>x.overflow!==422)?.overflow||201,evidence:JSON.stringify(results)}});
 await tc(16,'Shared-machine accounting',async()=>{const gc=fixture.processes.GC;const payload={process_id:gc.id,machine_id:gc.machines.find(x=>x.code==='5').id,machine_code:'5',product_code:gc.product,work_date:d(0),shift:'B',physical_ok_quantity:100,physical_ng_quantity:0,machine_time_hours:1,standard_output:100,exclude_kqd_from_tt_snapshot:1,note:runId}; const lg=await m.req('POST','/api/auth/login',{username:fixture.manager.username,password:fixture.manager.password,access_type:'management'});if(lg.status!==200)return {ok:false,status:lg.status,evidence:'manager login'};const r=await m.req('POST','/api/machine-production-events',payload);if(r.data?.id)artifacts.machineEventIds.push(r.data.id);return {ok:[200,201].includes(r.status),status:r.status,recordId:r.data?.id,evidence:'physical event separate endpoint'}});
 await tc(17,'KQD allowlist',async()=>{const gc=fixture.processes.GC;const kqd={...basePayload('GC'),operation_mode:'MACHINE',machine_no:'5',tt_ok:10,tt_ng:2,actual_output:10,defects:[{defect_type_id:gc.defects.KQD,quantity:1},{defect_type_id:gc.defects.KQD_TEST,quantity:1}],client_request_id:crypto.randomUUID()};const r=await w.req('POST','/api/production-temp',kqd);return {ok:r.status===201,status:r.status,recordId:r.data?.id,evidence:'KQD excluded; KQD_TEST counted under exact registry'}});
 await tc(18,'manager_processes authorization',async()=>{if(!m.token){const lg=await m.req('POST','/api/auth/login',{username:fixture.manager.username,password:fixture.manager.password,access_type:'management'});if(lg.status!==200)return {ok:false,status:lg.status}} const a=await m.req('GET',`/api/production-temp/pending?process_id=${fixture.processes.DO.id}`); const b=await m.req('GET',`/api/production-temp/pending?process_id=${fixture.processes.SX3.id}`); return {ok:a.status===200&&b.status===403,status:b.status,evidence:`assigned=${a.status},unassigned=${b.status}`}});
 let approvedId=null; await tc(19,'Approve/reject',async()=>{const id=artifacts.tempIds[0];const a=await m.req('POST','/api/production-temp/approve-selected',{ids:[id]}); approvedId=a.data?.data?.approved_ids?.[0]||a.data?.data?.ids?.[0]||null; if(!approvedId){const [ar]=await db.execute(`SELECT id FROM production_reports WHERE note LIKE ? ORDER BY id DESC LIMIT 1`,[`${runId}%`]);approvedId=ar[0]?.id||null;} if(approvedId)artifacts.approvedIds.push(approvedId); return {ok:a.status===200&&!!approvedId,status:a.status,recordId:approvedId}});
 await tc(20,'Approved edit conflict',async()=>{if(!approvedId){const [rr]=await db.execute(`SELECT id FROM production_reports WHERE note LIKE ? ORDER BY id DESC LIMIT 1`,[`${runId}%`]);approvedId=rr[0]?.id;} if(!approvedId)return {ok:false,status:0,evidence:'approved id unavailable'}; const g=await m.req('GET',`/api/production/${approvedId}`); const ts=g.data?.data?.updated_at; if(g.status!==200||!ts)return {ok:false,status:g.status}; const u1=await m.req('PUT',`/api/production/${approvedId}`,{expected_updated_at:ts,note:`${runId} update1`,reason:'E2E'}); const u2=await m.req('PUT',`/api/production/${approvedId}`,{expected_updated_at:ts,note:`${runId} stale`,reason:'E2E'}); return {ok:u1.status===200&&u2.status===409&&u2.data?.code==='REPORT_VERSION_CONFLICT',status:u2.status,code:u2.data?.code}});
 await tc(21,'Excel export data',async()=>{const r=await m.req('GET',`/api/reports/export-excel/company-data?month=${d(0).slice(0,7)}`);return {ok:r.status===200,status:r.status,code:r.data?.code||'',evidence:'desktop JSON source available'}});
 await tc(22,'Excel import real-diff',async()=>{const unchanged=await m.req('POST','/api/production/excel-sync',{changes:[]}); const changed=approvedId?await m.req('POST','/api/production/excel-sync',{changes:[{id:approvedId,expected_updated_at:(await m.req('GET',`/api/production/${approvedId}`)).data?.data?.updated_at,patch:{note:`${runId} excel-diff`},source:{file:'KTC_E2E.xlsx'}}] }):{status:0,data:{}}; return {ok:[200,204,422].includes(unchanged.status)&&changed.status===200,status:changed.status,code:changed.data?.code||'',evidence:`unchanged=${unchanged.status},changed=${changed.status}`}});
 await tc(23,'Final logout cleanup',async()=>{const a=await w.req('POST','/api/auth/logout',{});const old=w.token;w.token=old;w.cookies='';const b=await w.req('GET','/api/production-temp/my');return {ok:[200,204].includes(a.status)&&[401,403].includes(b.status),status:b.status,evidence:`logout=${a.status},protected=${b.status}`}});
 await cleanupRun(db); await db.end(); fs.writeFileSync(path.join(outDir,'critical-e2e.json'),JSON.stringify({runId,rows,artifacts,cleanup:process.env.KTC_E2E_KEEP_DATA==='1'?'kept':'attempted'},null,2)); console.table(rows.map(({n,name,result,status,code,recordId})=>({n,name,result,status,code,recordId}))); console.log(`KTC_CRITICAL_E2E=${rows.every(x=>x.result==='PASS')?'PASS':'FAIL'}`);
}
main().catch(e=>{console.error('KTC_CRITICAL_E2E_FATAL',e.stack||e);process.exit(1)});
