const defaultQuery = async (sql, params = []) => {
  const db = require('../config/db');
  const [rows] = await db.promise().query(sql, params);
  return rows;
};

function businessError(code, message, details = null) { const error = new Error(message); error.status = 422; error.code = code; error.isPublic = true; if (details) error.details = details; return error; }
function normalizeWorkDate(value) { const text = value instanceof Date ? `${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,'0')}-${String(value.getDate()).padStart(2,'0')}` : String(value || '').slice(0,10); if (!/^\d{4}-\d{2}-\d{2}$/.test(text)) throw businessError('INVALID_WORK_DATE','Ngày làm việc không hợp lệ'); return text; }
function positiveDecimal(value, code='INVALID_STANDARD_VALUE') { const number=Number(value); if(!Number.isFinite(number)||number<=0) throw businessError(code,'Định mức phải là số dương hợp lệ'); return number; }
function sameDecimal(a,b,tolerance=0.000001){ return Math.abs(Number(a)-Number(b))<=tolerance; }
function assertEffectiveOnDate(row,date,label){const from=row?.effective_from?String(row.effective_from).slice(0,10):null;const to=row?.effective_to?String(row.effective_to).slice(0,10):null;if(from&&from>date)throw businessError('HISTORICAL_STANDARD_NOT_FOUND',`${label} chưa có hiệu lực tại ngày ${date}`,{effective_from:from,effective_to:to});if(to&&to<date)throw businessError('HISTORICAL_STANDARD_NOT_FOUND',`${label} đã hết hiệu lực tại ngày ${date}`,{effective_from:from,effective_to:to});}
function chooseHistoricalVersion(rows,date,label){const applicable=(rows||[]).filter(row=>{const from=row?.effective_from?String(row.effective_from).slice(0,10):null;const to=row?.effective_to?String(row.effective_to).slice(0,10):null;return(!from||from<=date)&&(!to||to>=date)});if(!applicable.length)return null;const active=applicable.filter(row=>String(row.status||'').toLowerCase()==='active'||Number(row.is_active)===1);const candidates=active.length?active:applicable;if(candidates.length>1)throw businessError('STANDARD_EFFECTIVE_RANGE_CONFLICT',`Có nhiều định mức cùng hiệu lực cho ${label} tại ngày ${date}`,{work_date:date,version_ids:candidates.map(r=>Number(r.id)).filter(Boolean)});return candidates[0];}

function normalizeWorkType(value){const code=String(value||'').trim().toUpperCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');if(['CUT','CAT'].includes(code))return 'CUT';if(['LONG','LNG'].includes(code))return 'LONG';return code;}
function inferGcWorkType(machineCode){const code=String(machineCode||'').trim().toUpperCase().replace(/\s+/g,'');if(/^ML\d+$/.test(code)||/^\d+$/.test(code))return 'Lồng';if(/^C\d+/.test(code))return 'Cắt';return null;}
function normalizeRequestedWorkType({processId,processCode,machineCode,workType,operationMode}){const explicit=normalizeWorkType(workType);if(explicit==='LONG')return 'Lồng';if(explicit==='CUT')return 'Cắt';const isGc=Number(processId)===1||String(processCode||'').trim().toUpperCase()==='GC';if(isGc){const inferred=inferGcWorkType(machineCode);if(inferred)return inferred;if(String(operationMode||'').trim().toUpperCase()==='MANUAL')return 'Lồng';}return null;}

function createStandardResolver({query=defaultQuery}={}) {
  const productCache=new Map(), standardCache=new Map();
  async function findProductRows(pid,product,workType=null){const normalizedWorkType=normalizeWorkType(workType);const workTypeSql=normalizedWorkType==='LONG'?` AND UPPER(TRIM(ps.work_type))='LỒNG'`:normalizedWorkType==='CUT'?` AND UPPER(TRIM(ps.work_type))='CẮT'`:'';return query(`SELECT id AS product_standard_id, product_code, encoding_code, work_type, standard_output, exclude_kqd_from_tt FROM product_standards ps WHERE process_id=? AND status='active'${workTypeSql} AND (product_code=? OR encoding_code=? OR EXISTS(SELECT 1 FROM product_aliases pa WHERE pa.process_id=ps.process_id AND UPPER(TRIM(pa.product_code))=UPPER(TRIM(ps.product_code)) AND pa.status='active' AND UPPER(TRIM(pa.alias_code))=UPPER(TRIM(?)))) ORDER BY CASE WHEN UPPER(TRIM(encoding_code))=UPPER(TRIM(?)) THEN 0 WHEN UPPER(TRIM(product_code))=UPPER(TRIM(?)) THEN 1 ELSE 2 END,id LIMIT 2`,[pid,product,product,product,product,product]);}
  // Some catalogues hold the same product twice (one row per work type, or a
// duplicated import). Those rows are interchangeable when they carry the same
// standard, so pick the best-ranked one instead of reporting a missing standard.
function pickEquivalentRow(rows){if(!Array.isArray(rows)||rows.length<2)return null;const out=Number(rows[0]?.standard_output),kqd=Number(rows[0]?.exclude_kqd_from_tt||0);if(!Number.isFinite(out)||out<=0)return null;const allSame=rows.every(row=>sameDecimal(Number(row?.standard_output),out)&&Number(row?.exclude_kqd_from_tt||0)===kqd);return allSame?rows[0]:null;}
  async function selectProductRow(pid,product,workDate,{allowAutoAlias=false,workType=null}={}){const rows=await findProductRows(pid,product,workType);if(rows.length===1)return rows[0];const equivalent=pickEquivalentRow(rows);if(equivalent)return equivalent;if(!allowAutoAlias)return null;const autoProduct=/-AUTO$/i.test(product)?product:`${product}-AUTO`;const autoRows=await findProductRows(pid,autoProduct,workType);return autoRows.length===1?autoRows[0]:(pickEquivalentRow(autoRows)||null);}
  async function resolveProduct({processId,productCode,workDate,standardVersionId=null,allowAutoAlias=false,workType=null}) {
    const pid=Number(processId), product=String(productCode||'').trim(), date=normalizeWorkDate(workDate), normalizedWorkType=normalizeWorkType(workType);
    if(pid===60006&&!product)return{processId:pid,productCode:null,productStandardId:null,standardVersionId:null,machineStandardId:null,standardOutput:0,standardTimeSeconds:null,excludeKqdFromTt:0,effectiveFrom:null,effectiveTo:null,source:'NON_PRODUCT_WORK',workDate:date,historicalVersionAvailable:false,nonProductWork:true};
    if(!Number.isInteger(pid)||pid<=0||!product)throw businessError('INVALID_STANDARD_LOOKUP','Thiếu công đoạn hoặc sản phẩm để tra định mức');
    const requestedVersionId=Number(standardVersionId)||null, cacheKey=`${pid}|${product}|${date}|${requestedVersionId||''}|auto=${allowAutoAlias?1:0}|work=${normalizedWorkType||''}`;
    if(productCache.has(cacheKey))return productCache.get(cacheKey);
    let selectedProduct=await selectProductRow(pid,product,date,{allowAutoAlias,workType:normalizedWorkType});
    let fallbackToProcessProduct=false;
    if(!selectedProduct && normalizedWorkType){
      selectedProduct=await selectProductRow(pid,product,date,{allowAutoAlias,workType:null});
      fallbackToProcessProduct=Boolean(selectedProduct);
    }
    if(!selectedProduct)throw businessError('HISTORICAL_STANDARD_NOT_FOUND',`Không xác định duy nhất định mức sản phẩm ${product}${normalizedWorkType?` / ${normalizedWorkType}`:''} trong công đoạn`,{process_id:pid,product_code:product,work_type:normalizedWorkType||null});
    const canonicalProduct=String(selectedProduct.product_code||'').trim();
    const effectiveWorkType=normalizeWorkType(selectedProduct.work_type)||normalizedWorkType||null;
    if(requestedVersionId){const versionRows=await query(`SELECT id,process_id,product_code,standard_output,exclude_kqd_from_tt,version_no,effective_from,effective_to,status FROM product_standard_versions WHERE id=? AND process_id=? AND product_code=? LIMIT 1`,[requestedVersionId,pid,canonicalProduct]);if(versionRows.length!==1)throw businessError('HISTORICAL_STANDARD_NOT_FOUND',`Không tìm thấy định mức lịch sử #${requestedVersionId} cho ${canonicalProduct}`);const version=versionRows[0];assertEffectiveOnDate(version,date,`Định mức lịch sử #${requestedVersionId}`);const r={processId:pid,productCode:canonicalProduct,productStandardId:Number(selectedProduct.product_standard_id),standardVersionId:Number(version.id),machineStandardId:null,standardOutput:positiveDecimal(version.standard_output),standardTimeSeconds:null,excludeKqdFromTt:Number(version.exclude_kqd_from_tt||0)===1?1:0,effectiveFrom:version.effective_from?String(version.effective_from).slice(0,10):null,effectiveTo:version.effective_to?String(version.effective_to).slice(0,10):null,source:fallbackToProcessProduct?'PRODUCT_VERSION_PROCESS_FALLBACK':'PRODUCT_VERSION_SNAPSHOT',workDate:date,historicalVersionAvailable:true,workType:effectiveWorkType};productCache.set(cacheKey,r);return r;}
    const versions=await query(`SELECT id,process_id,product_code,standard_output,exclude_kqd_from_tt,version_no,effective_from,effective_to,status FROM product_standard_versions WHERE process_id=? AND product_code=? AND effective_from<=? AND (effective_to IS NULL OR effective_to>=?) ORDER BY effective_from,version_no,id`,[pid,canonicalProduct,date,date]);
    const version=chooseHistoricalVersion(versions,date,canonicalProduct);
    if(!version){const out=Number(selectedProduct.standard_output);if(!Number.isFinite(out)||out<=0)throw businessError('HISTORICAL_STANDARD_NOT_FOUND',`Không có định mức lịch sử cho ${canonicalProduct} tại ngày ${date}`,{process_id:pid,product_code:canonicalProduct,work_type:effectiveWorkType,work_date:date});const r={processId:pid,productCode:canonicalProduct,productStandardId:Number(selectedProduct.product_standard_id),standardVersionId:null,machineStandardId:null,standardOutput:out,standardTimeSeconds:null,excludeKqdFromTt:Number(selectedProduct.exclude_kqd_from_tt||0)===1?1:0,effectiveFrom:null,effectiveTo:null,source:fallbackToProcessProduct?'LEGACY_PRODUCT_STANDARD_PROCESS_FALLBACK':'LEGACY_PRODUCT_STANDARD',workDate:date,historicalVersionAvailable:false,workType:effectiveWorkType};productCache.set(cacheKey,r);return r;}
    const r={processId:pid,productCode:canonicalProduct,productStandardId:Number(selectedProduct.product_standard_id),standardVersionId:Number(version.id),machineStandardId:null,standardOutput:positiveDecimal(version.standard_output),standardTimeSeconds:null,excludeKqdFromTt:Number(version.exclude_kqd_from_tt||0)===1?1:0,effectiveFrom:String(version.effective_from).slice(0,10),effectiveTo:version.effective_to?String(version.effective_to).slice(0,10):null,source:fallbackToProcessProduct?'PRODUCT_VERSION_PROCESS_FALLBACK':(String(version.status||'').toLowerCase()==='active'?'PRODUCT_VERSION':'PRODUCT_VERSION_HISTORICAL'),workDate:date,historicalVersionAvailable:true,workType:effectiveWorkType};productCache.set(cacheKey,r);return r;
  }
  async function resolveStandard({processId,productCode,machineId=null,machineCode=null,workDate,standardVersionId=null,machineStandardId=null,operationMode=null,executionMethod=null,workType=null}) {
    const pid=Number(processId), requestedMachineId=Number(machineId)||null, requestedMachineCode=String(machineCode||'').trim(), requestedVersionId=Number(standardVersionId)||null, requestedMachineStandardId=Number(machineStandardId)||null, requestedProduct=String(productCode||'').trim(), date=normalizeWorkDate(workDate);
    let machineRows=[];
    if(requestedMachineStandardId&&!requestedMachineId&&!requestedMachineCode)machineRows=await query(`SELECT m.id,m.machine_code,p.process_code FROM machines m JOIN processes p ON p.id=m.process_id JOIN product_machine_standards pms ON pms.machine_id=m.id WHERE m.process_id=? AND pms.id=? LIMIT 2`,[pid,requestedMachineStandardId]);
    else if(requestedMachineId||requestedMachineCode)machineRows=await query(`SELECT m.id,m.machine_code,p.process_code FROM machines m JOIN processes p ON p.id=m.process_id WHERE m.process_id=? AND m.status='active' AND (? IS NULL OR m.id=?) AND (?='' OR UPPER(TRIM(m.machine_code))=UPPER(TRIM(?))) LIMIT 2`,[pid,requestedMachineId,requestedMachineId,requestedMachineCode,requestedMachineCode]);
    if(machineRows.length>1)throw businessError('MACHINE_NOT_FOUND','Máy xác định không duy nhất trong công đoạn');
    if((requestedMachineId||requestedMachineCode||requestedMachineStandardId)&&machineRows.length!==1)throw businessError('MACHINE_NOT_FOUND','Máy không tồn tại hoặc không thuộc công đoạn');
    const machine=machineRows[0]||null, processCode=String(machine?.process_code||'').trim().toUpperCase();
    const modeText=String(operationMode||executionMethod||'').trim().toUpperCase(), isAuto=['AUTO','AUTOMATIC','TỰ ĐỘNG','TU DONG'].includes(modeText)||/AUTO|TỰ\s*ĐỘNG|TU\s*DONG/.test(modeText);
    const resolvedWorkType=normalizeRequestedWorkType({processId:pid,processCode,machineCode:machine?.machine_code||requestedMachineCode,workType,operationMode:modeText});
    const standardKey=`${pid}|${requestedProduct}|${date}|${requestedMachineId||''}|${requestedMachineCode}|v${requestedVersionId||''}|ms${requestedMachineStandardId||''}|mode=${isAuto?'AUTO':'NORMAL'}|work=${resolvedWorkType||''}`;if(standardCache.has(standardKey))return standardCache.get(standardKey);
    if(machine){const rows=await query(`SELECT id,process_id,product_code,machine_id,standard_output,calculated_output_per_hour,standard_time_seconds,effective_from,effective_to,is_active FROM product_machine_standards WHERE process_id=? AND machine_id=? AND UPPER(TRIM(product_code))=UPPER(TRIM(?)) AND (effective_from IS NULL OR effective_from<=?) AND (effective_to IS NULL OR effective_to>=?) ORDER BY COALESCE(effective_from,'1000-01-01') DESC,id DESC`,[pid,Number(machine.id),requestedProduct,date,date]);const active=rows.filter(r=>Number(r.is_active)===1),usable=active.length?active:rows;if(usable.length>1)throw businessError('STANDARD_EFFECTIVE_RANGE_CONFLICT',`Có nhiều định mức máy cùng hiệu lực cho ${requestedProduct} / ${machine.machine_code}`);if(usable.length===1){const row=usable[0],out=Number(row.calculated_output_per_hour??row.standard_output);if(Number.isFinite(out)&&out>0){const r={processId:pid,productCode:requestedProduct,productStandardId:null,standardVersionId:null,machineStandardId:Number(row.id),standardOutput:out,standardTimeSeconds:Number(row.standard_time_seconds)>0?Number(row.standard_time_seconds):null,excludeKqdFromTt:0,effectiveFrom:row.effective_from?String(row.effective_from).slice(0,10):null,effectiveTo:row.effective_to?String(row.effective_to).slice(0,10):null,source:Number(row.is_active)===1?'MACHINE':'MACHINE_HISTORICAL',workDate:date,historicalVersionAvailable:true,machineId:Number(machine.id),machineCode:machine.machine_code};standardCache.set(standardKey,r);return r;}}}
    const processAutoEligible=pid===1&&(isAuto||['AUTO','AUTOMATIC'].includes(String(workType||'').trim().toUpperCase()));
    const product=await resolveProduct({processId:pid,productCode:requestedProduct,workDate:date,standardVersionId:requestedVersionId,allowAutoAlias:processAutoEligible,workType:resolvedWorkType});
    const resolved={...product,machineId:machine?Number(machine.id):null,machineCode:machine?machine.machine_code:null,machineStandardId:null,source:`${product.source}_MACHINE_FALLBACK`};standardCache.set(standardKey,resolved);return resolved;
  }
  async function validateProductVersionRange({processId,productCode,effectiveFrom,effectiveTo=null,excludeVersionId=null}){const from=normalizeWorkDate(effectiveFrom),to=effectiveTo?normalizeWorkDate(effectiveTo):null;if(to&&to<from)throw businessError('INVALID_STANDARD_EFFECTIVE_RANGE','Ngày kết thúc định mức phải từ ngày bắt đầu trở đi');const rows=await query(`SELECT id FROM product_standard_versions WHERE process_id=? AND product_code=? AND status='active' AND (? IS NULL OR id<>?) AND effective_from<=COALESCE(?, '9999-12-31') AND (effective_to IS NULL OR effective_to>=?) LIMIT 2`,[Number(processId),String(productCode||'').trim(),excludeVersionId?Number(excludeVersionId):null,excludeVersionId?Number(excludeVersionId):null,to,from]);if(rows.length)throw businessError('STANDARD_EFFECTIVE_RANGE_CONFLICT','Khoảng hiệu lực định mức bị chồng lấn',{conflicting_version_ids:rows.map(r=>Number(r.id))});return true;}
  return {resolveProduct,resolveStandard,validateProductVersionRange};
}
function assertStandardSnapshotConsistency({resolved,standardOutput,standardVersionId,machineStandardId=null}){const savedOutput=Number(standardOutput),hasSavedOutput=Number.isFinite(savedOutput)&&savedOutput>0,outputMatches=Boolean(resolved)&&sameDecimal(resolved.standardOutput,standardOutput),versionMatches=Number(resolved?.standardVersionId||0)===Number(standardVersionId||0),machineMatches=Number(resolved?.machineStandardId||0)===Number(machineStandardId||0),hasMachineSnapshotId=Number(machineStandardId||0)>0,hasProductSnapshotId=Number(standardVersionId||0)>0;if(hasMachineSnapshotId&&(!outputMatches||!machineMatches||(hasProductSnapshotId&&!versionMatches)))throw businessError('STANDARD_SNAPSHOT_MISMATCH','Định mức đã lưu không khớp nguồn định mức lịch sử',{saved_standard_output:standardOutput??null,saved_standard_version_id:standardVersionId??null,saved_machine_standard_id:machineStandardId??null,expected_standard_output:resolved?.standardOutput??null,expected_standard_version_id:resolved?.standardVersionId??null,expected_machine_standard_id:resolved?.machineStandardId??null,expected_source:resolved?.source??null});if(hasProductSnapshotId&&!hasMachineSnapshotId){if(!hasSavedOutput||!versionMatches)throw businessError('STANDARD_SNAPSHOT_MISMATCH','Định mức đã lưu không khớp nguồn định mức lịch sử');return true;}if(!hasProductSnapshotId&&!hasMachineSnapshotId){if(!hasSavedOutput)throw businessError('STANDARD_SNAPSHOT_MISMATCH','Định mức đã lưu không khớp nguồn định mức lịch sử');return true;}if(!resolved||!outputMatches||!versionMatches||!machineMatches)throw businessError('STANDARD_SNAPSHOT_MISMATCH','Định mức đã lưu không khớp nguồn định mức lịch sử');return true;}
const runtimeResolver=createStandardResolver();
module.exports={...runtimeResolver,createStandardResolver,assertStandardSnapshotConsistency,normalizeWorkDate,businessError};