/*
 * KTC template master data extracted directly from file mẫu(5).xlsx.
 * Source: Form nhập + process-specific input sheets.
 * SX3 is intentionally excluded from the worker production-process master.
 */
module.exports = {
  "GC": {"id":1,"name":"Cắt/Lồng","deductions":["Thiếu sản lượng","Bật máy, xét máy","Chuyển mã","Chỉnh máy","Chờ chỉnh máy","Mất điện","Mất khí","Chờ hàng","bảo dưỡng máy","Nghỉ giải lao","Giao ca","Dừng máy đi hỗ trợ","Giặt cs/cân cs, tuốt-tái pp, GL","5s","Học việc, đào tạo","Đi muộn về sớm"],"defects":["KQD","Vỡ / cao su","K xước / cong gãy","Cao su xoay","Cắt /  không đứt","bavia","CSH","ppcm","KT lớn","KT nhỏ","LCS","cắt lẹm","rách nvl","Chân ngắn dài","sót via","fure trục"]},
  "MAI": {"id":2,"name":"Mài","deductions":["Thiếu sản lượng","Bật máy, xét máy, đầu giờ","Chuyển mã","Chỉnh máy","Chờ chỉnh máy","Mài đá","Bảo dưỡng máy","Ko có KHSX, Dừng máy ko HT","Chờ hàng, / hết hàng","Khí yếu","Nghỉ giải lao","Giao ca","Dừng máy đi hỗ trợ","5s, đổ bụi,xì bụi,lấy bụi","Học việc","Thổi bụi,lấy bụi","Đi đo kiểm soát","Đi muộn/về sớm","Tắt máy hút bụi","mất điện"],"defects":["KQD / ĐẢO","Xô cs","PPCM / Mất điện","Hàng rơi","K- coleet","Thiếu - lẫn cs / CSH","Lỗi cao su"]},
  "K1": {"id":3,"name":"Kiểm 1","deductions":["Công việc trừ giờ","Đi muộn, về sớm","trừ giờ xlbv (người làm)"],"defects":["Dị vật / do NVL","DV do / SX1","DV dính via","Bẩn / do NVL","Bẩn (đen, trắng,vàng)","Bẩn /  khuôn","Bẩn chờ giặt, chờ xử lý","phồng","Biến dạng","Cách /   bậc","Thiếu / NL","Bít lỗ","NG kích /  thước","Tắc /  vòi","Hở sắt","Lỗi khuôn","hằn","Rách /  ĐPK (ren, vành)","Rách (bề mặt)","Rách lỗ rót, lỗ khí","rách đầu","rách thân, tai","Rách do / XLBV (sx1)","Dính bavia","Bavia, rách lòng trong","Chờ XLBV","Rách do / XLBV (bên ngoài)","bong cao su","Rách lòng trong","Khác  / màu","Loang đen, màu","lỗi khác(hàng mềm), mẻ","Tạp chất / do NVL","Bẩn chờ giặt","NG KT","Rách /  ĐPK","Rách","Rách lỗ rót","Xước sơn","HỞ SẮT","Rách do / XLBV","Bavia lòng trong","Loang màu"]},
  "K2": {"id":4,"name":"Kiểm 2","deductions":["Thiếu sản lượng","Nghỉ giải lao","5s","chuyển mã","lau ố, lau gót chống","lăn mốc","hỗ trợ","Lau khay,lọc khay","Quét hàng, thổi bụi","Giao Ca","Học kiểm, đào tạo","check hàng","Xem MGH, mất điện","lấy hàng và cất hàng","Đi muộn về sớm"],"defects":["Nứt vỡ, CSN, /  KĐĐ","Cắt lẹm , / CP, 502","cs bẩn (hủy)","Bavia do cắt, không chân số","Lõm csu","Đảo, BD, HV","Mặt mài","Lẫn csu, thiếu cs","Không ĐT","Lồng- mài / ngược","Coleet, K gót","K rãnh","K do /  gia lưu","K  / do gá","K va /  vào đá","Trục xước, bv trục","Dập trục","Bẩn Trục","Trục sét, / lớp mạ","KNCC","BV đầu vào","Rỗ khí","Lỗ rách","Rách lòng / trong","Rách cs / non","Dị vật","Mài sót","MM / Loang- sần, lõm","Mẻ cạnh, / mẻ bánh răng","Nứt đường / phân khuôn","lẫn NVL","Bẩn NCC","Mốc cs","Chân bánh răng ngắn-dài, Cao su ngắn","Cao su dài","CHÂN BV SÂU, thiếu gate, chân gate cao","mm thô","NDPK","hằn cs,nhăn","LBM","rách ngang","CS BÓNG","NG-bàn đá","CS móp","Bavia bánh răng","KHOẢNG SÁNG","Lỗi rót","Khác","Tên lỗi khác(KĐTâm)","hckt","Tái đi CVN","THIẾU LIỆU","CHỜ XLBV"]},
  "DO": {"id":60001,"name":"Đo","deductions":["Thiếu sản lượng","Chỉnh máy","Mất điện","Ko có KHSX","Chờ chỉnh máy","Nghỉ giải lao","Giao ca","Dừng máy đi hỗ trợ","5s/lấy bụi","Rải hàng, mài, cv khác","Lưu DL","KS DF, KS đầu giờ","Thổi bụi","Khác,đẩy hàng xuất,","Đi muộn về sớm","kiểm kho","Học việc, đào tạo"],"defects":["Lớn","Nhỏ","Fure / cao su","Fur / trục","Lẫn hàng"]},
  "CAN": {"id":60002,"name":"Cán","deductions":["Vệ sinh máy cán","Sửa máy","Nghỉ giải lao","5S","Dừng sản xuất","CAN HC"],"defects":["Chân không","Rách vỡ","Bề mặt","Bavia"]},
  "EP": {"id":60003,"name":"Ép","deductions":["Vệ sinh khuôn","Thay khuôn","5s + giao ca","Hâm khuôn","Sửa khuôn","SUA MAY","Nghỉ giải lao","DUNG MAY"],"defects":["Chân không","Rách vỡ","TNL","Dính via","Di vật","dính khuôn","Tạp chất"]},
  "XLBV": {"id":60004,"name":"XLBV","deductions":[],"defects":["CHÂN KHÔNG","RÁCH VỠ","XLBV","BẨN KHUÔN","TNL","DỊ VẬT","KHOAN KO HẾT","BIẾN DẠNG","HỞ SẮT","xước trục","CHỜ XL LAI BV","KHÁC MÀU","BẨN","KO QUA ZICK"]}
};
