const express=require('express');
const router=express.Router();
const auth=require('../middleware/authMiddleware');
const role=require('../middleware/roleMiddleware');
const permission=require('../middleware/permissionMiddleware');
const c=require('../controllers/governanceController');
router.use(auth,role('admin','manager'));
router.get('/summary',permission('GOVERNANCE_VIEW'),c.summary);
router.get('/period-locks',permission('GOVERNANCE_VIEW'),c.listLocks);
router.post('/period-locks',permission('PERIOD_LOCK'),c.lockPeriod);
router.patch('/period-locks/:id/unlock',role('admin'),permission('PERIOD_UNLOCK'),c.unlockPeriod);
router.get('/plans',permission('GOVERNANCE_VIEW'),c.listPlans);
router.post('/plans',permission('GOVERNANCE_VIEW'),c.createPlan);
router.get('/validation-issues',permission('GOVERNANCE_VIEW'),c.validationIssues);
module.exports=router;
