'use strict';
const db=require('../config/db');
const requiredTables=['users','workers','production_reports','production_reports_temp','production_report_defects','production_report_deductions','production_report_machine_lines','machine_production_events','product_standards','product_standard_versions','user_sessions','production_report_duplicate_locks'];
const requiredColumns=[['production_reports','standard_version_id'],['production_reports','training_percent_snapshot'],['production_reports','exclude_kqd_from_tt_snapshot'],['production_reports','machine_event_id'],['production_reports_temp','logical_duplicate_key'],['user_sessions','family_id'],['user_sessions','consumed_at'],['user_sessions','replaced_by_id'],['user_sessions','reuse_detected_at'],['production_formula_settings','effective_from'],['production_formula_settings','effective_to']];
const orphanChecks=[
 ['REPORT_WORKER_ORPHAN',`SELECT COUNT(*) n FROM production_reports r LEFT JOIN workers w ON w.id=r.worker_id WHERE w.id IS NULL`],
 ['REPORT_PROCESS_ORPHAN',`SELECT COUNT(*) n FROM production_reports r LEFT JOIN processes p ON p.id=r.process_id WHERE p.id IS NULL`],
 ['MACHINE_LINE_REPORT_ORPHAN',`SELECT COUNT(*) n FROM production_report_machine_lines m LEFT JOIN production_reports r ON r.id=m.report_id WHERE r.id IS NULL`],
 ['VERSION_REPORT_ORPHAN',`SELECT COUNT(*) n FROM production_report_versions v LEFT JOIN production_reports r ON r.id=v.report_id WHERE r.id IS NULL`],
];
async function main(){ await db.testConnection(); const q=db.promise(); const [tables]=await q.query(`SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE()`); const set=new Set(tables.map(r=>String(r.TABLE_NAME))); const missing=requiredTables.filter(t=>!set.has(t)); if(missing.length) throw Object.assign(new Error(`Missing tables: ${missing.join(',')}`),{code:'RESTORE_REQUIRED_TABLE_MISSING'}); for(const [t,c] of requiredColumns){ const [rows]=await q.query(`SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=? LIMIT 1`,[t,c]); if(!rows.length) throw Object.assign(new Error(`Missing column ${t}.${c}`),{code:'RESTORE_REQUIRED_COLUMN_MISSING'}); } for(const [code,sql] of orphanChecks){ const [rows]=await q.query(sql); if(Number(rows[0]?.n||0)!==0) throw Object.assign(new Error(`${code}:${rows[0]?.n}`),{code:'RESTORE_REFERENCE_INTEGRITY_FAILED'}); } console.log(JSON.stringify({success:true,required_tables:requiredTables.length,required_columns:requiredColumns.length,reference_checks:orphanChecks.length},null,2)); }
main().catch(e=>{console.error(`[KTC][F16] Post-restore verify failed: ${e.code||e.message}`);process.exitCode=1;}).finally(()=>db.closePool().catch(()=>{}));
