const fs = require('node:fs');
const path = require('node:path');
const root=path.join(__dirname,'..','electron');
const main=fs.readFileSync(path.join(root,'main.cjs'),'utf8');
const preload=fs.readFileSync(path.join(root,'preload.cjs'),'utf8');
const workbook=fs.readFileSync(path.join(root,'monthlyWorkbookLocal.cjs'),'utf8');
const sync=fs.readFileSync(path.join(root,'excelDbSync.cjs'),'utf8');
if(!/_KTC_SYNC/.test(workbook)) throw new Error('Thiếu metadata sheet _KTC_SYNC');
if(!/veryHidden/.test(workbook)) throw new Error('_KTC_SYNC phải veryHidden');
if(!/production\/excel-sync/.test(main)) throw new Error('Desktop chưa gọi API Excel->DB');
if(!/REPORT_VERSION_CONFLICT|expected_updated_at/.test(sync)) throw new Error('Thiếu optimistic concurrency metadata');
if(!/ktc-preview-excel-db-sync/.test(main) || !/ktc-apply-excel-db-sync/.test(main)) throw new Error('Thiếu IPC preview/apply Excel -> DB');
if(!/previewExcelDbSync/.test(preload) || !/applyExcelDbSync/.test(preload)) throw new Error('Preload chưa expose manual Excel -> DB');
if(/setInterval\(\(\) => void syncEditedExcelFilesToDb/.test(main)) throw new Error('Không được tự động Excel -> DB bằng watcher');
if(!/EXCEL_UNSYNCED_CHANGES/.test(main)) throw new Error('Thiếu guard chống ghi đè Excel chưa sync');
if(!/preview/.test(sync) || !/SL OK/.test(sync)) throw new Error('Thiếu diff preview trước -> sau');
console.log('[KTC] Excel <-> DB manual preview/apply contract OK');
