const fs=require('node:fs');
const path=require('node:path');
const ExcelJS=require('exceljs');
const {PROCESS_SHEETS,PROCESS_FILE_PREFIXES}=require('../electron/monthlyWorkbookLocal.cjs');
const root=path.resolve(process.argv[2]||'.');
const month=String(process.argv[3]||'').trim();
if(!/^\d{4}-\d{2}$/.test(month)){console.error('Cách dùng: node scripts/validateExcelFolder.cjs <folder> YYYY-MM');process.exit(2);}
const [year,mm]=month.split('-'); const suffix=`${mm}-${year}.xlsx`; const expected=['00_TONG_HOP_SAN_XUAT_'+suffix,...Object.keys(PROCESS_SHEETS).map(c=>`${PROCESS_FILE_PREFIXES[c]}_${suffix}`)];
(async()=>{ const errors=[]; for(const name of expected) if(!fs.existsSync(path.join(root,name))) errors.push(`Thiếu file ${name}`); if(errors.length) throw new Error(errors.join('\n'));
 for(const [code,cfg] of Object.entries(PROCESS_SHEETS)){ const name=`${PROCESS_FILE_PREFIXES[code]}_${suffix}`; const wb=new ExcelJS.Workbook(); await wb.xlsx.readFile(path.join(root,name)); const visible=wb.worksheets.filter(s=>!['hidden','veryHidden'].includes(s.state)).map(s=>s.name); if(visible.length!==1||visible[0]!==cfg.sheet) errors.push(`${name}: sheet hiển thị ${visible.join(',')}`); const sync=wb.getWorksheet('_KTC_SYNC'); if(!sync||sync.state!=='veryHidden') errors.push(`${name}: thiếu _KTC_SYNC veryHidden`); const sh=wb.getWorksheet(cfg.sheet); if(!sh) continue; const header=sh.getRow(5).values.map(v=>String(v||'')); for(const h of ['Mã NV','Tên NV','Thời gian nhập','% học việc','Định mức','OK','Tổng NG','SP công nhân nhập','Tổng SP quy đổi','SP/giờ','Tỷ lệ đạt','Tỷ lệ NG']) if(!header.includes(h)) errors.push(`${name}: thiếu cột ${h}`); if(header.includes('Ngày báo cáo')) errors.push(`${name}: không được lặp cột Ngày báo cáo trên từng dòng`); const view=sh.views?.[0]||{}; if(view.xSplit!==4||view.ySplit!==5||view.topLeftCell!=='E6') errors.push(`${name}: freeze phải xSplit=4,ySplit=5,topLeftCell=E6`); let activeDate=null,expectedStt=0,dataRows=0; for(let r=6;r<=sh.rowCount;r++){ const a=sh.getCell(r,1); const value=a.value; if(typeof value==='string'&&/^\d{2}\/\d{2}\/\d{4}$/.test(value)){ activeDate=value; expectedStt=0; if(!a.isMerged) errors.push(`${name}: dòng ngày ${r} phải merge A:D`); for(let c=5;c<=sh.columnCount;c++) if(sh.getCell(r,c).value!==null) errors.push(`${name}: dòng ngày ${r} phải trống ngoài A:D`); continue; } if(typeof value==='number'){ dataRows++; expectedStt++; if(!activeDate) errors.push(`${name}: dòng dữ liệu ${r} không có hàng ngày phía trước`); if(Number(value)!==expectedStt) errors.push(`${name}: STT dòng ${r}=${value}, mong đợi ${expectedStt}`); const entry=sh.getCell(r,header.indexOf('Thời gian nhập')); if(!entry.value) errors.push(`${name}: dòng ${r} thiếu Thời gian nhập`); } } if(dataRows===0) console.warn(`[KTC] ${name}: không có dòng dữ liệu trong tháng ${month}`); }
 const sum=new ExcelJS.Workbook(); await sum.xlsx.readFile(path.join(root,'00_TONG_HOP_SAN_XUAT_'+suffix)); for(const sh of ['BÌA','TỔNG HỢP THÁNG','ĐỐI CHIẾU DỮ LIỆU']) if(!sum.getWorksheet(sh)) errors.push(`00 tổng hợp thiếu sheet ${sh}`);
 if(errors.length) throw new Error(errors.join('\n')); console.log(JSON.stringify({success:true,folder:root,month,files:expected.length,processes:Object.keys(PROCESS_SHEETS).length},null,2));
})().catch(e=>{console.error('[KTC] Excel folder validation failed:\n'+e.message);process.exit(1);});
