-- KTC TEST 046: authoritative GC worker master from Mã hóa (2).xlsx.
-- Deletes only the current GC worker roster. Lead/Manager/Admin and workers assigned to other processes stay intact.
-- Code rule: given name, lowercase ASCII, no spaces; duplicate given names get -2/-3; 49xxx -> 49-xxx.
SET @gc_process_id := (SELECT id FROM processes WHERE UPPER(TRIM(process_code))='GC' LIMIT 1);
DROP TEMPORARY TABLE IF EXISTS tmp_old_gc_workers_20260924;
CREATE TEMPORARY TABLE tmp_old_gc_workers_20260924(worker_id BIGINT PRIMARY KEY,user_id BIGINT NOT NULL);
INSERT INTO tmp_old_gc_workers_20260924 SELECT DISTINCT w.id,w.user_id FROM workers w JOIN users u ON u.id=w.user_id JOIN worker_processes wp ON wp.worker_id=w.id WHERE wp.process_id=@gc_process_id AND u.role='worker';
DELETE FROM worker_processes WHERE process_id=@gc_process_id;
DELETE w FROM workers w JOIN tmp_old_gc_workers_20260924 x ON x.worker_id=w.id LEFT JOIN worker_processes wp ON wp.worker_id=w.id WHERE wp.worker_id IS NULL;
DELETE u FROM users u JOIN tmp_old_gc_workers_20260924 x ON x.user_id=u.id LEFT JOIN workers w ON w.user_id=u.id WHERE w.id IS NULL AND u.role='worker';
DROP TEMPORARY TABLE IF EXISTS tmp_gc046;
CREATE TEMPORARY TABLE tmp_gc046(worker_code VARCHAR(160) PRIMARY KEY,worker_name VARCHAR(255) NOT NULL);
INSERT INTO tmp_gc046(worker_code,worker_name) VALUES ('dung','Lê Thị Dung'),('chuong','Mùi Văn Chường'),('huynh','Điêu Chính Huynh'),('lieu','Vì Thị Liệu'),('thanh','Mùi Văn Thanh'),('hanh','Vàng văn Hạnh'),('lam','Mùi Văn Lâm'),('nghe','Vừ A Nghệ'),('hien','Xồng Y Hiền'),('thanh-2','Hà Tiến Thành'),('na','Lầu Thị Na'),('thanh-3','Lò Văn Thành'),('vu','Giàng Mí Vư'),('mai','Và Y Mái'),('chau','Vàng Thị Quỳnh Châu'),('dinh','Mùa Cang Dinh'),('thiep','Bùi Tiến Thiệp'),('diep','Đinh Thị Lâm Diệp'),('mu','Lò Thị Mư'),('hoan','Hoàng Thị Hoan'),('la','La Văn La'),('tien','Quàng Thị Tiến'),('an','Hoàng VĂn Án'),('tu','Nông Anh Tú'),('tin','Hoàng Thị Kim Tin'),('hon','Chương Văn Hôn'),('manh','Giàng A Mạnh'),('dong','Giàng Thị Đông'),('nanh','Vừ A Nánh'),('tuan','Nguyễn Quang Tuấn'),('vinh','Nguyễn Đức Vinh'),('ngan','Nguyễn Thị Ngân'),('thieu','Vì Thị Thiếu'),('nhuong','Bùi Văn Nhượng'),('nga','Đinh Thị Nga'),('luu','Đinh Văn Lưu'),('huyen','Lường Văn Huyên'),('vien','Cầm Thị Viến'),('vat','Mùi Văn Vặt'),('van','Đinh Thị Vân'),('ma','Lý A Mà'),('hao','Phạm Văn Hào'),('tuan-2','Giàng A Tuấn'),('mua','Sùng Mí Mua'),('don','Vàng A Đon'),('diep-2','Mùi Thị Ngọc Diệp'),('phanh','Vàng Mười Phành'),('linh','Vàng A Linh'),('say','Sùng Mí Say'),('hoa','Và Thị Hoa'),('no','Giàng A Nọ'),('cuc','Đinh Thị Cúc'),('si','Vì Văn Sĩ'),('thuy','Đinh Thị Thùy'),('tan','Đinh Thị Tân'),('hanh-2','Lò Thị Hạnh'),('duan','Đinh Thị Duân'),('gia','Mua Mí Già'),('dieu','Giàng Seo Diêu'),('vang','Giàng A Váng'),('khanh','Lê văn Khánh'),('ngan-2','Lục Văn Ngân'),('49-046','Đỗ Trung Anh'),('49-049','Phạm Gia Bách'),('49-050','Vũ Việt Bách'),('49-052','Hà Việt Bút'),('49-055','Nguyễn Đức Hiếu'),('49-056','Phạm Trung Hiếu'),('49-059','Phạm Gia Huy'),('49-064','Đào Anh Minh'),('49-065','Phan Bảo Minh'),('49-073','Nguyễn Ngọc Minh Trí'),('49-076','Bùi Tuấn Lâm'),('49-078','Lê Nhật Bảo Long'),('49-084','Nguyễn Hải Thanh'),('49-025','Đặng Thế Bảo'),('49-026','Nguyễn Tiến Công'),('49-027','Nguyễn Minh Đức'),('49-028','Đỗ Duy Hoàng Dương'),('49-030','Bùi Đức Huy'),('49-032','Nguyễn Dương Chí Kiên'),('49-038','Nguyễn Trọng Tấn'),('49-040','Vũ Viết Thái'),('49-042','Hoàng Tuấn Tú'),('49-044','Hoàng Minh Tùng'),('49-001','Nguyễn Đức Anh'),('49-002','Vũ Mạnh Hoàng Anh'),('49-014','Phùng Gia Phát'),('49-015','Lê Minh Phúc'),('49-022','Trần Hoàng Trung');
INSERT INTO users(username,password,full_name,role,status) SELECT t.worker_code,'',t.worker_name,'worker','active' FROM tmp_gc046 t LEFT JOIN users u ON LOWER(TRIM(u.username))=LOWER(TRIM(t.worker_code)) WHERE u.id IS NULL;
INSERT INTO workers(user_id,worker_code,phone,department,position,training_percent,status) SELECT u.id,t.worker_code,NULL,'Sản xuất','Công nhân',100,'active' FROM tmp_gc046 t JOIN users u ON LOWER(TRIM(u.username))=LOWER(TRIM(t.worker_code)) LEFT JOIN workers w ON w.user_id=u.id WHERE w.id IS NULL;
UPDATE users u JOIN tmp_gc046 t ON LOWER(TRIM(u.username))=LOWER(TRIM(t.worker_code)) SET u.full_name=t.worker_name,u.role='worker',u.status='active';
INSERT IGNORE INTO worker_processes(worker_id,process_id) SELECT w.id,@gc_process_id FROM workers w JOIN tmp_gc046 t ON t.worker_code=w.worker_code WHERE @gc_process_id IS NOT NULL;
DROP TEMPORARY TABLE tmp_gc046;
DROP TEMPORARY TABLE tmp_old_gc_workers_20260924;
