import { getAccessToken } from "../utils/authStorage";
import api from "./api";
import { clearSessionCache, getSessionCached } from "./sessionCache";
import type { ProductionDeduction, ProductionDefect, ProductionReport } from "../types/production";

export interface CompanyNetworkAccess { allowed:boolean; restricted:boolean; enforced:boolean; configured:boolean; client_ip:string; message:string; }
export const getCompanyNetworkAccess=async(forceRefresh=false):Promise<CompanyNetworkAccess>=>{const loader=async()=>{const res=await api.get("/network/access");return res.data?.data||res.data;};if(forceRefresh)return loader();return getSessionCached("network-access",5*60*1000,loader);};
export const createTempReport=async(data:ProductionReport)=>{const res=await api.post("/production-temp",data,{timeout:30000});return res.data;};
export interface SimilarReportCheckResponse{success:boolean;duplicate:boolean;data:{id:number;status:string;work_date:string;shift:string;machine_no:string;product_name:string}|null;message:string;}
export const checkSimilarTempReport=async(data:Pick<ProductionReport,"process_id"|"work_date"|"shift"|"machine_no"|"product_name">):Promise<SimilarReportCheckResponse>=>{const res=await api.post("/production-temp/check-similar",data);return res.data;};
export const getTempDates=async()=>{const res=await api.get("/production-temp/dates");return res.data.data||res.data||[];};
export const getTempReportsByDate=async(date:string):Promise<ProductionReport[]>=>{const res=await api.get(`/production-temp/by-date?date=${date}`);return res.data.data||res.data||[];};
export const getTempReportById=async(id:number):Promise<ProductionReport>=>{const res=await api.get(`/production-temp/${id}`,{params:{_t:Date.now()}});return res.data.data||res.data;};
export const getTempReportDetail=async(id:number):Promise<ProductionReport>=>getTempReportById(id);
export const getMyTempReports=async()=>{const res=await api.get("/production-temp/my");return res.data.data||res.data||[];};
export interface ManagerReportPagination{page:number;page_size:number;total:number;total_pages:number;}
export interface ManagerReportPage{data:ProductionReport[];pagination:ManagerReportPagination;processes?:string[];previous_count?:number;}
export interface PendingReportFilters{dateFrom?:string;dateTo?:string;shift?:string;processId?:number|string;processName?:string;search?:string;page?:number;pageSize?:number;}
const normalizeManagerReportPage=(payload:any):ManagerReportPage=>({data:Array.isArray(payload?.data)?payload.data:Array.isArray(payload)?payload:[],pagination:{page:Number(payload?.pagination?.page||1),page_size:Number(payload?.pagination?.page_size||20),total:Number(payload?.pagination?.total||(Array.isArray(payload?.data)?payload.data.length:0)),total_pages:Math.max(1,Number(payload?.pagination?.total_pages||1))},processes:Array.isArray(payload?.processes)?payload.processes:undefined,previous_count:Number(payload?.previous_count||0)});
export const getPendingReports=async(filters:PendingReportFilters={}):Promise<ManagerReportPage>=>{const key=["manager-pending",filters.dateFrom||"",filters.dateTo||"",filters.shift||"",filters.processId||"",filters.processName||"",filters.search?.trim()||"",filters.page||1,filters.pageSize||20].join(":");return getSessionCached(key,15000,async()=>{const res=await api.get("/production-temp/pending",{params:{date_from:filters.dateFrom||undefined,date_to:filters.dateTo||undefined,shift:filters.shift,process_id:filters.processId||undefined,process_name:filters.processName,search:filters.search?.trim(),page:filters.page||1,page_size:filters.pageSize||20,include_meta:1}});return normalizeManagerReportPage(res.data);});};
export interface ApprovedReportFilters extends PendingReportFilters{}
export const getApprovedReports=async(filters:ApprovedReportFilters={}):Promise<ManagerReportPage>=>{const key=["manager-approved-v2",filters.dateFrom||"",filters.dateTo||"",filters.shift||"",filters.processId||"",filters.processName||"",filters.search?.trim()||"",filters.page||1,filters.pageSize||20].join(":");return getSessionCached(key,15000,async()=>{const res=await api.get("/production/");const source=Array.isArray(res.data?.data)?res.data.data:Array.isArray(res.data)?res.data:[];const from=filters.dateFrom||"0000-01-01",to=filters.dateTo||"9999-12-31",pid=filters.processId==null?null:Number(filters.processId);const q=filters.search?.trim().toLowerCase()||"";const filtered=source.filter((r:any)=>{const date=String(r.work_date||"").slice(0,10);if(date<from||date>to)return false;if(filters.shift&&String(r.shift||"")!==String(filters.shift))return false;if(pid!=null&&Number(r.process_id)!==pid)return false;if(filters.processName&&String(r.process_name||"").toLowerCase()!==String(filters.processName).toLowerCase())return false;if(q&&!([r.worker_code,r.full_name,r.machine_no,r.product_name,r.process_name].some(v=>String(v??"").toLowerCase().includes(q))))return false;return true;}).map((r:any)=>({...r,training_percent:r.training_percent_snapshot??r.training_percent??r.hv_percent??r.learning_percent??r.hoc_viec_percent??0})).sort((a:any,b:any)=>String(b.work_date||"").localeCompare(String(a.work_date||""))||Number(b.id)-Number(a.id));const page=Math.max(1,Number(filters.page||1)),pageSize=Math.max(1,Number(filters.pageSize||20)),start=(page-1)*pageSize;return{data:filtered.slice(start,start+pageSize),pagination:{page,page_size:pageSize,total:filtered.length,total_pages:Math.max(1,Math.ceil(filtered.length/pageSize))}};});};
export const invalidatePendingReportCache=()=>clearSessionCache("manager-pending");
export const invalidateApprovedReportCache=()=>clearSessionCache("manager-approved");
export const invalidateManagerReportCaches=()=>{clearSessionCache("manager-pending");clearSessionCache("manager-approved");clearSessionCache("manager-approved-v2");};
export const getReports=async():Promise<ProductionReport[]>=>(await getApprovedReports()).data;
export const getReportById=async(id:number,source?:string|null)=>{const normalizedSource=String(source||"").toLowerCase();const url=normalizedSource==="pending"||normalizedSource==="temp"?`/production-temp/${id}`:`/production/${id}`;const res=await api.get(url);return res.data.data||res.data;};
export const updateReport=async(id:number,data:ProductionReport,source:"pending"|"approved"="approved",expectedUpdatedAt:string|null=null)=>{const endpoint=source==="pending"?`/production-temp/${id}`:`/production/${id}`;const payload=source==="approved"?{...data,expected_updated_at:expectedUpdatedAt||undefined}:data;const res=await api.put(endpoint,payload);return res.data;};
export const updateTempReport=async(id:number,data:ProductionReport)=>{const res=await api.put(`/production-temp/${id}`,{...data,expected_updated_at:data.updated_at||undefined});return res.data;};
export const deleteReport=async(id:number,reason:string)=>{const res=await api.delete(`/production/${id}`,{data:{reason:String(reason||"").trim()}});return res.data;};
export const createApprovedReportFromExcel=async(data:ProductionReport)=>{const res=await api.post("/production/excel-sync",{changes:[{create:true,data,source:{file:"Manager Web",sheet:"Quản lý báo cáo"}}]});const result=res.data?.results?.[0];if(!result?.success)throw new Error(result?.message||res.data?.message||"Không thể thêm báo cáo");return result;};
const downloadExcel=(data:BlobPart,filename:string)=>{const blob=new Blob([data],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});const url=window.URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();window.URL.revokeObjectURL(url);};
export const exportProductionExcel=async(date:string)=>{const res=await api.get(`/reports/export-excel?date=${date}&type=pending`,{responseType:"blob"});downloadExcel(res.data,`BaoCaoChoDuyet_${date}.xlsx`);};
export const getApprovedDates=async()=>{const res=await api.get("/production/dates");return res.data.data||res.data||[];};
export const getApprovedReportsByDate=async(date:string):Promise<ProductionReport[]>=>((await getApprovedReports({dateFrom:date,dateTo:date})).data);
export const exportApprovedExcel=async(date:string)=>{const res=await api.get(`/reports/export-excel?date=${date}&type=approved`,{responseType:"blob"});downloadExcel(res.data,`BaoCaoDaDuyet_${date}.xlsx`);};
export type TempReviewTarget={id:number;expected_updated_at?:string|null};
const normalizeTempReviewTargets=(items:Array<number|TempReviewTarget>)=>items.map(item=>typeof item==="number"?{id:item,expected_updated_at:null}:{id:Number(item.id),expected_updated_at:item.expected_updated_at||null});
export const approveSelectedTempReports=async(items:Array<number|TempReviewTarget>)=>{const targets=normalizeTempReviewTargets(items);const res=await api.post("/production-temp/approve-selected",{ids:targets.map(item=>item.id),targets});invalidateManagerReportCaches();return res.data;};
export const rejectSelectedTempReports=async(items:Array<number|TempReviewTarget>,reason:string)=>{const targets=normalizeTempReviewTargets(items);const res=await api.post("/production-temp/reject-selected",{ids:targets.map(item=>item.id),targets,reason});invalidateManagerReportCaches();invalidatePendingReportCache();return res.data;};
export interface MachineProductionEventDefectInput{defect_type_id?:number;defect_code?:string;quantity:number;responsible_worker_id:number;}
export interface MachineProductionEvent{ id:number;process_id:number;machine_id:number;machine_code:string;product_code:string;work_date:string;shift:string;physical_ok_quantity:number;physical_ng_quantity?:number;physical_counted_output:number;physical_total_output?:number;credited_output?:number;machine_time_hours:number;maximum_output?:number;standard_output?:number;standard_source?:string|null;exclude_kqd_from_tt_snapshot?:number|null;status:string;defects?:MachineProductionEventDefectInput[];participants?:Array<{worker_id:number;machine_line_id?:number;report_id?:number}>;[key:string]:unknown;}
export interface MachineProductionEventInput{process_id:number;machine_id?:number|null;machine_code:string;product_code:string;work_date:string;shift:string;physical_ok_quantity:number;machine_time_hours:number;defects?:MachineProductionEventDefectInput[];temp_machine_line_ids?:number[];}
export interface MachineProductionEventUpdate{physical_ok_quantity?:number;machine_time_hours?:number;defects?:MachineProductionEventDefectInput[];}
export const createMachineProductionEvent=async(data:MachineProductionEventInput):Promise<MachineProductionEvent>=>{const res=await api.post("/machine-production-events",data);return res.data?.data??res.data;};
export const getMachineProductionEvent=async(eventId:number):Promise<MachineProductionEvent>=>{const res=await api.get(`/machine-production-events/${eventId}`);return res.data?.data??res.data;};
export const updateMachineProductionEvent=async(eventId:number,patch:MachineProductionEventUpdate):Promise<MachineProductionEvent>=>{const res=await api.put(`/machine-production-events/${eventId}`,patch);return res.data?.data??res.data;};
export const linkMachineEventParticipants=async(eventId:number,participantIds:number[])=> (await api.post(`/machine-production-events/${eventId}/participants`,{participant_ids:participantIds})).data;
export const approveMachineProductionEvent=async(eventId:number)=>(await api.post(`/machine-production-events/${eventId}/approve`)).data;
export interface ReportActionLog{id:number;report_type:"temp"|"approved";report_id:number;action:string;note?:string|null;full_name?:string|null;username?:string|null;role?:string|null;created_at:string;}
export const getTempReportActionLogs=async(id:number):Promise<ReportActionLog[]>=>{const res=await api.get(`/production-temp/${id}/logs`);return res.data?.data||[];};
export interface ExcelExportResult{success:boolean;skipped?:boolean;code?:string;reason?:string;message?:string;files?:Array<{processName?:string;processCode?:string;success?:boolean;error?:string;saved?:boolean;pendingPath?:string|null}>;[key:string]:unknown;}
export const exportSelectedApprovedExcel=async(date:string):Promise<ExcelExportResult>=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new Error("Ngày xuất Excel không hợp lệ");const isElectronRuntime=Boolean(window.ktcDesktop?.isDesktop)||navigator.userAgent.toLowerCase().includes("electron");if(isElectronRuntime){if(!window.ktcDesktop?.isDesktop||typeof window.ktcDesktop.syncAllExcel!=="function")throw new Error("Ứng dụng Desktop chưa tải được mô-đun cập nhật Excel. Hãy đóng ứng dụng và cài lại bản Desktop mới nhất.");const token=getAccessToken()||"";if(!token)throw new Error("Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.");const result=await window.ktcDesktop.syncAllExcel(token,date) as ExcelExportResult;if(result?.skipped)throw new Error(result.message||"Đang có một lần cập nhật Excel khác chạy. Yêu cầu đã được xếp hàng.");if(!result?.success){const failedFiles=Array.isArray(result?.files)?result.files.filter(file=>file?.success===false).map(file=>`${file.processName||file.processCode||"File Excel"}: ${file.error||"Không xác định được lỗi"}`):[];throw new Error(failedFiles.length>0?failedFiles.join("; "):result?.message||"Không thể cập nhật file Excel tháng.");}return result;}const response=await api.post("/reports/export-excel",{date},{responseType:"blob",timeout:180000});const contentDisposition=response.headers["content-disposition"] as string|undefined;const [year,month]=date.split("-");let fileName=`Bao-cao-san-xuat-${month}-${year}.xlsx`;if(contentDisposition){const utf8Match=contentDisposition.match(/filename\*=UTF-8''([^;]+)/i);const normalMatch=contentDisposition.match(/filename="?([^";]+)"?/i);const encodedName=utf8Match?.[1]||normalMatch?.[1];if(encodedName){try{fileName=decodeURIComponent(encodedName);}catch{fileName=encodedName;}}}const blob=response.data instanceof Blob?response.data:new Blob([response.data],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});const downloadUrl=window.URL.createObjectURL(blob);const link=document.createElement("a");try{link.href=downloadUrl;link.download=fileName;document.body.appendChild(link);link.click();}finally{link.remove();window.URL.revokeObjectURL(downloadUrl);}return{success:true,message:"Đã tải file Excel theo tháng."};};
export const getDeductionOptionsByProcess=async(processId:number):Promise<ProductionDeduction[]>=>{const res=await api.get(`/processes/${processId}/deductions`);return res.data.data||res.data||[];};
export const getDefectOptionsByProcess=async(processId:number):Promise<ProductionDefect[]>=>{const res=await api.get(`/processes/${processId}/defects`);return res.data.data||res.data||[];};
export type MonthlyExcelStatus={selectedDate:string;yearMonth:string;ready:boolean;fileName:string;size:number;reportCount:number;generatedAt:string|null;latestUpdatedAt:string|null;};
export const getMonthlyExcelStatus=async(date:string):Promise<MonthlyExcelStatus>=>{const response=await api.get("/reports/export-excel/status",{params:{date}});return response.data.data;};