export const TEST_CASES = [
  { id: 'SEC-001', name: 'Environment guard blocks production', type: 'safety' },
  { id: 'SYS-001', name: 'Frontend reachable', type: 'api' },
  { id: 'SYS-002', name: 'Production-temp API does not return 5xx', type: 'api' },
  { id: 'SYS-003', name: 'Notifications API does not return 5xx', type: 'api' },

  // Login is independent from worker/process fixtures.
  { id: 'LOGIN-001', name: 'Login page desktop renders', type: 'ui' },
  { id: 'LOGIN-002', name: 'Login rejects empty employee code', type: 'ui' },
  { id: 'LOGIN-003', name: 'Valid employee code opens role choice', type: 'ui' },
  { id: 'LOGIN-004', name: 'Back from role choice returns to employee code', type: 'ui' },
  { id: 'LOGIN-005', name: 'Management role opens password step', type: 'ui' },
  { id: 'LOGIN-006', name: 'Management login rejects empty password', type: 'ui' },
  { id: 'LOGIN-007', name: 'Password visibility toggle works', type: 'ui' },
  { id: 'LOGIN-008', name: 'Valid manager credentials login through FE', type: 'e2e' },
  { id: 'LOGIN-009', name: 'Login page mobile renders', type: 'ui' },
  { id: 'LOGIN-010', name: 'Login desktop has no browser console errors', type: 'ui' },
  { id: 'LOGIN-011', name: 'Login mobile has no browser console errors', type: 'ui' },

  // Authenticated worker/process tests.
  { id: 'MASTER-001', name: 'Cắt has CAT01-CAT04', type: 'api' },
  { id: 'MASTER-002', name: 'Lồng has LONG01-LONG05', type: 'api' },
  { id: 'WORKER-001', name: 'Create production report', type: 'business' },
  { id: 'WORKER-002', name: 'View report history', type: 'business' },
  { id: 'WORKER-003', name: 'Edit report within 10 minutes', type: 'business' },
  { id: 'RULE-001', name: 'Daily total <= 12 hours', type: 'business' },
  { id: 'RULE-002', name: 'Support/deduction excluded from daily production hours', type: 'business' },
  { id: 'MANAGER-001', name: 'Manager review/approve', type: 'business' },
  { id: 'PERM-001', name: 'Role authorization', type: 'security' },
  { id: 'EXPORT-001', name: 'Excel export', type: 'business' },

  // Visible worker browser E2E.
  { id: 'E2E-001', name: 'Manager login opens through FE', type: 'ui-e2e' },
  { id: 'E2E-002', name: 'Manager dashboard renders', type: 'ui-e2e' },
  { id: 'E2E-003', name: 'Worker login opens through FE', type: 'ui-e2e' },
  { id: 'E2E-004', name: 'Worker home/process UI renders', type: 'ui-e2e' },
  { id: 'E2E-005', name: 'Cắt mode selectable in FE', type: 'ui-e2e' },
  { id: 'E2E-006', name: 'Lồng mode selectable in FE', type: 'ui-e2e' },
  { id: 'E2E-007', name: 'Cắt shows only CAT defects', type: 'ui-e2e' },
  { id: 'E2E-008', name: 'Lồng shows only LONG defects', type: 'ui-e2e' },
  { id: 'E2E-009', name: 'Lồng defect labels include code before name', type: 'ui-e2e' },
  { id: 'E2E-010', name: 'Cắt defect labels include code before name', type: 'ui-e2e' },
  { id: 'E2E-011', name: 'Worker mobile layout opens', type: 'ui-e2e' },
  { id: 'E2E-012', name: 'Browser console stays clean during worker flow', type: 'ui-e2e' },
];
