export const TEST_CASES = [
  { id: 'SYS-001', name: 'Frontend reachable', type: 'api' },
  { id: 'SYS-002', name: 'Production-temp API does not return 5xx', type: 'api' },
  { id: 'SYS-003', name: 'Notifications API does not return 5xx', type: 'api' },
  { id: 'UI-001', name: 'Login page desktop', type: 'ui' },
  { id: 'UI-002', name: 'Login page mobile', type: 'ui' },
  { id: 'UI-003', name: 'Browser console desktop', type: 'ui' },
  { id: 'UI-004', name: 'Browser console mobile', type: 'ui' },
  { id: 'MASTER-001', name: 'Cắt has CAT01-CAT04', type: 'ui', status: 'SKIP', detail: 'Chưa có authenticated worker fixture.' },
  { id: 'MASTER-002', name: 'Lồng has LONG01-LONG05', type: 'ui', status: 'SKIP', detail: 'Chưa có authenticated worker fixture.' },
  { id: 'WORKER-001', name: 'Create production report', type: 'e2e', status: 'SKIP', detail: 'Chưa có test worker credentials/fixture.' },
  { id: 'WORKER-002', name: 'View report history', type: 'e2e', status: 'SKIP', detail: 'Chưa có test worker credentials/fixture.' },
  { id: 'WORKER-003', name: 'Edit report within 10 minutes', type: 'e2e', status: 'SKIP', detail: 'Chưa có test worker credentials/fixture.' },
  { id: 'RULE-001', name: 'Daily total <= 12 hours', type: 'business', status: 'SKIP', detail: 'Cần authenticated API fixture để tạo 2 reports.' },
  { id: 'RULE-002', name: 'Support/deduction excluded from daily production hours', type: 'business', status: 'SKIP', detail: 'Cần authenticated API fixture.' },
  { id: 'MANAGER-001', name: 'Manager review/approve', type: 'e2e', status: 'SKIP', detail: 'Chưa có test manager credentials/fixture.' },
  { id: 'PERM-001', name: 'Role authorization', type: 'api', status: 'SKIP', detail: 'Cần authenticated role fixtures.' },
  { id: 'EXPORT-001', name: 'Excel export', type: 'e2e', status: 'SKIP', detail: 'Cần authenticated manager fixture.' },
];
