import { useEffect, useMemo, useState } from "react";
import { useToast } from "../../components/feedback/toastContext";
import { getTempReportDetail } from "../../services/productionService";
import { getReportEditProposals, reviewReportEditProposal, type ReportEditProposal } from "../../services/reportEditProposalService";
import "./ReportEditProposals.css";

const num=(v:any)=>Number(v||0);
const mins=(v:any)=>Math.round(num(v)*60);
const normalize=(r:any)=>({work_date:String(r?.work_date||"").slice(0,10),shift:r?.shift||"",machine_no:r?.machine_no||"",product_name:r?.product_name||"",actual_time:num(r?.actual_time),tt_ok:num(r?.tt_ok),note:r?.note||"",deductions:(r?.deductions||[]).filter((x:any)=>num(x.hours)>0).map((x:any)=>({...x,hours:num(x.hours)})),defects:(r?.defects||[]).filter((x:any)=>num(x.quantity)>0).map((x:any)=>({...x,quantity:num(x.quantity)}))});
const key=(x:any,type:string)=>String(x?.[`${type}_type_id`]||x?.id||x?.[`${type}_name`]);

export default function ManagerReportEditProposals(){
 const {showToast}=useToast(); const [items,setItems]=useState<ReportEditProposal[]>([]); const [selected,setSelected]=useState<ReportEditProposal|null>(null); const [original,setOriginal]=useState<any>(null); const [draft,setDraft]=useState<any>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [rejectOpen,setRejectOpen]=useState(false); const [rejectReason,setRejectReason]=useState("");
 const load=async()=>{try{setLoading(true);setItems(await getReportEditProposals())}catch(e:any){showToast(e?.response?.data?.message||"Không thể tải đề xuất sửa","error")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const open=async(p:ReportEditProposal)=>{try{const r=await getTempReportDetail(p.report_id);setSelected(p);setOriginal(normalize(r));setDraft(normalize(p.proposed_data));setRejectOpen(false)}catch(e:any){showToast(e?.response?.data?.message||"Không thể tải báo cáo","error")}};
 const changed=useMemo(()=>JSON.stringify(original)!==JSON.stringify(draft),[original,draft]);
 const approve=async()=>{if(!selected)return;try{setBusy(true);await reviewReportEditProposal(selected.id,{decision:"approve",status_after:"approved",proposed_data:draft});showToast(changed?"Đã sửa theo nội dung cập nhật và duyệt báo cáo":"Đã duyệt theo đề xuất của tổ trưởng","success");setSelected(null);setDraft(null);setOriginal(null);await load()}catch(e:any){showToast(e?.response?.data?.message||"Không thể duyệt đề xuất","error")}finally{setBusy(false)}};
 const savePending=async()=>{if(!selected)return;try{setBusy(true);await reviewReportEditProposal(selected.id,{decision:"approve",status_after:"pending",proposed_data:draft});showToast(changed?"Đã cập nhật nội dung và chuyển báo cáo về chờ duyệt":"Đã áp dụng đề xuất, báo cáo đang chờ duyệt","success");setSelected(null);setDraft(null);setOriginal(null);await load()}catch(e:any){showToast(e?.response?.data?.message||"Không thể áp dụng đề xuất","error")}finally{setBusy(false)}};
 const reject=async()=>{if(!selected||rejectReason.trim().length<2){showToast("Vui lòng nhập lý do từ chối","error");return}try{setBusy(true);await reviewReportEditProposal(selected.id,{decision:"reject",reason:rejectReason});showToast("Đã từ chối đề xuất sửa","success");setSelected(null);setDraft(null);setOriginal(null);setRejectOpen(false);setRejectReason("");await load()}catch(e:any){showToast(e?.response?.data?.message||"Không thể từ chối đề xuất","error")}finally{setBusy(false)}};
 const set=(patch:any)=>setDraft((d:any)=>({...d,...patch}));
 const editList=(name:"defects"|"deductions",i:number,patch:any)=>setDraft((d:any)=>({...d,[name]:d[name].map((x:any,n:number)=>n===i?{...x,...patch}:x)}));
 return <div className="management-page report-proposals-page manager-proposals">
  <header className="proposal-page-head"><div><h1>Đề xuất sửa báo cáo</h1><p>Các đề xuất của tổ trưởng thuộc phạm vi công đoạn quản lý phụ trách.</p></div></header>
  <section className="proposal-workspace"><div className="proposal-list-card"><div className="proposal-card-head"><strong>Đề xuất chờ xử lý</strong><span>{items.filter(x=>x.status==='pending').length}</span></div>{loading?<div className="proposal-empty">Đang tải...</div>:items.filter(x=>x.status==='pending').length===0?<div className="proposal-empty">Không có đề xuất chờ xử lý.</div>:<div className="proposal-list">{items.filter(x=>x.status==='pending').map(p=><button type="button" className={`proposal-list-item ${selected?.id===p.id?'active':''}`} key={p.id} onClick={()=>void open(p)}><div><strong>Báo cáo #{p.report_id}</strong><span>{p.worker_name||p.worker_code||'---'} · {p.work_date||'---'} · Ca {p.shift||'-'}</span><small>Tổ trưởng: {p.proposer_name||p.proposer_username||'---'}</small></div><em>Chờ xử lý</em></button>)}</div>}</div>
  <div className="proposal-detail-card">{!selected?<div className="proposal-empty">Chọn một đề xuất để xem và xử lý.</div>:<><div className="proposal-detail-head"><div><h2>Đề xuất sửa #{selected.id}</h2><p>Báo cáo #{selected.report_id} · Tổ trưởng: {selected.proposer_name||selected.proposer_username||'---'}</p></div><button type="button" onClick={()=>setSelected(null)}>×</button></div>
   <div className="proposal-detail-body"><div className="proposal-compare-grid"><CompareCard title="Báo cáo hiện tại" data={original} changedAgainst={draft} old/><CompareCard title="Nội dung đề xuất / sau khi quản lý sửa" data={draft} changedAgainst={original}/></div>
   <section className="manager-edit-form"><div className="proposal-section-title"><div><h3>Chỉnh sửa trước khi duyệt</h3><p className="proposal-section-help">Nếu quản lý thay đổi bất kỳ trường nào, khi bấm <b>Duyệt</b> hệ thống sẽ hiểu là <b>sửa rồi duyệt</b>. Không thay đổi thì chỉ là duyệt đề xuất của tổ trưởng.</p></div></div>
    <div className="proposal-grid"><label>Ngày báo cáo<input type="date" value={draft.work_date} onChange={e=>set({work_date:e.target.value})}/></label><label>Ca<input value={draft.shift} onChange={e=>set({shift:e.target.value})}/></label><label>Máy<input value={draft.machine_no} onChange={e=>set({machine_no:e.target.value})}/></label><label>Sản phẩm<input value={draft.product_name} onChange={e=>set({product_name:e.target.value})}/></label><label>Giờ làm thực tế<input type="number" min="0" step="0.01" value={draft.actual_time} onChange={e=>set({actual_time:Math.max(0,num(e.target.value))})}/></label><label>Sản lượng OK<input type="number" min="0" value={draft.tt_ok} onChange={e=>set({tt_ok:Math.max(0,num(e.target.value))})}/></label></div>
    <h3>Thời gian trừ</h3>{(draft.deductions||[]).map((x:any,i:number)=><div className="proposal-row" key={key(x,'deduction')}><input value={x.deduction_name||x.deduction_code||''} readOnly/><input type="number" min="0" value={mins(x.hours)} onChange={e=>editList('deductions',i,{hours:Math.max(0,num(e.target.value))/60})}/><span>phút</span></div>)}
    <h3>Lỗi NG</h3>{(draft.defects||[]).map((x:any,i:number)=><div className="proposal-row" key={key(x,'defect')}><input value={x.defect_name||x.defect_code||''} readOnly/><input type="number" min="0" value={x.quantity} onChange={e=>editList('defects',i,{quantity:Math.max(0,num(e.target.value))})}/><span>sp</span></div>)}
    <label className="proposal-note">Ghi chú<textarea rows={3} value={draft.note||''} onChange={e=>set({note:e.target.value})}/></label>
   </section>
   {rejectOpen&&<section className="proposal-reject-box"><h3>Lý do từ chối</h3><textarea rows={3} value={rejectReason} onChange={e=>setRejectReason(e.target.value)} placeholder="Nhập lý do để tổ trưởng biết cần sửa gì..."/><div><button type="button" className="danger" onClick={()=>void reject()} disabled={busy}>Xác nhận từ chối</button><button type="button" onClick={()=>setRejectOpen(false)}>Hủy</button></div></section>}
   </div><footer className="proposal-actions manager-proposal-actions"><button type="button" onClick={()=>setSelected(null)}>Hủy</button><button type="button" className="danger" onClick={()=>setRejectOpen(true)} disabled={busy}>Từ chối</button><button type="button" onClick={()=>void savePending()} disabled={busy}>Lưu, chờ duyệt</button><button type="button" className="primary" onClick={()=>void approve()} disabled={busy}>Duyệt</button></footer></>}</div></section></div>
}

function CompareCard({title,data,changedAgainst,old}:{title:string;data:any;changedAgainst:any;old?:boolean}){const rows:any[]=[['Ngày báo cáo',data?.work_date,changedAgainst?.work_date],['Ca',data?.shift,changedAgainst?.shift],['Máy',data?.machine_no,changedAgainst?.machine_no],['Sản phẩm',data?.product_name,changedAgainst?.product_name],['Giờ làm thực tế',`${num(data?.actual_time)} giờ`,`${num(changedAgainst?.actual_time)} giờ`],['Sản lượng OK',num(data?.tt_ok),num(changedAgainst?.tt_ok)],['Ghi chú',data?.note||'---',changedAgainst?.note||'---']];return <div className={`proposal-compare-card ${old?'original':'proposed'}`}><div className="proposal-compare-card-head"><div><span>{old?'PHIÊN BẢN HIỆN TẠI':'PHIÊN BẢN SAU KHI SỬA'}</span><strong>{title}</strong></div></div><table className="proposal-compare-table"><thead><tr><th>Hạng mục</th><th>Giá trị</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td><strong>{r[0]}</strong></td><td className={String(r[1])!==String(r[2])?'changed-'+(old?'old':'new'):''}>{r[1]}</td></tr>)}</tbody></table></div>}
