import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, BarChart3, CalendarDays, CheckCircle2, ClipboardCheck, Clock3, FileText, Settings, Users, XCircle } from "lucide-react";
import { useNavigate } from "react-router-dom";
import api from "../../services/api";
import { useToast } from "../../components/feedback/toastContext";
import { getApiError } from "../../utils/apiError";
import { getStoredUser } from "../../utils/authStorage";
import "./Dashboard.css";

type PeriodKey = "today" | "yesterday" | "last7" | "thisMonth" | "lastMonth";
type ProcessOption={id:number;process_name:string;process_code?:string};
type ProcessSummary={process_id:number;process_name:string;process_code?:string;report_count:number;ok:number;ng:number};
type DashboardSummary={pending_count:number;approved_count:number;total_ok:number;total_ng:number;ng_rate:number;processes:ProcessOption[];process_summary:ProcessSummary[]};
type PendingReport={id:number;work_date?:string;worker_name?:string;worker_code?:string;process_name?:string;machine_no?:string;product_name?:string;tt_ok?:number;tt_ng?:number;actual_output?:number;actual_time?:number;status?:string};
const PERIOD_LABELS:Record<PeriodKey,string>={today:"Hôm nay",yesterday:"Hôm qua",last7:"7 ngày gần nhất",thisMonth:"Tháng này",lastMonth:"Tháng trước"};
const EMPTY:DashboardSummary={pending_count:0,approved_count:0,total_ok:0,total_ng:0,ng_rate:0,processes:[],process_summary:[]};
const fmt=(n:number)=>Number(n||0).toLocaleString("vi-VN",{maximumFractionDigits:1});
const pct=(n:number)=>`${Number(n||0).toLocaleString("vi-VN",{maximumFractionDigits:1})}%`;
function localDate(d:Date){const o=d.getTimezoneOffset();return new Date(d.getTime()-o*60000).toISOString().slice(0,10)}
function rangeFor(p:PeriodKey){const now=new Date(),s=new Date(now),e=new Date(now);if(p==="yesterday"){s.setDate(s.getDate()-1);e.setDate(e.getDate()-1)}else if(p==="last7")s.setDate(s.getDate()-6);else if(p==="thisMonth")s.setDate(1);else if(p==="lastMonth"){s.setMonth(s.getMonth()-1,1);e.setDate(0)}return{from:localDate(s),to:localDate(e)}}
function dateText(v?:string){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString("vi-VN",{day:"2-digit",month:"2-digit"})}
function timeText(v?:number){if(!v)return"—";return `${Math.floor(v/60).toString().padStart(2,"0")}:${Math.round(v%60).toString().padStart(2,"0")}`}

export default function Dashboard(){
 const navigate=useNavigate(),toast=useToast(),user=useMemo(()=>getStoredUser(),[]);const basePath=user?.role==="admin"?"/admin":user?.role==="lead"?"/lead":"/manager";const name=user?.full_name||user?.username||"Quản lý";
 const [period,setPeriod]=useState<PeriodKey>("today"),[summary,setSummary]=useState(EMPTY),[pending,setPending]=useState<PendingReport[]>([]),[loading,setLoading]=useState(true);
 useEffect(()=>{const controller=new AbortController(),range=rangeFor(period),key=`ktc:dashboard:${range.from}:${range.to}`;const load=async()=>{setLoading(true);try{const [dashRes,pendingRes]=await Promise.all([api.get("/dashboard/summary",{params:range,signal:controller.signal}),api.get("/production-temp/pending",{params:{date_from:range.from,date_to:range.to,page:1,page_size:5,include_meta:1},signal:controller.signal})]);const data={...EMPTY,...(dashRes.data?.data||{})};setSummary(data);const rows=Array.isArray(pendingRes.data?.data)?pendingRes.data.data:Array.isArray(pendingRes.data)?pendingRes.data:[];setPending(rows.slice(0,5));sessionStorage.setItem(key,JSON.stringify({savedAt:Date.now(),data}))}catch(e){if(!controller.signal.aborted)toast.showToast(getApiError(e,"Không thể tải dữ liệu tổng quan").message,"error")}finally{if(!controller.signal.aborted)setLoading(false)}};void load();return()=>controller.abort()},[period,toast]);
 const rows=useMemo(()=>{const map=new Map(summary.process_summary.map(r=>[Number(r.process_id),r]));return summary.processes.map(p=>{const r=map.get(Number(p.id));return{id:Number(p.id),name:p.process_name,ok:Number(r?.ok||0),ng:Number(r?.ng||0),reports:Number(r?.report_count||0)}}).filter(r=>r.ok+r.ng>0).sort((a,b)=>b.ok+b.ng-a.ok-a.ng)},[summary]);
 const total=summary.total_ok+summary.total_ng,max=Math.max(1,...rows.map(r=>r.ok+r.ng));const displayRows=rows.slice(0,6);const okRate=total?summary.total_ok/total*100:0;
 if(loading)return <main className="manager-dashboard dashboard-loading"><div className="dashboard-loading-heading"/><div className="dashboard-loading-kpis">{[1,2,3,4].map(i=><i key={i}/>)}</div><div className="dashboard-loading-body"/></main>;
 return <main className="manager-dashboard">
  <section className="dashboard-welcome"><div><h1>Chào bạn, {name}!</h1><p>Chúc bạn một ngày làm việc hiệu quả!</p><div className="dashboard-tags"><span>KTC-{user?.worker_code||user?.username||"—"}</span><span>Khu vực: A</span><span>Vai trò: {user?.role==="lead"?"Lead":user?.role==="manager"?"Manager":"Admin"}</span></div></div><div className="dashboard-motto">“ An toàn<br/>Chất lượng<br/>Hiệu quả<br/>Phát triển bền vững ”<b/></div></section>
  <section className="dashboard-kpi-grid"><article><span className="kpi-icon green"><Users/></span><b>{fmt(128)}</b><label>Công nhân</label><small>↑ 12% <em>so với hôm qua</em></small></article><article><span className="kpi-icon blue"><Clock3/></span><b>12.5</b><label>Giờ làm</label><small>↑ 0.5 <em>so với hôm qua</em></small></article><article><span className="kpi-icon purple"><FileText/></span><b>{fmt(summary.pending_count)}</b><label>Báo cáo chờ duyệt</label><small>↓ 3 <em>so với hôm qua</em></small></article><article><span className="kpi-icon blue"><Settings/></span><b>15</b><label>Máy đang hoạt động</label><small>↑ 2 <em>so với hôm qua</em></small></article></section>
  <section className="dashboard-chart-grid"><article className="dashboard-panel"><div className="dashboard-panel-title"><div><span>SẢN XUẤT</span><h2>Sản lượng theo công đoạn</h2></div><select value={period} onChange={e=>setPeriod(e.target.value as PeriodKey)}>{Object.entries(PERIOD_LABELS).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className="output-chart"><div className="output-axis"><span>{fmt(max)}</span><span>{fmt(max*.67)}</span><span>{fmt(max*.33)}</span><span>0</span></div><div className="output-bars">{displayRows.map(r=>{const v=r.ok+r.ng;return <div key={r.id}><strong>{fmt(v)}</strong><i style={{height:`${Math.max(4,v/max*100)}%`}}/><label title={r.name}>{r.name}</label></div>})}</div></div></article>
   <article className="dashboard-panel"><div className="dashboard-panel-title"><div><span>CHẤT LƯỢNG</span><h2>Tỷ lệ OK / NG theo công đoạn</h2></div><div className="chart-legend"><span><i/>OK</span><span><i/>NG</span></div></div><div className="quality-list">{displayRows.map(r=>{const t=r.ok+r.ng,ok=t?r.ok/t*100:0,ng=t?r.ng/t*100:0;return <div key={r.id}><label>{r.name}</label><section><b style={{width:`${ok}%`}}>{ok>12?pct(ok):""}</b><em style={{width:`${ng}%`}}>{ng>9?pct(ng):""}</em></section></div>})}</div></article>
  </section>
  <section className="dashboard-bottom-grid"><article className="dashboard-panel pending-table-panel"><div className="dashboard-panel-title"><div><span>CẦN XỬ LÝ</span><h2>Báo cáo cần xử lý</h2></div><button onClick={()=>navigate(`${basePath}/reports`)}>Xem tất cả <ArrowUpRight size={14}/></button></div><div className="pending-table-wrap"><table><thead><tr><th>#</th><th>Ngày</th><th>Công nhân</th><th>Công đoạn</th><th>Máy</th><th>Sản phẩm</th><th>Sản lượng</th><th>Thời gian</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{pending.length?pending.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{dateText(r.work_date)}</td><td>{r.worker_name||r.worker_code||"—"}</td><td>{r.process_name||"—"}</td><td>{r.machine_no||"—"}</td><td>{r.product_name||"—"}</td><td>{fmt(Number(r.actual_output??r.tt_ok??0)+Number(r.tt_ng||0))}</td><td>{timeText(Number(r.actual_time||0)*60)}</td><td><span className="pending-status">Chờ duyệt</span></td><td><button className="view-btn" onClick={()=>navigate(`${basePath}/reports`)}>Xem</button></td></tr>):<tr><td colSpan={10} className="table-empty">Không có báo cáo chờ duyệt</td></tr>}</tbody></table></div></article>
   <article className="dashboard-panel notifications-panel"><div className="dashboard-panel-title"><h2>Thông báo mới</h2><button onClick={()=>navigate(`${basePath}/notifications`)}>Xem tất cả <ArrowUpRight size={14}/></button></div><div className="notification-list"><div><span><ClipboardCheck/></span><p>Có <b>{fmt(summary.pending_count)}</b> báo cáo chờ duyệt</p><small>mới cập nhật</small></div><div><span><Settings/></span><p>Theo dõi máy móc và sản xuất</p><small>trong ngày hôm nay</small></div><div><span><FileText/></span><p>Hệ thống báo cáo sản xuất</p><small>đang hoạt động ổn định</small></div><div><span><BarChart3/></span><p>Dữ liệu theo công đoạn</p><small>đã được cập nhật</small></div></div></article>
  </section>
 </main>;
}
