import { useEffect, useState } from "react";
import axios from "axios";
import { createApprovedReportFromExcel, deleteReport, getApprovedReports, getReportById, invalidateManagerReportCaches, updateReport } from "../../services/productionService";
import { getCachedDefects, getCachedDeductions } from "../../services/masterDataCache";
import { normalizeDefectOptions, normalizeDeductionOptions, type WorkerMasterOption } from "../worker/processMasterDataNormalization";
import type { ProductionDeduction, ProductionDefect, ProductionReport } from "../../types/production";
import { useToast } from "../../components/feedback/toastContext";
import { getToday } from "./managerReportDateLogic";
import "./ManagerExcelReports.css";

type Preset = "today" | "yesterday" | "week" | "last-week" | "month" | "last-month" | "custom";
type ProcessTab = { label: string; processId: number; processCode: string };
const PROCESSES: ProcessTab[] = [
  { label: "CÁN", processId: 60002, processCode: "CAN" }, { label: "ÉP", processId: 60003, processCode: "EP" },
  { label: "XLBV", processId: 60004, processCode: "XLBV" }, { label: "Cắt lồng", processId: 1, processCode: "GC" },
  { label: "TT Mài", processId: 2, processCode: "MAI" }, { label: "TT Đo", processId: 60001, processCode: "DO" },
  { label: "TT Kiểm 1", processId: 3, processCode: "KIEM1" }, { label: "TT Kiểm 2", processId: 4, processCode: "KIEM2" },
];
const n=(v:unknown)=>Number(v||0),fmt=(v:unknown)=>n(v).toLocaleString("vi-VN",{maximumFractionDigits:2}),pct=(v:unknown)=>`${fmt(v)}%`,txt=(v:unknown)=>v===undefined||v===null||v===""?"—":String(v);
const dateFmt=(v?:string)=>{if(!v)return "—";const s=String(v).trim();if(/^\d{2}\/\d{2}\/\d{4}$/.test(s))return s;const m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[3]}/${m[2]}/${m[1]}`:"—"};
const dateInputValue=(v:unknown)=>{if(v===undefined||v===null||v==="")return "";const s=String(v).trim();if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;const m=s.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);if(m)return `${m[3]}-${m[2]}-${m[1]}`;const isoMatch=s.match(/^(\d{4})-(\d{2})-(\d{2})[T\s]/);if(isoMatch)return `${isoMatch[1]}-${isoMatch[2]}-${isoMatch[3]}`;return ""};
const parse=(v:string)=>{const [y,m,d]=v.split("-").map(Number);return new Date(y,(m||1)-1,d||1)},iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`,ms=(d:Date)=>new Date(d.getFullYear(),d.getMonth(),1),me=(d:Date)=>new Date(d.getFullYear(),d.getMonth()+1,0);
const ws=(d:Date)=>{const x=new Date(d),day=x.getDay();x.setDate(x.getDate()+(day===0?-6:1-day));return x},we=(d:Date)=>{const x=ws(d);x.setDate(x.getDate()+6);return x};
const initial=()=>{const d=parse(getToday());return{from:iso(ms(d)),to:iso(me(d))}};
function findDeduction(r:ProductionReport,o:WorkerMasterOption){return(r.deductions||[]).find(x=>(o.deduction_type_id&&x.deduction_type_id===o.deduction_type_id)||(o.deduction_code&&x.deduction_code===o.deduction_code)||x.deduction_name.trim().toUpperCase()===o.label.trim().toUpperCase())}
function findDefect(r:ProductionReport,o:WorkerMasterOption){return(r.defects||[]).find(x=>(o.defect_type_id&&x.defect_type_id===o.defect_type_id)||(o.defect_code&&x.defect_code===o.code)||x.defect_name.trim().toUpperCase()===o.label.trim().toUpperCase())}
function putDeduction(r:ProductionReport,o:WorkerMasterOption,v:number):ProductionDeduction[]{const a=[...(r.deductions||[])],i=a.findIndex(x=>(o.deduction_type_id&&x.deduction_type_id===o.deduction_type_id)||(o.deduction_code&&x.deduction_code===o.deduction_code)||x.deduction_name.trim().toUpperCase()===o.label.trim().toUpperCase()),x:ProductionDeduction={id:i>=0?a[i].id:undefined,deduction_type_id:o.deduction_type_id,deduction_code:o.deduction_code||o.code,deduction_name:o.label,hours:Math.max(0,v)};if(i>=0)a[i]=x;else if(v>0)a.push(x);return a}
function putDefect(r:ProductionReport,o:WorkerMasterOption,v:number):ProductionDefect[]{const a=[...(r.defects||[])],i=a.findIndex(x=>(o.defect_type_id&&x.defect_type_id===o.defect_type_id)||(o.defect_code&&x.defect_code===o.code)||x.defect_name.trim().toUpperCase()===o.label.trim().toUpperCase()),x:ProductionDefect={id:i>=0?a[i].id:undefined,defect_type_id:o.defect_type_id,defect_code:o.defect_code||o.code,defect_name:o.label,quantity:Math.max(0,Math.round(v))};if(i>=0)a[i]=x;else if(v>0)a.push(x);return a}
export default function ManagerReportGrid(){
 const{showToast}=useToast(),init=initial();
 const[process,setProcess]=useState<ProcessTab>(PROCESSES[0]),[from,setFrom]=useState(init.from),[to,setTo]=useState(init.to),[preset,setPreset]=useState<Preset>("month"),[search,setSearch]=useState(""),[page,setPage]=useState(1),[total,setTotal]=useState(0),[rows,setRows]=useState<ProductionReport[]>([]),[drafts,setDrafts]=useState<Record<number,ProductionReport>>({}),[editing,setEditing]=useState<number|null>(null),[selectedId,setSelectedId]=useState<number|null>(null),[dirty,setDirty]=useState(false),[unsavedPrompt,setUnsavedPrompt]=useState(false),[pendingAction,setPendingAction]=useState<(() => void)|null>(null),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[processId,setProcessId]=useState<number|null>(PROCESSES[0].processId),[deductions,setDeductions]=useState<WorkerMasterOption[]>([]),[defects,setDefects]=useState<WorkerMasterOption[]>([]);
 const pageSize=20;
 const apply=(p:Preset)=>{const d=parse(getToday());let a=d,b=d;if(p==="yesterday"){a=new Date(d);a.setDate(a.getDate()-1);b=new Date(a)}else if(p==="week"){a=ws(d);b=we(d)}else if(p==="last-week"){b=ws(d);b.setDate(b.getDate()-1);a=new Date(b);a.setDate(a.getDate()-6)}else if(p==="month"){a=ms(d);b=me(d)}else if(p==="last-month"){a=new Date(d.getFullYear(),d.getMonth()-1,1);b=new Date(d.getFullYear(),d.getMonth(),0)}else{setPreset("custom");return}setPreset(p);setFrom(iso(a));setTo(iso(b));setPage(1)};
 const load=async()=>{try{setLoading(true);const res=await getApprovedReports({dateFrom:from,dateTo:to,processId:process.processId,search:search.trim()||undefined,page,pageSize});const list=res.data||[];const full=await Promise.all(list.map(async x=>{try{return await getReportById(Number(x.id),"approved")}catch{return x}}));setRows(full);setTotal(Number(res.pagination?.total||full.length))}catch(e){showToast(axios.isAxiosError(e)?e.response?.data?.message||"Không thể tải báo cáo đã duyệt":"Không thể tải báo cáo đã duyệt");setRows([]);setTotal(0)}finally{setLoading(false)}};
 useEffect(()=>{void load()},[process,from,to,search,page]);
 useEffect(()=>{setPage(1);if(!dirty){setEditing(null);setSelectedId(null);setDrafts({});}setProcessId(process.processId)},[process,from,to,search]);
 useEffect(()=>{const before=(e:BeforeUnloadEvent)=>{if(!dirty)return;e.preventDefault();e.returnValue=""};addEventListener("beforeunload",before);return()=>removeEventListener("beforeunload",before)},[dirty]);
 useEffect(()=>{let alive=true;if(!processId){setDeductions([]);setDefects([]);return}Promise.all([getCachedDefects(processId),getCachedDeductions(processId)]).then(([a,b])=>{if(!alive)return;setDefects(normalizeDefectOptions(a,processId));setDeductions(normalizeDeductionOptions(b,processId))}).catch(()=>{if(alive){setDefects([]);setDeductions([])}});return()=>{alive=false}},[processId]);
 const row=(r:ProductionReport)=>drafts[Number(r.id)]||r,dsum=(r:ProductionReport)=>deductions.reduce((s,o)=>s+n(findDeduction(r,o)?.hours),0),ng=(r:ProductionReport)=>{const x=defects.reduce((s,o)=>s+n(findDefect(r,o)?.quantity),0);return x||n(r.tt_ng)},dm=(r:ProductionReport)=>n((r as any).standard_output??(r as any).target_output),tt=(r:ProductionReport)=>n(r.actual_output),ok=(r:ProductionReport)=>n(r.tt_ok),ttdm=(r:ProductionReport)=>n((r as any).tt_dinh_muc)||dm(r)*n(r.actual_time),ns=(r:ProductionReport)=>n((r as any).nang_suat_percent)||(ttdm(r)>0?tt(r)/ttdm(r)*100:0),dat=(r:ProductionReport)=>tt(r)>0?ok(r)/tt(r)*100:0,pp=(r:ProductionReport)=>n((r as any).pp_percent)||(tt(r)>0?ng(r)/tt(r)*100:0);
 const edit=(r:ProductionReport)=>{const id=Number(r.id);setSelectedId(id);setDrafts(p=>p[id]?p:{...p,[id]:{...r,deductions:[...(r.deductions||[])],defects:[...(r.defects||[])]}});setEditing(id);setDirty(false)};
 const selectRow=(r:ProductionReport)=>{const id=Number(r.id);if(editing===id)return;if(editing!==null&&dirty){setPendingAction(()=>()=>edit(r));setUnsavedPrompt(true);return}edit(r)};
 const field=(id:number,k:keyof ProductionReport,v:string|number)=>{setDirty(true);setDrafts(p=>({...p,[id]:{...p[id],[k]:v}}))};
 const save=async(r:ProductionReport)=>{const id=Number(r.id),d=drafts[id];if(!d)return;if(id<0){try{setSaving(true);await createApprovedReportFromExcel({...d,id:undefined,process_code:process.processCode,worker_code:String(d.worker_code||''),work_date:String(d.work_date||''),operation_mode:d.operation_mode||'MANUAL',operation_type:d.operation_type||undefined});showToast("Đã thêm báo cáo","success");setEditing(null);setSelectedId(null);setDirty(false);setDrafts({});invalidateManagerReportCaches();await load()}catch(e){showToast(axios.isAxiosError(e)?e.response?.data?.message||"Không thể thêm báo cáo":(e as Error).message||"Không thể thêm báo cáo")}finally{setSaving(false)}return}const totalHours=n(d.actual_time)+dsum(d);if(totalHours>12){showToast("Tổng giờ không được vượt quá 12 giờ");return}const payload:ProductionReport={...d,actual_time:n(d.actual_time),deduction_time:dsum(d),total_time:totalHours,actual_output:n(d.actual_output),tt_ok:n(d.tt_ok),tt_ng:ng(d),deductions:(d.deductions||[]).filter(x=>n(x.hours)>0),defects:(d.defects||[]).filter(x=>n(x.quantity)>0)};try{setSaving(true);await updateReport(id,payload,"approved",d.updated_at||null);showToast("Đã cập nhật báo cáo","success");setEditing(null);setSelectedId(null);setDirty(false);setDrafts(p=>{const x={...p};delete x[id];return x});invalidateManagerReportCaches();await load()}catch(e){showToast(axios.isAxiosError(e)?e.response?.data?.message||"Không thể cập nhật báo cáo":"Không thể cập nhật báo cáo")}finally{setSaving(false)}};
 const cancel=(id:number)=>{setEditing(null);setSelectedId(null);setDirty(false);setDrafts(p=>{const x={...p};delete x[id];return x})};
 const excelKey=(id:number)=>(e:React.KeyboardEvent<HTMLInputElement>)=>{if(e.key==='Escape'){e.preventDefault();cancel(id);return}if(e.key==='Enter'||(e.ctrlKey&&e.key.toLowerCase()==='s')){e.preventDefault();const r=rows.find(x=>Number(x.id)===id);if(r)void save(r)}};
 const toolbarAdd=()=>{if(editing!=null){showToast("Hãy lưu hoặc hủy dòng đang sửa trước");return}showToast("Chức năng thêm báo cáo đang giữ nguyên");};
 const toolbarCancel=()=>{if(editing!=null)cancel(editing)};const toolbarSave=async()=>{if(editing==null){showToast("Chưa có dòng đang sửa");return}const r=rows.find(x=>Number(x.id)===editing);if(r)await save(r)};
 const toolbarDelete=async()=>{if(selectedId==null){showToast("Hãy chọn một dòng trước khi Xóa");return}if(!confirm("Xóa báo cáo đã chọn?"))return;try{setSaving(true);await deleteReport(selectedId,"Quản lý xóa báo cáo đã duyệt");setEditing(null);setSelectedId(null);setDrafts(p=>{const x={...p};delete x[selectedId!];return x});setDirty(false);invalidateManagerReportCaches();showToast("Đã xóa báo cáo","success");await load()}catch(e){showToast(axios.isAxiosError(e)?e.response?.data?.message||"Không thể xóa báo cáo":"Không thể xóa báo cáo")}finally{setSaving(false)}};
 const requestLeave=(a:()=>void)=>{if(!dirty||saving){a();return}setPendingAction(()=>a);setUnsavedPrompt(true)};
 const input=(r:ProductionReport,k:keyof ProductionReport,type="text")=>{const id=Number(r.id),v=(row(r) as any)[k]??"";return <input className="manager-excel-input" type={type} value={type==="date"?dateInputValue(v):v} onChange={e=>field(id,k,type==="number"?Number(e.target.value):type==="date"?e.target.value:e.target.value)} onKeyDown={excelKey(id)} onClick={e=>e.stopPropagation()} />};
 const cell=(r:ProductionReport,content:React.ReactNode,editor?:React.ReactNode,cls="")=>{const active=editing===Number(r.id);return <td className={`manager-excel-cell ${active?"is-active":""} ${cls}`} onClick={()=>selectRow(r)}>{active&&editor?editor:content}</td>};
 return <div className="manager-report-grid" onClick={()=>{}}>
  <div className="manager-excel-toolbar"><button onClick={toolbarAdd}>＋ Thêm</button><button onClick={toolbarSave}>Lưu</button><button onClick={toolbarCancel}>Hủy</button><button onClick={toolbarDelete}>Xóa</button></div>
  <div className="manager-report-tabs">{PROCESSES.map(p=><button key={p.processId} className={process.processId===p.processId?"active":""} onClick={()=>requestLeave(()=>setProcess(p))}>{p.label}</button>)}</div>
  <div className="manager-report-filters"><select value={preset} onChange={e=>apply(e.target.value as Preset)}><option value="today">Hôm nay</option><option value="yesterday">Hôm qua</option><option value="week">Tuần này</option><option value="last-week">Tuần trước</option><option value="month">Tháng này</option><option value="last-month">Tháng trước</option><option value="custom">Tùy chọn</option></select><input type="date" value={from} onChange={e=>{setPreset("custom");setFrom(e.target.value)}}/><input type="date" value={to} onChange={e=>{setPreset("custom");setTo(e.target.value)}}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm kiếm"/><button onClick={()=>void load()}>↻ Làm mới</button></div>
  <div className="manager-excel-scroll"><table><thead><tr><th>Ngày</th><th>Mã CN</th><th>Họ tên</th><th className="shift-col">Ca</th><th>Máy</th><th>Sản phẩm</th><th>% HV</th><th>TT giờ</th><th>Trừ giờ</th>{deductions.map(o=><th key={`d-${o.deduction_type_id||o.code}`}>{o.label}</th>)}<th>Tổng giờ</th><th>Định mức/h</th><th>TT định mức</th><th>TT OK</th><th>NG</th>{defects.map(o=><th key={`f-${o.defect_type_id||o.code}`}>{o.label}</th>)}<th>% năng suất</th><th>% đạt</th><th>% PP</th><th>Ghi chú</th></tr></thead><tbody>{loading?<tr><td colSpan={30}>Đang tải...</td></tr>:rows.length===0?<tr><td colSpan={30}>Không có báo cáo đã duyệt của công đoạn này.</td></tr>:rows.map(r=>{const x=row(r);return <tr key={r.id} data-manager-row-id={r.id} className={selectedId===Number(r.id)?"is-row-selected":""}>{cell(r,dateFmt(x.work_date),input(r,"work_date","date"))}{cell(r,txt(x.worker_code),input(r,"worker_code"))}{cell(r,txt(x.worker_name),input(r,"worker_name"))}{cell(r,txt(x.shift),input(r,"shift"),"shift-col")}{cell(r,txt(x.machine_no),input(r,"machine_no"))}{cell(r,txt(x.product_name),input(r,"product_name"))}{cell(r,pct(x.hv_percent),input(r,"hv_percent","number"))}{cell(r,fmt(x.actual_time),input(r,"actual_time","number"))}<td className="manager-excel-cell">{fmt(x.deduction_time)}</td>{deductions.map(o=>{const d=findDeduction(x,o);return <td key={`dv-${o.deduction_type_id||o.code}`} className="manager-excel-cell" onClick={()=>selectRow(r)}>{editing===Number(r.id)?<input className="manager-excel-input" type="number" value={d?.hours??0} onChange={e=>{setDirty(true);setDrafts(p=>({...p,[Number(r.id)]:{...p[Number(r.id)],deductions:putDeduction(p[Number(r.id)],o,Number(e.target.value))}}))}} onKeyDown={excelKey(Number(r.id))} onClick={e=>e.stopPropagation()}/>:fmt(d?.hours)}</td>})}{cell(r,fmt(n(x.actual_time)+dsum(x)))}{cell(r,fmt(dm(x)),input(r,"standard_output","number"))}{cell(r,fmt(ttdm(x)))}{cell(r,fmt(ok(x)),input(r,"tt_ok","number"))}<td className="manager-excel-cell">{fmt(ng(x))}</td>{defects.map(o=>{const d=findDefect(x,o);return <td key={`fv-${o.defect_type_id||o.code}`} className="manager-excel-cell" onClick={()=>selectRow(r)}>{editing===Number(r.id)?<input className="manager-excel-input" type="number" value={d?.quantity??0} onChange={e=>{setDirty(true);setDrafts(p=>({...p,[Number(r.id)]:{...p[Number(r.id)],defects:putDefect(p[Number(r.id)],o,Number(e.target.value))}}))}} onKeyDown={excelKey(Number(r.id))} onClick={e=>e.stopPropagation()}/>:fmt(d?.quantity)}</td>})}{cell(r,pct(ns(x)))}{cell(r,pct(dat(x)))}{cell(r,pct(pp(x)))}{cell(r,txt(x.notes),input(r,"notes"))}</tr>})}</tbody></table></div>
  <div className="manager-excel-footer">{total} báo cáo đã duyệt · Tổng giờ = TT giờ + các loại Trừ giờ · Tổng giờ tối đa 12h</div>
  {unsavedPrompt&&<div className="manager-excel-unsaved-overlay"><div className="manager-excel-unsaved"><h3>Bạn có thay đổi chưa lưu</h3><p>Bạn có muốn lưu thay đổi trước khi chuyển sang thao tác khác?</p><button onClick={()=>{const a=pendingAction;setPendingAction(null);setUnsavedPrompt(false);if(editing!=null){const r=rows.find(x=>Number(x.id)===editing);if(r)void save(r).then(()=>a?.())}else a?.()}}>Lưu</button><button onClick={()=>{const a=pendingAction;setPendingAction(null);setUnsavedPrompt(false);if(editing!=null)cancel(editing);a?.()}}>Không lưu</button><button onClick={()=>{setUnsavedPrompt(false);setPendingAction(null)}}>Ở lại</button></div></div>}
 </div>;
}
