import { useEffect, useMemo, useState } from "react";
import axios from "axios";
import { getApprovedReports, getReportById, updateReport } from "../../services/productionService";
import { getCachedDefects, getCachedDeductions } from "../../services/masterDataCache";
import { normalizeDefectOptions, normalizeDeductionOptions, type WorkerMasterOption } from "../worker/processMasterDataNormalization";
import type { ProductionDeduction, ProductionDefect, ProductionReport } from "../../types/production";
import { useToast } from "../../components/feedback/toastContext";
import { getToday } from "./managerReportDateLogic";
import "./ManagerExcelReports.css";

type Preset = "today" | "yesterday" | "week" | "last-week" | "month" | "last-month" | "custom";
const PROCESSES = ["CÁN", "ÉP", "XLBV", "Cắt lồng", "TT Mài", "TT Đo", "TT Kiểm 1", "TT Kiểm 2"];
const n=(v:unknown)=>Number(v||0), fmt=(v:unknown)=>n(v).toLocaleString("vi-VN",{maximumFractionDigits:2}), pct=(v:unknown)=>`${fmt(v)}%`, txt=(v:unknown)=>v===undefined||v===null||v===""?"—":String(v);
const dateFmt=(v?:string)=>v?`${String(v).slice(8,10)}/${String(v).slice(5,7)}/${String(v).slice(0,4)}`:"—";
const parse=(v:string)=>{const [y,m,d]=v.split("-").map(Number);return new Date(y,(m||1)-1,d||1)};
const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const ms=(d:Date)=>new Date(d.getFullYear(),d.getMonth(),1), me=(d:Date)=>new Date(d.getFullYear(),d.getMonth()+1,0);
const ws=(d:Date)=>{const x=new Date(d),day=x.getDay();x.setDate(x.getDate()+(day===0?-6:1-day));return x}, we=(d:Date)=>{const x=ws(d);x.setDate(x.getDate()+6);return x};
const initial=()=>{const d=parse(getToday());return {from:iso(ms(d)),to:iso(me(d))}};

function findDeduction(r:ProductionReport,o:WorkerMasterOption){return (r.deductions||[]).find(x=>(o.deduction_type_id&&x.deduction_type_id===o.deduction_type_id)||(o.deduction_code&&x.deduction_code===o.deduction_code)||x.deduction_name.trim().toUpperCase()===o.label.trim().toUpperCase())}
function findDefect(r:ProductionReport,o:WorkerMasterOption){return (r.defects||[]).find(x=>(o.defect_type_id&&x.defect_type_id===o.defect_type_id)||(o.defect_code&&x.defect_code===o.defect_code)||x.defect_name.trim().toUpperCase()===o.label.trim().toUpperCase())}
function putDeduction(r:ProductionReport,o:WorkerMasterOption,v:number):ProductionDeduction[]{const a=[...(r.deductions||[])],i=a.findIndex(x=>(o.deduction_type_id&&x.deduction_type_id===o.deduction_type_id)||(o.deduction_code&&x.deduction_code===o.deduction_code)||x.deduction_name.trim().toUpperCase()===o.label.trim().toUpperCase());const x:ProductionDeduction={id:i>=0?a[i].id:undefined,deduction_type_id:o.deduction_type_id,deduction_code:o.deduction_code||o.code,deduction_name:o.label,hours:Math.max(0,v)};if(i>=0)a[i]=x;else if(v>0)a.push(x);return a}
function putDefect(r:ProductionReport,o:WorkerMasterOption,v:number):ProductionDefect[]{const a=[...(r.defects||[])],i=a.findIndex(x=>(o.defect_type_id&&x.defect_type_id===o.defect_type_id)||(o.defect_code&&x.defect_code===o.defect_code)||x.defect_name.trim().toUpperCase()===o.label.trim().toUpperCase());const x:ProductionDefect={id:i>=0?a[i].id:undefined,defect_type_id:o.defect_type_id,defect_code:o.defect_code||o.code,defect_name:o.label,quantity:Math.max(0,Math.round(v))};if(i>=0)a[i]=x;else if(v>0)a.push(x);return a}

export default function ManagerReportGrid(){
 const {showToast}=useToast(), init=initial();
 const [process,setProcess]=useState(PROCESSES[0]),[from,setFrom]=useState(init.from),[to,setTo]=useState(init.to),[preset,setPreset]=useState<Preset>("month"),[search,setSearch]=useState(""),[page,setPage]=useState(1),[total,setTotal]=useState(0),[rows,setRows]=useState<ProductionReport[]>([]),[drafts,setDrafts]=useState<Record<number,ProductionReport>>({}),[editing,setEditing]=useState<number|null>(null),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[processId,setProcessId]=useState<number|null>(null),[deductions,setDeductions]=useState<WorkerMasterOption[]>([]),[defects,setDefects]=useState<WorkerMasterOption[]>([]);
 const pageSize=20;
 const apply=(p:Preset)=>{const d=parse(getToday());let a=d,b=d;if(p==="yesterday"){a=new Date(d);a.setDate(a.getDate()-1);b=new Date(a)}else if(p==="week"){a=ws(d);b=we(d)}else if(p==="last-week"){b=ws(d);b.setDate(b.getDate()-1);a=new Date(b);a.setDate(a.getDate()-6)}else if(p==="month"){a=ms(d);b=me(d)}else if(p==="last-month"){a=new Date(d.getFullYear(),d.getMonth()-1,1);b=new Date(d.getFullYear(),d.getMonth(),0)}else{setPreset("custom");return}setPreset(p);setFrom(iso(a));setTo(iso(b));setPage(1)};
 const load=async()=>{try{setLoading(true);const res=await getApprovedReports({dateFrom:from,dateTo:to,processName:process,search:search.trim()||undefined,page,pageSize});const list=res.data||[];const full=await Promise.all(list.map(async x=>{try{return await getReportById(Number(x.id),"approved")}catch{return x}}));setRows(full);setTotal(Number(res.pagination?.total||full.length));setProcessId(Number(full[0]?.process_id||0)||null)}catch(e){showToast(axios.isAxiosError(e)?e.response?.data?.message||"Không thể tải báo cáo đã duyệt":"Không thể tải báo cáo đã duyệt");setRows([]);setTotal(0);setProcessId(null)}finally{setLoading(false)}};
 useEffect(()=>{void load()},[process,from,to,search,page]);useEffect(()=>{setPage(1);setEditing(null);setDrafts({})},[process,from,to,search]);
 useEffect(()=>{let alive=true;if(!processId){setDeductions([]);setDefects([]);return}Promise.all([getCachedDefects(processId),getCachedDeductions(processId)]).then(([a,b])=>{if(!alive)return;setDefects(normalizeDefectOptions(a,processId));setDeductions(normalizeDeductionOptions(b,processId))}).catch(()=>{if(alive){setDefects([]);setDeductions([])}});return()=>{alive=false}},[processId]);
 const row=(r:ProductionReport)=>drafts[Number(r.id)]||r;
 const dsum=(r:ProductionReport)=>deductions.reduce((s,o)=>s+n(findDeduction(r,o)?.hours),0);
 const ng=(r:ProductionReport)=>{const x=defects.reduce((s,o)=>s+n(findDefect(r,o)?.quantity),0);return x||n(r.tt_ng)};
 const dm=(r:ProductionReport)=>n((r as any).standard_output??(r as any).target_output), tt=(r:ProductionReport)=>n(r.actual_output), ok=(r:ProductionReport)=>n(r.tt_ok), ttdm=(r:ProductionReport)=>n((r as any).tt_dinh_muc)||dm(r)*n(r.actual_time), ns=(r:ProductionReport)=>n((r as any).nang_suat_percent)||(ttdm(r)>0?tt(r)/ttdm(r)*100:0), dat=(r:ProductionReport)=>tt(r)>0?ok(r)/tt(r)*100:0, pp=(r:ProductionReport)=>n((r as any).pp_percent)||(tt(r)>0?ng(r)/tt(r)*100:0);
 const edit=(r:ProductionReport)=>{const id=Number(r.id);setDrafts(p=>({...p,[id]:{...r,deductions:[...(r.deductions||[])],defects:[...(r.defects||[])]}}));setEditing(id)};
 const field=(id:number,k:keyof ProductionReport,v:string|number)=>setDrafts(p=>({...p,[id]:{...p[id],[k]:v}}));
 const save=async(r:ProductionReport)=>{const id=Number(r.id),d=drafts[id];if(!d)return;const totalHours=n(d.actual_time)+dsum(d);if(totalHours>12){showToast("Tổng giờ không được vượt quá 12 giờ");return}const payload:ProductionReport={...d,actual_time:n(d.actual_time),deduction_time:dsum(d),total_time:totalHours,actual_output:n(d.actual_output),tt_ok:n(d.tt_ok),tt_ng:ng(d),deductions:(d.deductions||[]).filter(x=>n(x.hours)>0),defects:(d.defects||[]).filter(x=>n(x.quantity)>0)};try{setSaving(true);await updateReport(id,payload,"approved",d.updated_at||null);showToast("Đã cập nhật báo cáo","success");setEditing(null);setDrafts(p=>{const x={...p};delete x[id];return x});await load()}catch(e){showToast(axios.isAxiosError(e)?e.response?.data?.message||"Không thể cập nhật báo cáo":"Không thể cập nhật báo cáo")}finally{setSaving(false)}};
 const cancel=(id:number)=>{setEditing(null);setDrafts(p=>{const x={...p};delete x[id];return x})};
 const input=(id:number,k:keyof ProductionReport,v:unknown,type="text")=><input className="manager-excel-cell-input" type={type} min={type==="number"?0:undefined} step={type==="number"?"0.01":undefined} value={v??""} onChange={e=>field(id,k,type==="number"?n(e.target.value):e.target.value)} onClick={e=>e.stopPropagation()}/>;
 const pages=Math.max(1,Math.ceil(total/pageSize));
 return <div className="manager-excel-page"><header className="manager-excel-head"><div><h1>Quản lý báo cáo</h1><p>Chỉ báo cáo đã duyệt · từng công đoạn · sửa trực tiếp như Excel, dùng Tab để chuyển ô.</p></div><button type="button" onClick={()=>void load()} disabled={loading}>↻ Làm mới</button></header>
 <div className="manager-excel-tabs">{PROCESSES.map(p=><button key={p} type="button" className={process===p?"active":""} onClick={()=>setProcess(p)}>{p}</button>)}</div>
 <section className="manager-excel-filters"><label>Khoảng thời gian<select value={preset} onChange={e=>apply(e.target.value as Preset)}><option value="today">Hôm nay</option><option value="yesterday">Hôm qua</option><option value="week">Tuần này</option><option value="last-week">Tuần trước</option><option value="month">Tháng này</option><option value="last-month">Tháng trước</option><option value="custom">Tùy chọn</option></select></label><label>Từ ngày<input type="date" value={from} onChange={e=>{setPreset("custom");setFrom(e.target.value)}}/></label><label>Đến ngày<input type="date" value={to} min={from} onChange={e=>{setPreset("custom");setTo(e.target.value)}}/></label><label className="search">Tìm kiếm<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Mã CN, họ tên, máy, sản phẩm..."/></label></section>
 <section className="manager-excel-table-card"><div className="manager-excel-table-wrap"><table className="manager-excel-table"><thead><tr><th className="sticky date">Ngày</th><th className="sticky code">Mã CN</th><th className="sticky name">Họ tên</th><th>Ca</th><th>Máy</th><th>Sản phẩm</th><th>% HV</th><th>TT giờ</th><th>Trừ giờ</th>{deductions.map(o=><th key={`d-${o.key}`}>{o.label}</th>)}<th>Tổng giờ</th><th>Định mức/h</th><th>TT định mức</th><th>TT</th><th>OK</th><th>NG</th><th>% năng suất</th><th>% đạt</th><th>% PP</th>{defects.map(o=><th key={`n-${o.key}`}>{o.label}</th>)}<th>Ghi chú</th><th>Trạng thái</th></tr></thead>
 <tbody>{loading?<tr><td colSpan={30+deductions.length+defects.length} className="empty">Đang tải...</td></tr>:!rows.length?<tr><td colSpan={30+deductions.length+defects.length} className="empty">Không có báo cáo đã duyệt của công đoạn này.</td></tr>:rows.map(original=>{const id=Number(original.id),r=row(original),is=editing===id,totalHours=n(r.actual_time)+dsum(r);return <tr key={id} className={is?"editing":""} onClick={()=>{if(!is)edit(original)}}>
 <td className="sticky date">{dateFmt(r.work_date)}</td><td className="sticky code">{txt(r.worker_code)}</td><td className="sticky name">{txt(r.full_name)}</td><td>{is?input(id,"shift",r.shift):txt(r.shift)}</td><td>{is?input(id,"machine_no",r.machine_no):txt(r.machine_no)}</td><td className="wide">{is?input(id,"product_name",r.product_name):txt(r.product_name)}</td><td>{pct(r.training_percent??(r as any).training_percent_snapshot)}</td>
 <td className="editable-cell">{is?input(id,"actual_time",r.actual_time,"number"):fmt(r.actual_time)}</td><td className="calculated-cell">{fmt(dsum(r))}</td>
 {deductions.map(o=><td key={`dv-${id}-${o.key}`} className="editable-cell">{is?<input className="manager-excel-cell-input" type="number" min="0" step="0.01" value={n(findDeduction(r,o)?.hours)} onChange={e=>setDrafts(p=>({...p,[id]:{...p[id],deductions:putDeduction(p[id],o,n(e.target.value))}}))} onClick={e=>e.stopPropagation()}/>:fmt(findDeduction(r,o)?.hours)}</td>)}
 <td className={`calculated-cell ${totalHours>12?"invalid-cell":""}`}>{fmt(totalHours)}</td><td className="calculated-cell">{fmt(dm(r))}</td><td className="calculated-cell">{fmt(ttdm(r))}</td><td className="editable-cell">{is?input(id,"actual_output",r.actual_output,"number"):fmt(tt(r))}</td><td className="editable-cell">{is?input(id,"tt_ok",r.tt_ok,"number"):fmt(ok(r))}</td><td className="calculated-cell">{fmt(ng(r))}</td><td className="calculated-cell">{pct(ns(r))}</td><td className="calculated-cell">{pct(dat(r))}</td><td className="calculated-cell">{pct(pp(r))}</td>
 {defects.map(o=><td key={`nv-${id}-${o.key}`} className="editable-cell">{is?<input className="manager-excel-cell-input" type="number" min="0" step="1" value={n(findDefect(r,o)?.quantity)} onChange={e=>setDrafts(p=>({...p,[id]:{...p[id],defects:putDefect(p[id],o,n(e.target.value))}}))} onClick={e=>e.stopPropagation()}/>:fmt(findDefect(r,o)?.quantity)}</td>)}
 <td className="wide">{is?input(id,"note",r.note):txt(r.note)}</td><td>{is?<><button type="button" disabled={saving} onClick={e=>{e.stopPropagation();void save(original)}}>Lưu</button><button type="button" disabled={saving} onClick={e=>{e.stopPropagation();cancel(id)}}>Hủy</button></>:<span className="approved-badge">Đã duyệt</span>}</td>
 </tr>})}</tbody></table></div><footer className="manager-excel-footer"><span>{total} báo cáo đã duyệt · Tổng giờ = TT giờ + các loại Trừ giờ · Tổng giờ tối đa 12h</span><div><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>‹</button><strong>{page} / {pages}</strong><button disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>›</button></div></footer></section></div>;
}
