import { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { getPendingReports } from "../../services/productionService";
import Reports from "./Reports";
import ApprovedReportsDesktopActions from "./ApprovedReportsDesktopActions";

const n=(v:unknown)=>{const x=Number(v);return Number.isFinite(x)?x:0};
const f=(v:unknown)=>n(v).toLocaleString("vi-VN",{maximumFractionDigits:2});
const p=(v:unknown)=>`${f(v)}%`;
const d=(v:unknown)=>{const s=String(v||"").slice(0,10),[y,m,day]=s.split("-");return y&&m&&day?`${day}/${m}/${y}`:s||"—"};
const dv=(v:Date)=>`${v.getFullYear()}-${String(v.getMonth()+1).padStart(2,"0")}-${String(v.getDate()).padStart(2,"0")}`;
const range=(value:string,type:"day"|"week"|"month"|"year")=>{const a=new Date(`${value}T00:00:00`),b=new Date(a);if(type==="year"){a.setMonth(0,1);b.setMonth(11,31)}else if(type==="month"){a.setDate(1);b.setMonth(b.getMonth()+1,0)}else if(type==="week"){const o=(a.getDay()+6)%7;a.setDate(a.getDate()-o);b.setTime(a.getTime());b.setDate(a.getDate()+6)}return{dateFrom:dv(a),dateTo:dv(b)}};
const code=(r:any,i=0)=>`PR${String(r.work_date||"REPORT").slice(0,10).replace(/-/g,"")}-${r.worker_code||String(r.id||i+1).padStart(4,"0")}`;
const kpi=(r:any)=>{const ok=n(r.tt_ok),ng=n(r.tt_ng),actual=n(r.actual_output)||ok+ng,standard=n(r.standard_output)||n(r.target_output),time=n(r.actual_time),tt=n(r.tt_dinh_muc)||(standard>0&&time>0?standard*time:0);return{ok,ng,hv:r.training_percent??r.hv_percent??r.learning_percent??r.hoc_viec_percent??0,prod:n(r.nang_suat_percent)||(tt>0?actual/tt*100:0),dat:actual>0?ok/actual*100:0,pp:n(r.pp_percent)||(actual>0?ng/actual*100:0),ngTypes:Math.max(n(r.ng_defect_type_count),n(r.worker_ng_type_count),n(r.machine_ng_type_count))}};

function installReportWorkspaceFix(navigate:(to:string)=>void){
 const id="ktc-manager-report-workspace-fix";
 if(!document.getElementById(id)){const s=document.createElement("style");s.id=id;s.textContent=`@media(min-width:801px){body.ktc-report-workspace-fix .management-sidebar{position:fixed!important;inset:72px 0 auto!important;width:100%!important;height:58px!important;min-height:58px!important;padding:0 18px!important;flex-direction:row!important;align-items:center!important;gap:14px!important;border-right:0!important;border-bottom:1px solid #dce8f5!important;box-shadow:0 3px 12px rgba(24,58,106,.05)!important}body.ktc-report-workspace-fix .management-brand{width:120px!important;flex:0 0 120px!important;height:48px!important;padding:2px 4px!important}body.ktc-report-workspace-fix .management-brand-logo{width:112px!important;max-height:42px!important}body.ktc-report-workspace-fix .management-menu{display:flex!important;flex:1 1 auto!important;min-width:0!important;margin-top:0!important;overflow-x:auto!important;overflow-y:hidden!important;gap:4px!important;padding:0!important}body.ktc-report-workspace-fix .management-menu button{width:auto!important;min-width:max-content!important;min-height:42px!important;height:42px!important;padding:0 13px!important;gap:7px!important;white-space:nowrap!important}body.ktc-report-workspace-fix .management-sidebar-footer{display:none!important}body.ktc-report-workspace-fix .management-main{margin-left:0!important}body.ktc-report-workspace-fix .management-content{padding-top:84px!important}body.ktc-report-workspace-fix .pending-reference-page{max-width:none!important}body.ktc-report-workspace-fix .pending-workspace{grid-template-columns:minmax(0,1fr) minmax(520px,43%)!important;align-items:start!important}body.ktc-report-workspace-fix .pending-reference-table{min-width:1500px!important}body.ktc-report-workspace-fix .pending-list-card .pending-reference-table th:nth-child(2),body.ktc-report-workspace-fix .pending-list-card .pending-reference-table td:nth-child(2){display:none!important}body.ktc-report-workspace-fix .pending-list-card .pending-reference-table th,body.ktc-report-workspace-fix .pending-list-card .pending-reference-table td{height:42px!important;padding:0 9px!important;font-size:11px!important}body.ktc-report-workspace-fix .pending-full-metric{text-align:center!important;font-weight:600!important}body.ktc-report-workspace-fix .pending-full-productivity{background:#ffd6e7!important;color:#9b123f!important;border:1px solid #ff9fbe!important}body.ktc-report-workspace-fix .pending-full-pp{background:#fff0b8!important;color:#795600!important;border:1px solid #e3ad20!important}}`;document.head.appendChild(s)}
 document.body.classList.add("ktc-report-workspace-fix");
 let timer:number|undefined,last="",cache:any[]=[],cachedAt=0;
 const filters=()=>{const ins=Array.from(document.querySelectorAll<HTMLInputElement>(".pending-filter-card input")),sels=Array.from(document.querySelectorAll<HTMLSelectElement>(".pending-filter-card select")),date=ins.find(x=>x.type==="date")?.value||dv(new Date()),search=ins.find(x=>x.type!=="date")?.value?.trim()||"",processName=sels[0]?.value||"",shift=sels[1]?.value||"",active=document.querySelector<HTMLButtonElement>(".pending-quick-filters button.active")?.textContent?.trim()||"Hôm nay",type=active==="Tuần này"?"week":active==="Tháng này"?"month":active==="Năm này"?"year":"day",r=range(date,type as any),page=Number(document.querySelector<HTMLButtonElement>(".pending-pagination button.active")?.textContent||1)||1;return{date,search,processName,shift,...r,page,pageSize:8}};
 const sync=async()=>{if(!window.location.hash.includes("#/manager/reports"))return;const table=document.querySelector<HTMLTableElement>(".pending-reference-table");if(!table)return;const rows=Array.from(table.querySelectorAll<HTMLTableRowElement>("tbody tr"));if(!rows.length||rows[0].querySelector(".management-empty,.management-error"))return;const q=filters(),sig=JSON.stringify(q);if(sig!==last||Date.now()-cachedAt>1500){try{const r=await getPendingReports({...q,processName:q.processName||undefined,shift:q.shift||undefined,search:q.search||undefined});cache=r.data||[];last=sig;cachedAt=Date.now()}catch{return}}const map=new Map(cache.map((r:any,i:number)=>[code(r,i),r]));const head=table.tHead?.rows[0];if(head&&!head.dataset.fullPending){const h=head.cells;if(h[6])h[6].textContent="Ngày báo cáo";if(h[7])h[7].textContent="Trạng thái";const th=document.createElement("th");th.textContent="Thời gian";h[7].before(th);["% HV","TT OK","NG","% năng suất","% đạt","% PP"].forEach(x=>{const c=document.createElement("th");c.textContent=x;c.className="pending-full-metric";h[h.length-1].before(c)});head.dataset.fullPending="1"}
 rows.forEach(row=>{if(row.dataset.fullPending)return;const cells=row.cells,r=map.get(cells[2]?.textContent?.trim()||"");if(!r)return;const x=kpi(r);cells[6].textContent=d(r.work_date);const tc=document.createElement("td");tc.textContent=`${f(r.actual_time||r.total_time)} giờ`;cells[7].before(tc);const vals:[[string,number],[string,number],[string,number],[string,number],[string,number],[string,number]]=[["hv",x.hv],["ok",x.ok],["ng",x.ng],["prod",x.prod],["dat",x.dat],["pp",x.pp]];vals.forEach(([type,v])=>{const c=document.createElement("td");c.textContent=["hv","prod","dat","pp"].includes(type)?p(v):f(v);c.className="pending-full-metric";if(type==="prod"&&(v<=75||v>100))c.classList.add("pending-full-productivity");if(type==="pp"&&(v===0||x.ngTypes===1))c.classList.add("pending-full-pp");cells[8].before(c)});row.dataset.fullPending="1"})};
 const schedule=()=>{window.clearTimeout(timer);timer=window.setTimeout(()=>void sync(),80)};const mo=new MutationObserver(schedule);mo.observe(document.body,{childList:true,subtree:true});schedule();
 const open=(row:HTMLTableRowElement)=>{const cells=Array.from(row.cells).map(c=>(c.innerText||"").replace(/\s+/g," ").trim()),m=(cells.find(v=>/\d{2}\/\d{2}\/\d{4}/.test(v))||"").match(/(\d{2})\/(\d{2})\/(\d{4})/),date=m?`${m[3]}-${m[2]}-${m[1]}`:"",worker=(cells[2]||"").match(/\(([^)]+)\)/)?.[1]||"",key=encodeURIComponent([date,worker,cells[3]||"",cells[4]||"",cells[1]||""].join("|"));navigate(`/manager/report/review?source=pending&date=${date}&key=${key}`)};
 const click=(e:MouseEvent)=>{const t=e.target as Element|null;if(!t||t.closest("input,select,textarea"))return;const row=t.closest<HTMLTableRowElement>(".pending-reference-table tbody tr");if(!row||row.querySelector(".management-empty,.management-error"))return;e.preventDefault();e.stopPropagation();open(row)};document.addEventListener("click",click,true);
 return()=>{mo.disconnect();window.clearTimeout(timer);document.removeEventListener("click",click,true);document.body.classList.remove("ktc-report-workspace-fix");document.getElementById(id)?.remove()};
}

export function ManagerReportsWorkspaceFix(){const navigate=useNavigate();useEffect(()=>installReportWorkspaceFix(navigate),[navigate]);return <Reports/>}
export function ManagerApprovedReportsWorkspaceFix(){const navigate=useNavigate();useEffect(()=>installReportWorkspaceFix(navigate),[navigate]);return <ApprovedReportsDesktopActions/>}
