import { useCallback, useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import { approveSelectedTempReports, getPendingReports, rejectSelectedTempReports } from "../../services/productionService";
import type { ProductionReport } from "../../types/production";
import { useToast } from "../../components/feedback/toastContext";
import { usePermissions } from "../../hooks/usePermissions";
import { getToday } from "./managerReportDateLogic";
import "./ReportsSplitReference.css";

const n=(v:unknown)=>{const x=Number(v);return Number.isFinite(x)?x:0;};
const f=(v:unknown)=>n(v).toLocaleString("vi-VN",{maximumFractionDigits:2});
const pct=(v:unknown)=>`${f(v)}%`;
const dateText=(v:unknown)=>{const s=String(v||"").slice(0,10);const [y,m,d]=s.split("-");return y&&m&&d?`${d}/${m}/${y}`:s||"—";};
const dateValue=(v:Date)=>`${v.getFullYear()}-${String(v.getMonth()+1).padStart(2,"0")}-${String(v.getDate()).padStart(2,"0")}`;
const rangeFor=(value:string,type:"day"|"week"|"month"|"year")=>{const start=new Date(`${value}T00:00:00`);const end=new Date(start);if(type==="year"){start.setMonth(0,1);end.setMonth(11,31);}else if(type==="month"){start.setDate(1);end.setMonth(end.getMonth()+1,0);}else if(type==="week"){const offset=(start.getDay()+6)%7;start.setDate(start.getDate()-offset);end.setTime(start.getTime());end.setDate(start.getDate()+6);}return{dateFrom:dateValue(start),dateTo:dateValue(end)};};

const kpi=(report:ProductionReport)=>{const x=report as ProductionReport&Record<string,unknown>;const ok=n(x.tt_ok);const ng=n(x.tt_ng);const actual=n(x.actual_output)||ok+ng;const standard=n(x.standard_output)||n(x.target_output);const actualTime=n(x.actual_time);const target=n(x.tt_dinh_muc)||(standard>0&&actualTime>0?standard*actualTime:0);const productivity=n(x.nang_suat_percent)||(target>0?actual/target*100:0);const achieved=actual>0?ok/actual*100:0;const pp=n(x.pp_percent)||(actual>0?ng/actual*100:0);const hv=x.training_percent_snapshot??x.training_percent??x.hv_percent??x.learning_percent??x.hoc_viec_percent??0;const ngTypes=Math.max(n(x.ng_defect_type_count),n(x.worker_ng_type_count),n(x.machine_ng_type_count));return{ok,ng,actual,productivity,achieved,pp,hv:n(hv),ngTypes};};
const metricStyle=(type:"productivity"|"pp",value:number,ngTypes=0)=>{if(type==="productivity"&&(value<=75||value>100))return{background:"#ffd6e7",color:"#9b123f",fontWeight:800,border:"1px solid #ff9fbe"};if(type==="pp"&&(value===0||ngTypes===1))return{background:"#fff0b8",color:"#795600",fontWeight:800,border:"1px solid #e3ad20"};return{};};
const reportCode=(r:ProductionReport,duplicate=false)=>{const x=r as ProductionReport&Record<string,unknown>;const explicit=x.report_code||x.reportCode||x.code;if(explicit)return String(explicit);const base=`PR${String(r.work_date||"REPORT").slice(0,10).replace(/-/g,"")}-${r.worker_code||String(r.id||"").padStart(4,"0")}`;return duplicate?`${base}-${r.id}`:base;};
const rowKey=(r:ProductionReport)=>[String(r.work_date||"").slice(0,10),String(r.worker_code||""),String(r.process_name||r.process_code||""),String(r.shift||""),n(r.actual_time).toFixed(4),n(r.tt_ok).toFixed(3),n(r.tt_ng).toFixed(3)].join("|");

export default function Reports(){
 const navigate=useNavigate();const{showToast}=useToast();const{can}=usePermissions();const canReview=can("REPORT_APPROVE");
 const[date,setDate]=useState(getToday());const[range,setRange]=useState<{dateFrom:string;dateTo:string}|null>(null);const[search,setSearch]=useState("");const[process,setProcess]=useState("");const[shift,setShift]=useState("");const[reports,setReports]=useState<ProductionReport[]>([]);const[selected,setSelected]=useState<number[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[page,setPage]=useState(1);const[pages,setPages]=useState(1);const[total,setTotal]=useState(0);const[counts,setCounts]=useState({day:0,week:0,month:0,year:0});const[actionLoading,setActionLoading]=useState(false);
 const load=useCallback(async()=>{try{setLoading(true);setError("");const active=range||{dateFrom:date,dateTo:date};const filters={dateFrom:active.dateFrom,dateTo:active.dateTo,processName:process||undefined,shift:shift||undefined,search:search.trim()||undefined};const result=await getPendingReports({...filters,page,pageSize:8});const data=result.data||[];setReports(data);setTotal(result.pagination?.total||0);setPages(Math.max(1,result.pagination?.total_pages||1));setSelected(current=>current.filter(id=>data.some(r=>Number(r.id)===id)));const types=["day","week","month","year"] as const;const values=await Promise.all(types.map(type=>{const r=rangeFor(date,type);return getPendingReports({...r,processName:process||undefined,shift:shift||undefined,search:search.trim()||undefined,page:1,pageSize:1);}));setCounts({day:values[0].pagination?.total||0,week:values[1].pagination?.total||0,month:values[2].pagination?.total||0,year:values[3].pagination?.total||0});}catch(e:unknown){setError(axios.isAxiosError(e)?e.response?.data?.message||"Không thể tải báo cáo chờ duyệt":"Không thể tải báo cáo chờ duyệt");setReports([]);setTotal(0);setPages(1);}finally{setLoading(false);}},[date,range,process,shift,search,page]);
 useEffect(()=>{void load();},[load]);useEffect(()=>{setPage(1);setSelected([]);},[date,range,process,shift,search]);
 const processes=useMemo(()=>Array.from(new Set(reports.map(r=>r.process_name).filter(Boolean) as string[])).sort(),[reports]);const shifts=useMemo(()=>Array.from(new Set(reports.map(r=>r.shift).filter(Boolean))).sort(),[reports]);
 const quick=(type:"day"|"week"|"month"|"year")=>{setDate(getToday());setRange(type==="day"?null:rangeFor(getToday(),type));};
 const toggle=(id:number)=>{if(!id)return;setSelected(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id]);};
 const targets=reports.filter(r=>selected.includes(Number(r.id))).map(r=>({id:Number(r.id),expected_updated_at:r.updated_at||null}));
 const approve=async()=>{if(!canReview||actionLoading||!targets.length)return;if(!window.confirm(`Duyệt ${targets.length} báo cáo đã chọn?`))return;setActionLoading(true);try{await approveSelectedTempReports(targets);showToast(`Đã duyệt ${targets.length} báo cáo`,"success");setSelected([]);await load();}catch(e:unknown){showToast(axios.isAxiosError(e)?e.response?.data?.message||"Không thể duyệt báo cáo":"Không thể duyệt báo cáo");}finally{setActionLoading(false);}};
 const reject=async()=>{if(!canReview||actionLoading||!selected.length)return;const reason=window.prompt("Lý do từ chối báo cáo:","Sai dữ liệu báo cáo")?.trim();if(!reason)return;setActionLoading(true);try{await rejectSelectedTempReports(selected,reason);showToast(`Đã từ chối ${selected.length} báo cáo`,"success");setSelected([]);await load();}catch(e:unknown){showToast(axios.isAxiosError(e)?e.response?.data?.message||"Không thể từ chối báo cáo":"Không thể từ chối báo cáo");}finally{setActionLoading(false);}};
 const openDetail=(report:ProductionReport)=>{if(!report.id)return;const dateValue=String(report.work_date||"").slice(0,10);const key=encodeURIComponent(rowKey(report));navigate(`/manager/report/review?source=pending&date=${dateValue}&key=${key}&id=${Number(report.id)}`);};
 const allSelected=reports.length>0&&reports.every(r=>selected.includes(Number(r.id)));
 return <div className="management-report-page manager-page pending-reference-page">
  <header className="pending-page-title"><div><h1>Báo cáo chờ duyệt</h1><p>Kiểm tra đầy đủ thông tin báo cáo trước khi duyệt hoặc từ chối.</p></div></header>
  <section className="pending-filter-card">
   <label className="pending-search"><span>Tìm kiếm</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm kiếm mã báo cáo, công nhân..."/></label>
   <label><span>Ngày báo cáo</span><input type="date" value={date} onChange={e=>{setDate(e.target.value);setRange(null);}}/></label>
   <label><span>Công đoạn</span><select value={process} onChange={e=>setProcess(e.target.value)}><option value="">Tất cả</option>{processes.map(p=><option key={p} value={p}>{p}</option>)}</select></label>
   <label><span>Ca làm việc</span><select value={shift} onChange={e=>setShift(e.target.value)}><option value="">Tất cả</option>{shifts.map(s=><option key={s} value={s}>{s}</option>)}</select></label>
   <div className="pending-quick-filters">{(["Hôm nay","Tuần này","Tháng này","Năm này"] as const).map(label=>{const type=label==="Hôm nay"?"day":label==="Tuần này"?"week":label==="Tháng này"?"month":"year";const activeRange=type==="day"?!range:Boolean(range&&range.dateFrom===rangeFor(date,type).dateFrom&&range.dateTo===rangeFor(date,type).dateTo);return <button key={label} type="button" className={activeRange?"active":""} onClick={()=>quick(type)}>{label}</button>;})}</div>
   <button type="button" className="pending-refresh" onClick={()=>void load()}>↻ <span>Làm mới</span></button>
  </section>
  <section className="pending-kpis">{[["Hôm nay",counts.day,"day"],["Tuần này",counts.week,"week"],["Tháng này",counts.month,"month"],["Năm này",counts.year,"year"]].map(([label,value,type])=><button key={String(label)} type="button" className="pending-kpi" onClick={()=>quick(type as "day"|"week"|"month"|"year")}><span>{label}</span><strong>{value}</strong><small>Báo cáo chờ duyệt · Bấm để xem</small></button>)}</section>
  {error&&<div className="management-error">{error}</div>}
  <section className="pending-workspace list-only"><div className="pending-list-card"><div className="pending-list-tabs"><button type="button" className="pending-list-tab active">Danh sách báo cáo <span className="tab-badge">{total}</span></button></div>
   {selected.length>0&&<div className="management-selected-info"><strong>Đã chọn {selected.length} báo cáo.</strong><div className="management-selected-actions"><button type="button" onClick={()=>setSelected([])}>Bỏ chọn</button>{canReview&&<><button type="button" className="selected-reject-action" onClick={()=>void reject()} disabled={actionLoading}>Từ chối</button><button type="button" className="selected-approve-action" onClick={()=>void approve()} disabled={actionLoading}>Duyệt</button></>}</div></div>}
   <div className="pending-table-wrap" style={{overflowX:"auto"}}><table className="pending-reference-table" style={{width:"100%",minWidth:1450,borderCollapse:"collapse",tableLayout:"fixed"}}><thead><tr>
    <th className="select-col" style={{width:44}}><input type="checkbox" checked={allSelected} onChange={()=>setSelected(allSelected?[]:reports.map(r=>Number(r.id)).filter(Boolean))}/></th><th>Mã báo cáo</th><th>Công nhân</th><th>Công đoạn</th><th>Ca</th><th>Ngày báo cáo</th><th>Thời gian</th><th>% HV</th><th>TT OK</th><th>NG</th><th>% năng suất</th><th>% đạt</th><th>% PP</th><th>Trạng thái</th>
   </tr></thead><tbody>{loading?<tr><td colSpan={14} className="management-empty" style={{padding:48,textAlign:"center"}}>Đang tải báo cáo...</td></tr>:reports.length===0?<tr><td colSpan={14} className="management-empty" style={{padding:48,textAlign:"center"}}>Không có báo cáo chờ duyệt.</td></tr>:reports.map((r,i)=>{const x=kpi(r);const code=reportCode(r);const duplicate=reports.filter(item=>reportCode(item)===code).length>1;const id=Number(r.id);return <tr key={id||i} data-report-id={id} onClick={()=>openDetail(r)} style={{cursor:"pointer"}}>
    <td className="select-col" onClick={e=>e.stopPropagation()}><input type="checkbox" checked={selected.includes(id)} disabled={!id||actionLoading} onChange={()=>toggle(id)}/></td><td className="report-code">{reportCode(r,duplicate)}</td><td>{String((r as any).full_name||(r as any).worker_name||"—")} <span style={{color:"#7185a4"}}>({String(r.worker_code||"—")})</span></td><td>{String(r.process_name||r.process_code||"—")}</td><td><span className="shift-chip">{String(r.shift||"—")}</span></td><td>{dateText(r.work_date)}</td><td>{f((r as any).actual_time||(r as any).total_time)} giờ</td><td>{pct(x.hv)}</td><td>{f(x.ok)}</td><td>{f(x.ng)}</td><td style={metricStyle("productivity",x.productivity,x.ngTypes)}>{pct(x.productivity)}</td><td>{pct(x.achieved)}</td><td style={metricStyle("pp",x.pp,x.ngTypes)}>{pct(x.pp)}{x.pp===0||x.ngTypes===1?" ⚠":""}</td><td><span className="status-pill status-orange">Chờ duyệt</span></td>
   </tr>;})}</tbody></table></div>
   <div className="pending-table-footer" style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10}}><span>Trang {page}/{pages} · {total} báo cáo</span><div style={{display:"flex",gap:6}}><button type="button" disabled={page<=1||loading} onClick={()=>setPage(p=>Math.max(1,p-1))}>Trước</button><button type="button" disabled={page>=pages||loading} onClick={()=>setPage(p=>Math.min(pages,p+1))}>Sau</button></div></div>
  </div></section>
 </div>;
}
