import { useEffect, useMemo, useState, type ReactNode } from "react";
import { BarChart3, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Clock3, Download, FileText, Filter, Gauge, HardDrive, XCircle } from "lucide-react";
import api from "../../services/api";
import { useToast } from "../../components/feedback/toastContext";
import "./Statistics.css";

type TabKey="day"|"process"|"shift"|"worker"|"machine";
type Summary={
 pending_count:number; approved_count:number; total_ok:number; total_ng:number; ng_rate:number;
 processes:{id:number;process_code?:string;process_name:string}[];
 process_summary:{process_id:number;process_code?:string;process_name:string;report_count:number;ok:number;ng:number}[];
 shift_summary:{shift:string;report_count:number;ok:number;ng:number}[];
 daily_summary:{work_date:string;report_count:number;ok:number;ng:number}[];
 worker_performance:{actual_worker_hours:number;earned_standard_hours:number;efficiency_percent:number};
 machine_performance:{machine_count:number;machine_line_count:number;total_machine_hours:number;maximum_output:number;counted_output:number;total_ok:number;total_ng:number;efficiency_percent:number};
 machine_summary:{machine_id:number;machine_code?:string;run_count:number;machine_hours:number;maximum_output:number;counted_output:number;ok:number;ng:number;efficiency_percent:number}[];
};
const EMPTY:Summary={pending_count:0,approved_count:0,total_ok:0,total_ng:0,ng_rate:0,processes:[],process_summary:[],shift_summary:[],daily_summary:[],worker_performance:{actual_worker_hours:0,earned_standard_hours:0,efficiency_percent:0},machine_performance:{machine_count:0,machine_line_count:0,total_machine_hours:0,maximum_output:0,counted_output:0,total_ok:0,total_ng:0,efficiency_percent:0},machine_summary:[]};
const pad=(v:number)=>String(v).padStart(2,"0");
const today=()=>{const d=new Date();return d.getFullYear()+"-"+pad(d.getMonth()+1)+"-"+pad(d.getDate());};
const monthStart=()=>{const d=new Date();return d.getFullYear()+"-"+pad(d.getMonth()+1)+"-01";};
const num=(v:number)=>Number(v||0).toLocaleString("vi-VN",{maximumFractionDigits:1});
const pct=(v:number)=>Number(v||0).toLocaleString("vi-VN",{minimumFractionDigits:2,maximumFractionDigits:2})+"%";
const totalOf=(r:{ok:number;ng:number})=>Number(r.ok||0)+Number(r.ng||0);
const rateOf=(r:{ok:number;ng:number})=>{const t=totalOf(r);return t?Number(r.ok||0)/t*100:0;};
const dateLabel=(v:string)=>{const parts=String(v).slice(0,10).split("-");return parts.length===3?parts[2]+"/"+parts[1]+"/"+parts[0]:v;};
const excel=(html:string,name:string)=>{const documentHtml="<html><head><meta charset=\"utf-8\"></head><body>"+html+"</body></html>";const blob=new Blob([documentHtml],{type:"application/vnd.ms-excel;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);};
const tableHtml=(rows:unknown[])=>{if(!rows.length)return "<p>Không có dữ liệu.</p>";return "<table border=\"1\"><tr><th>Dữ liệu</th></tr>"+rows.map(row=>"<tr><td>"+String((row as Record<string,unknown>).process_name||(row as Record<string,unknown>).work_date||(row as Record<string,unknown>).shift||(row as Record<string,unknown>).machine_code||"")+"</td></tr>").join("")+"</table>";};

export default function Statistics(){
 const toast=useToast();
 const [from,setFrom]=useState(monthStart()),[to,setTo]=useState(today());
 const [draftFrom,setDraftFrom]=useState(monthStart()),[draftTo,setDraftTo]=useState(today());
 const [period,setPeriod]=useState("custom"),[process,setProcess]=useState(""),[shift,setShift]=useState(""),[draftProcess,setDraftProcess]=useState(""),[draftShift,setDraftShift]=useState("");
 const [tab,setTab]=useState<TabKey>("day"),[summary,setSummary]=useState<Summary>(EMPTY),[loading,setLoading]=useState(true),[page,setPage]=useState(1);
 const load=async()=>{setLoading(true);try{const r=await api.get("/dashboard/summary",{params:{from,to}});setSummary({...EMPTY,...(r.data?.data||{})});}catch(e:any){toast.showToast(e?.response?.data?.message||"Không thể tải thống kê","error");setSummary(EMPTY);}finally{setLoading(false);}};
 useEffect(()=>{void load();},[from,to]);
 const processRows=useMemo(()=>summary.process_summary.filter(r=>!process||String(r.process_id)===process),[summary.process_summary,process]);
 const shiftRows=useMemo(()=>summary.shift_summary.filter(r=>!shift||r.shift===shift),[summary.shift_summary,shift]);
 const dayRows=useMemo(()=>summary.daily_summary.filter(r=>r.ok+r.ng>0).slice().reverse(),[summary.daily_summary]);
 const selectedProcess=process?summary.process_summary.find(r=>String(r.process_id)===process):null;
 const selectedShift=shift?summary.shift_summary.find(r=>r.shift===shift):null;
 const totals=selectedProcess?{ok:selectedProcess.ok,ng:selectedProcess.ng,reports:selectedProcess.report_count}:selectedShift?{ok:selectedShift.ok,ng:selectedShift.ng,reports:selectedShift.report_count}:{ok:summary.total_ok,ng:summary.total_ng,reports:summary.approved_count};
 const total=totals.ok+totals.ng;
 const apply=()=>{if(!draftFrom||!draftTo||draftFrom>draftTo){toast.showToast("Khoảng thời gian không hợp lệ","error");return;}setFrom(draftFrom);setTo(draftTo);setProcess(draftProcess);setShift(draftShift);setPage(1)};
 const quick=(value:string)=>{setPeriod(value);if(value==="custom")return;const d=new Date(),a=new Date(d),b=new Date(d);if(value==="7")a.setDate(d.getDate()-6);else if(value==="month")a.setDate(1);else if(value==="lastmonth"){a.setMonth(d.getMonth()-1,1);b.setDate(0);}const f=a.getFullYear()+"-"+pad(a.getMonth()+1)+"-"+pad(a.getDate()),t=b.getFullYear()+"-"+pad(b.getMonth()+1)+"-"+pad(b.getDate());setDraftFrom(f);setDraftTo(t);setFrom(f);setTo(t);setPage(1)};
 const exportCurrent=()=>{const title="KTC Production Statistics "+from+" - "+to;const rows=tab==="day"?dayRows:tab==="process"?processRows:tab==="shift"?shiftRows:tab==="machine"?summary.machine_summary:[];excel("<h2>"+title+"</h2>"+tableHtml(rows),"KTC_ThongKe_"+from+"_"+to+".xls");};
 const rowsPerPage=7,pageCount=Math.max(1,Math.ceil(dayRows.length/rowsPerPage)),pagedDays=dayRows.slice((page-1)*rowsPerPage,page*rowsPerPage);
 return <main className="statistics-page manager-page">
  <header className="statistics-title"><div><h1>Thống kê báo cáo</h1><p>Thống kê tổng hợp tình hình sản xuất theo thời gian và công đoạn</p></div></header>
  <section className="statistics-filter-card">
   <label><span>Khoảng thời gian</span><div className="statistics-period"><CalendarDays size={15}/><select value={period} onChange={e=>quick(e.target.value)}><option value="custom">Tùy chọn</option><option value="7">7 ngày gần nhất</option><option value="month">Tháng này</option><option value="lastmonth">Tháng trước</option></select></div></label>
   <label><span>Từ ngày</span><div className="statistics-date"><input type="date" value={draftFrom} onChange={e=>{setDraftFrom(e.target.value);setPeriod("custom")}}/><CalendarDays size={15}/></div></label>
   <label><span>Đến ngày</span><div className="statistics-date"><input type="date" value={draftTo} onChange={e=>{setDraftTo(e.target.value);setPeriod("custom")}}/><CalendarDays size={15}/></div></label>
   <label><span>Công đoạn</span><select value={draftProcess} onChange={e=>setDraftProcess(e.target.value)}><option value="">Tất cả</option>{summary.processes.map(p=><option key={p.id} value={p.id}>{p.process_name}</option>)}</select></label>
   <label><span>Ca làm việc</span><select value={draftShift} onChange={e=>setDraftShift(e.target.value)}><option value="">Tất cả</option>{summary.shift_summary.map(s=><option key={s.shift} value={s.shift}>{s.shift}</option>)}</select></label>
   <button className="statistics-filter-btn" onClick={apply}><Filter size={15}/> Lọc dữ liệu</button>
  </section>
  {loading?<section className="statistics-loading"><div/><div/><div/><div/><div/></section>:<>
   <section className="statistics-kpis"><Kpi icon={<FileText/>} label="Tổng số báo cáo" value={num(totals.reports)} note="Báo cáo" kind="blue"/><Kpi icon={<CheckCircle2/>} label="Tổng sản lượng OK" value={num(totals.ok)} note="Sản phẩm" kind="green"/><Kpi icon={<XCircle/>} label="Tổng sản lượng NG" value={num(totals.ng)} note="Sản phẩm" kind="red"/><Kpi icon={<BarChart3/>} label="Tỷ lệ OK trung bình" value={pct(total?totals.ok/total*100:0)} note="Tỷ lệ" kind="blue"/><Kpi icon={<Clock3/>} label="Tổng giờ làm" value={num(summary.worker_performance.actual_worker_hours)} note="Giờ" kind="orange"/></section>
   <section className="statistics-card statistics-tabs-card"><div className="statistics-tabs">{([["day","Theo ngày"],["process","Theo công đoạn"],["shift","Theo ca làm việc"],["worker","Theo công nhân"],["machine","Theo máy móc"]] as [TabKey,string][]).map(([k,t])=><button key={k} className={tab===k?"active":""} onClick={()=>{setTab(k);setPage(1)}}>{t}</button>)}</div>
    {tab==="day"&&<DailyTable rows={pagedDays}/>} {tab==="process"&&<ProcessTable rows={processRows}/>} {tab==="shift"&&<ShiftTable rows={shiftRows}/>} {tab==="worker"&&<WorkerTable summary={summary}/>} {tab==="machine"&&<MachineTable rows={summary.machine_summary}/>} 
    <footer className="statistics-footer"><span>{tab==="day"?"Hiển thị "+(dayRows.length?((page-1)*rowsPerPage+1):0)+" đến "+Math.min(page*rowsPerPage,dayRows.length)+" của "+dayRows.length+" ngày":"Dữ liệu trong khoảng "+dateLabel(from)+" - "+dateLabel(to)}</span><div className="statistics-footer-actions"><button className="export-btn" onClick={exportCurrent}><Download size={15}/> Xuất Excel</button>{tab==="day"&&<><button className="pager" disabled={page<=1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={15}/></button><button className="pager current">{page}</button><button className="pager" disabled={page>=pageCount} onClick={()=>setPage(p=>p+1)}><ChevronRight size={15}/></button></>}</div></footer>
   </section>
   <section className="statistics-bottom-grid"><article className="statistics-card stats-summary-card"><div className="stats-card-head"><div><span>CHẤT LƯỢNG</span><h2>Tổng quan chất lượng</h2></div></div><div className="stats-quality"><div className="stats-quality-donut" style={{background:`conic-gradient(#22a56b 0 ${total?totals.ok/total*100:0}%, #e84552 ${total?totals.ok/total*100:0}% 100%)`}}><strong>{pct(total?totals.ok/total*100:0)}</strong><small>OK</small></div><div className="stats-quality-list"><p><i className="green"/>OK <b>{num(totals.ok)}</b></p><p><i className="red"/>NG <b>{num(totals.ng)}</b></p><p><i className="blue"/>Tổng <b>{num(total)}</b></p></div></div></article><article className="statistics-card stats-summary-card"><div className="stats-card-head"><div><span>HIỆU SUẤT</span><h2>Hiệu suất máy móc</h2></div></div><div className="stats-metric-grid"><div><HardDrive/><b>{num(summary.machine_performance.machine_count)}</b><span>Máy hoạt động</span></div><div><Gauge/><b>{pct(summary.machine_performance.efficiency_percent)}</b><span>Hiệu suất máy</span></div><div><Clock3/><b>{num(summary.machine_performance.total_machine_hours)}</b><span>Giờ máy</span></div><div><BarChart3/><b>{num(summary.worker_performance.earned_standard_hours)}</b><span>Giờ chuẩn</span></div></div></article></section>
  </>}
 </main>;
}
function Kpi({icon,label,value,note,kind}:{icon:ReactNode;label:string;value:string;note:string;kind:string}){return <article className={`statistics-kpi ${kind}`}><div className="statistics-kpi-icon">{icon}</div><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function DailyTable({rows}:{rows:Summary["daily_summary"]}){return <TableWrap><table><thead><tr><th>Ngày</th><th>Số báo cáo</th><th>Sản lượng OK</th><th>Sản lượng NG</th><th>Tổng sản lượng</th><th>Tỷ lệ OK</th><th>Giờ làm</th><th>Người duyệt</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.work_date}><td className="date-link">{dateLabel(r.work_date)}</td><td>{num(r.report_count)}</td><td className="ok-cell">{num(r.ok)}</td><td className="ng-cell">{num(r.ng)}</td><td>{num(totalOf(r))}</td><td className="rate-cell">{pct(rateOf(r))}</td><td>—</td><td>—</td></tr>):<EmptyRow/>}</tbody>{rows.length>0&&<tfoot><tr><td>Tổng cộng</td><td>{num(rows.reduce((n,r)=>n+r.report_count,0))}</td><td>{num(rows.reduce((n,r)=>n+r.ok,0))}</td><td>{num(rows.reduce((n,r)=>n+r.ng,0))}</td><td>{num(rows.reduce((n,r)=>n+totalOf(r),0))}</td><td>{pct(rows.reduce((n,r)=>n+totalOf(r),0)?rows.reduce((n,r)=>n+r.ok,0)/rows.reduce((n,r)=>n+totalOf(r),0)*100:0)}</td><td>—</td><td>—</td></tr></tfoot>}</table></TableWrap>}
function ProcessTable({rows}:{rows:Summary["process_summary"]}){return <TableWrap><table><thead><tr><th>Công đoạn</th><th>Số báo cáo</th><th>Sản lượng OK</th><th>Sản lượng NG</th><th>Tổng sản lượng</th><th>Tỷ lệ OK</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.process_id}><td className="strong-cell">{r.process_name}</td><td>{num(r.report_count)}</td><td className="ok-cell">{num(r.ok)}</td><td className="ng-cell">{num(r.ng)}</td><td>{num(totalOf(r))}</td><td className="rate-cell">{pct(rateOf(r))}</td></tr>):<EmptyRow/>}</tbody></table></TableWrap>}
function ShiftTable({rows}:{rows:Summary["shift_summary"]}){return <TableWrap><table><thead><tr><th>Ca làm việc</th><th>Số báo cáo</th><th>Sản lượng OK</th><th>Sản lượng NG</th><th>Tổng sản lượng</th><th>Tỷ lệ OK</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.shift}><td className="strong-cell">{r.shift}</td><td>{num(r.report_count)}</td><td className="ok-cell">{num(r.ok)}</td><td className="ng-cell">{num(r.ng)}</td><td>{num(totalOf(r))}</td><td className="rate-cell">{pct(rateOf(r))}</td></tr>):<EmptyRow/>}</tbody></table></TableWrap>}
function WorkerTable({summary}:{summary:Summary}){return <div className="worker-stat-panel"><div className="worker-stat-hero"><span className="worker-stat-icon">👥</span><div><strong>Hiệu suất tổng hợp công nhân</strong><span>Tổng hợp theo kỳ đã chọn</span></div></div><div className="worker-stat-grid"><div><b>{num(summary.worker_performance.actual_worker_hours)}</b><span>Giờ công thực tế</span></div><div><b>{num(summary.worker_performance.earned_standard_hours)}</b><span>Giờ chuẩn đạt được</span></div><div><b>{pct(summary.worker_performance.efficiency_percent)}</b><span>Hiệu suất công nhân</span></div><div><b>{num(summary.approved_count)}</b><span>Báo cáo đã duyệt</span></div></div></div>}
function MachineTable({rows}:{rows:Summary["machine_summary"]}){return <TableWrap><table><thead><tr><th>Máy móc</th><th>Số lần chạy</th><th>Giờ máy</th><th>Sản lượng</th><th>OK</th><th>NG</th><th>Hiệu suất</th></tr></thead><tbody>{rows.length?rows.map(r=><tr key={r.machine_id}><td className="strong-cell">{r.machine_code||("Máy "+r.machine_id)}</td><td>{num(r.run_count)}</td><td>{num(r.machine_hours)}</td><td>{num(r.counted_output)}</td><td className="ok-cell">{num(r.ok)}</td><td className="ng-cell">{num(r.ng)}</td><td className="rate-cell">{pct(r.efficiency_percent)}</td></tr>):<EmptyRow/>}</tbody></table></TableWrap>}
function TableWrap({children}:{children:ReactNode}){return <div className="statistics-table-wrap">{children}</div>}
function EmptyRow(){return <tr><td colSpan={8} className="statistics-empty">Chưa có dữ liệu trong khoảng thời gian này</td></tr>}
