import { useEffect, useMemo, useState } from "react";
import { Pencil, Plus, Search, Trash2, Users, UserRound, X } from "lucide-react";
import api from "../../services/api";
import { useToast } from "../../components/feedback/toastContext";
import { usePermissions } from "../../hooks/usePermissions";
import "./Workers.css";

type Person={id:number;username:string;full_name:string;role:"manager"|"lead"|"worker";status:string;worker_code?:string|null;phone?:string|null;department?:string|null;position?:string|null;training_percent?:number;process_ids?:string|null;process_names?:string|null;created_at?:string};
type Process={id:number;process_name:string;process_code?:string};
type FormState={id?:number;role:"lead"|"worker";username:string;password:string;full_name:string;worker_code:string;phone:string;department:string;position:string;training_percent:string;process_ids:number[];status:"active"|"inactive"};
const emptyForm:FormState={role:"lead",username:"",password:"",full_name:"",worker_code:"",phone:"",department:"Sản xuất",position:"Tổ trưởng",training_percent:"100",process_ids:[],status:"active"};
const roleText=(r:string)=>r==="lead"?"Tổ trưởng":r==="worker"?"Công nhân":"Quản lý";
const statusText=(s:string)=>s==="active"?"Đang hoạt động":"Ngừng hoạt động";
const processIds=(v?:string|null)=>String(v||"").split(",").map(Number).filter(n=>Number.isInteger(n)&&n>0);

export default function Workers(){
 const {can}=usePermissions(); const {showToast}=useToast(); const canCreate=can("USER_CREATE"),canEdit=can("USER_EDIT");
 const [people,setPeople]=useState<Person[]>([]),[processes,setProcesses]=useState<Process[]>([]),[loading,setLoading]=useState(true),[tab,setTab]=useState("overview"),[keyword,setKeyword]=useState(""),[modal,setModal]=useState<FormState|null>(null),[saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);try{const [u,p]=await Promise.all([api.get("/users"),api.get("/users/options/processes")]);setPeople(u.data?.data||[]);setProcesses(p.data?.data||[]);}catch{showToast("Không thể tải dữ liệu nhân sự","error");}finally{setLoading(false);}};
 useEffect(()=>{void load();},[]);
 const leads=useMemo(()=>people.filter(p=>p.role==="lead"),[people]),workers=useMemo(()=>people.filter(p=>p.role==="worker"),[people]);
 const filter=(rows:Person[])=>rows.filter(p=>[p.username,p.full_name,p.worker_code,p.phone,p.process_names,p.department].join(" ").toLowerCase().includes(keyword.toLowerCase()));
 const assignments=useMemo(()=>processes.map(p=>({process:p,lead:leads.find(l=>processIds(l.process_ids).includes(p.id))})),[processes,leads]);
 const workerGroups=useMemo(()=>processes.map(p=>({process:p,workers:workers.filter(w=>processIds(w.process_ids).includes(p.id))})),[processes,workers]);
 const create=(role:"lead"|"worker")=>setModal({...emptyForm,role,position:role==="worker"?"Công nhân":"Tổ trưởng"});
 const edit=(p:Person)=>setModal({id:p.id,role:p.role==="lead"?"lead":"worker",username:p.username||"",password:"",full_name:p.full_name||"",worker_code:p.worker_code||"",phone:p.phone||"",department:p.department||"Sản xuất",position:p.position||roleText(p.role),training_percent:String(p.training_percent??100),process_ids:processIds(p.process_ids),status:p.status==="inactive"?"inactive":"active"});
 const save=async()=>{if(!modal)return;setSaving(true);try{const body:any={username:modal.username,full_name:modal.full_name,status:modal.status,process_ids:modal.process_ids};if(modal.password)body.password=modal.password;if(modal.role==="worker"){Object.assign(body,{worker_code:modal.worker_code,phone:modal.phone,department:modal.department,position:modal.position,training_percent:Number(modal.training_percent)});}if(modal.id)await api.put(`/users/${modal.id}`,body);else{body.role=modal.role;body.password=modal.password;await api.post("/users",body);}showToast(modal.id?"Đã cập nhật nhân sự":"Đã thêm nhân sự","success");setModal(null);await load();}catch(e:any){showToast(e?.response?.data?.message||"Không thể lưu nhân sự","error");}finally{setSaving(false);}};
 const remove=async(p:Person)=>{if(!canEdit)return;if(!window.confirm(`Xóa ${roleText(p.role)} ${p.full_name}? Tài khoản sẽ chuyển sang Ngừng hoạt động để bảo toàn lịch sử.`))return;try{await api.put(`/users/${p.id}`,{status:"inactive"});showToast("Đã xóa khỏi danh sách hoạt động","success");await load();}catch(e:any){showToast(e?.response?.data?.message||"Không thể xóa nhân sự","error");}};
 return <section className="personnel-page manager-page">
  <header className="personnel-header"><div><h1>Nhân sự</h1><p>Quản lý nhân sự trong hệ thống: quản lý, tổ trưởng và công nhân</p></div>{canCreate&&<button className="personnel-primary" onClick={()=>create("lead")}><Plus size={17}/> Thêm tổ trưởng</button>}</header>
  <nav className="personnel-tabs">{[["overview","Tổng quan"],["leads","Quản lý tổ trưởng"],["workers","Danh sách công nhân"],["assignment","Phân công công đoạn"],["activity","Lịch sử hoạt động"]].map(([k,t])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{t}</button>)}</nav>
  <div className="personnel-toolbar"><div className="personnel-search"><Search size={17}/><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="Tìm mã, tên, bộ phận..."/></div>{canCreate&&<button className="personnel-secondary" onClick={()=>create("worker")}><Plus size={16}/> Thêm công nhân</button>}</div>
  {loading?<div className="personnel-state">Đang tải dữ liệu nhân sự...</div>:<>
   {tab==="overview"&&<><section className="personnel-kpis"><div><Users/><span>Tài khoản quản lý</span><b>{people.filter(p=>p.role==="manager").length}</b><small>Quản lý</small></div><div><Users/><span>Tổ trưởng</span><b>{leads.filter(p=>p.status==="active").length} / 3</b><small>Đã tạo tối đa</small></div><div><UserRound/><span>Công nhân</span><b>{workers.filter(p=>p.status==="active").length}</b><small>Đang hoạt động</small></div><div><Users/><span>Công đoạn phụ trách</span><b>{processes.length}</b><small>Tổng số</small></div><article><strong>Quy định nhân sự</strong><p>✓ Mỗi tài khoản quản lý được tạo tối đa 3 tổ trưởng.</p><p>✓ Mỗi công đoạn chỉ được phân 1 tổ trưởng phụ trách.</p><p>✓ Tổ trưởng chỉ quản lý công nhân trong công đoạn được phân công.</p></article></section><div className="personnel-grid"><section className="personnel-card"><CardHead title={`Tổ trưởng của bạn (${leads.length}/3)`} sub="Danh sách tổ trưởng được tạo và quản lý"/><PersonTable rows={filter(leads)} canEdit={canEdit} onEdit={edit} onDelete={remove} role="lead"/></section><section className="personnel-card"><CardHead title="Phân công công đoạn cho tổ trưởng" sub="Mỗi công đoạn chỉ được phân 1 tổ trưởng phụ trách"/><AssignmentTable rows={assignments}/></section><section className="personnel-card"><CardHead title="Công nhân theo công đoạn" sub="Tổng số công nhân theo công đoạn"/><WorkerProcessTable rows={workerGroups}/></section><section className="personnel-card"><CardHead title="Hoạt động nhân sự gần đây" sub="Các tài khoản nhân sự mới tạo gần đây"/><Activity rows={people}/></section></div></>}
   {tab==="leads"&&<section className="personnel-card"><CardHead title="Quản lý tổ trưởng" sub="Thêm, sửa, xóa tổ trưởng"/><PersonTable rows={filter(leads)} canEdit={canEdit} onEdit={edit} onDelete={remove} role="lead"/></section>}
   {tab==="workers"&&<section className="personnel-card"><CardHead title={`Danh sách công nhân (${workers.length})`} sub="Quản lý thông tin tài khoản và phân công công đoạn"/><PersonTable rows={filter(workers)} canEdit={canEdit} onEdit={edit} onDelete={remove} role="worker"/></section>}
   {tab==="assignment"&&<section className="personnel-card"><CardHead title="Phân công công đoạn" sub="Kiểm soát tổ trưởng phụ trách từng công đoạn"/><AssignmentTable rows={assignments}/></section>}
   {tab==="activity"&&<section className="personnel-card"><CardHead title="Lịch sử hoạt động" sub="Các tài khoản nhân sự mới tạo gần đây"/><Activity rows={people}/></section>}
  </>}
  {modal&&<div className="personnel-modal-backdrop"><div className="personnel-modal"><div className="modal-head"><div><h2>{modal.id?"Sửa":"Thêm"} {roleText(modal.role)}</h2><p>Thông tin được lưu trực tiếp vào hệ thống.</p></div><button onClick={()=>setModal(null)}><X size={19}/></button></div><div className="modal-grid"><label>Họ và tên<input value={modal.full_name} onChange={e=>setModal({...modal,full_name:e.target.value})}/></label><label>Tên đăng nhập<input value={modal.username} onChange={e=>setModal({...modal,username:e.target.value})}/></label><label>Mật khẩu{modal.id&&<small> (để trống nếu không đổi)</small>}<input type="password" value={modal.password} onChange={e=>setModal({...modal,password:e.target.value})} placeholder="Tối thiểu 6 ký tự"/></label>{modal.role==="worker"&&<><label>Mã công nhân<input value={modal.worker_code} onChange={e=>setModal({...modal,worker_code:e.target.value})}/></label><label>Số điện thoại<input value={modal.phone} onChange={e=>setModal({...modal,phone:e.target.value})}/></label><label>Bộ phận<input value={modal.department} onChange={e=>setModal({...modal,department:e.target.value})}/></label><label>Vị trí<input value={modal.position} onChange={e=>setModal({...modal,position:e.target.value})}/></label><label>% học việc<input type="number" min="0" max="100" value={modal.training_percent} onChange={e=>setModal({...modal,training_percent:e.target.value})}/></label></>}<label>Trạng thái<select value={modal.status} onChange={e=>setModal({...modal,status:e.target.value as "active"|"inactive"})}><option value="active">Đang hoạt động</option><option value="inactive">Ngừng hoạt động</option></select></label><div className="modal-processes"><span>Công đoạn phụ trách</span><div>{processes.map(p=><label key={p.id}><input type="checkbox" checked={modal.process_ids.includes(p.id)} onChange={e=>setModal({...modal,process_ids:e.target.checked?[...modal.process_ids,p.id]:modal.process_ids.filter(id=>id!==p.id)})}/>{p.process_name}</label>)}</div></div></div><div className="modal-actions"><button onClick={()=>setModal(null)}>Hủy</button><button className="personnel-primary" disabled={saving} onClick={()=>void save()}>{saving?"Đang lưu...":"Lưu thay đổi"}</button></div></div></div>}
 </section>;
}
function CardHead({title,sub}:{title:string;sub:string}){return <div className="card-head"><div><h2>{title}</h2><p>{sub}</p></div></div>}
function PersonTable({rows,canEdit,onEdit,onDelete,role}:{rows:Person[];canEdit:boolean;onEdit:(p:Person)=>void;onDelete:(p:Person)=>void;role:"lead"|"worker"}){return <div className="personnel-table-wrap"><table className="personnel-table"><thead><tr><th>STT</th><th>{role==="lead"?"Tổ trưởng":"Công nhân"}</th><th>Mã</th><th>Công đoạn phụ trách</th><th>Số điện thoại</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{rows.length?rows.map((p,i)=><tr key={p.id}><td>{i+1}</td><td><strong>{p.full_name}</strong><small>{p.username}</small></td><td>{p.worker_code||`TT${String(i+1).padStart(3,"0")}`}</td><td>{p.process_names||"Chưa phân công"}</td><td>{p.phone||"---"}</td><td><span className={`person-status ${p.status}`}>{statusText(p.status)}</span></td><td><div className="row-actions">{canEdit&&<><button title="Sửa" onClick={()=>onEdit(p)}><Pencil size={15}/></button><button className="danger" title="Xóa" onClick={()=>onDelete(p)}><Trash2 size={15}/></button></>}</div></td></tr>):<tr><td colSpan={7} className="empty">Không có dữ liệu</td></tr>}</tbody></table></div>}
function AssignmentTable({rows}:{rows:{process:Process;lead?:Person}[]}){return <div className="personnel-table-wrap"><table className="personnel-table"><thead><tr><th>Công đoạn</th><th>Tổ trưởng phụ trách</th><th>Trạng thái</th></tr></thead><tbody>{rows.map(r=><tr key={r.process.id}><td><strong>{r.process.process_name}</strong></td><td>{r.lead?`${r.lead.full_name} (${r.lead.username})`:"Chưa phân công"}</td><td><span className={`person-status ${r.lead?"active":"pending"}`}>{r.lead?"Đã phân công":"Chưa phân công"}</span></td></tr>)}</tbody></table></div>}
function WorkerProcessTable({rows}:{rows:{process:Process;workers:Person[]}[]}){return <div className="personnel-table-wrap"><table className="personnel-table"><thead><tr><th>Công đoạn</th><th>Tổ trưởng phụ trách</th><th>Số công nhân</th><th>Nam</th><th>Nữ</th><th>Trạng thái</th></tr></thead><tbody>{rows.map(r=><tr key={r.process.id}><td>{r.process.process_name}</td><td>{r.workers[0]?.process_names||"Chưa phân công"}</td><td>{r.workers.length}</td><td>—</td><td>—</td><td><span className="person-status active">Đang hoạt động</span></td></tr>)}<tr className="total-row"><td>Tổng cộng</td><td>{rows.length} công đoạn</td><td>{rows.reduce((n,r)=>n+r.workers.length,0)}</td><td>—</td><td>—</td><td>—</td></tr></tbody></table></div>}
function Activity({rows}:{rows:Person[]}){return <div className="activity-list">{rows.slice(0,5).map((p,i)=><div key={p.id}><span className={`activity-dot d${i%3}`}>{i+1}</span><div><strong>{p.full_name}</strong><p>{roleText(p.role)} · {p.process_names||"Chưa phân công"}</p></div><time>{p.created_at?new Date(p.created_at).toLocaleString("vi-VN"):"Gần đây"}</time></div>)}</div>}
