import { useEffect, useMemo, useRef, useState } from "react";
import { Download, FileSpreadsheet, LogIn, LogOut, Pencil, Plus, Search, Trash2, Upload, Users, UserRound, X } from "lucide-react";
import api from "../../services/api";
import { getActivities, type ActivityItem } from "../../services/systemService";
import { useToast } from "../../components/feedback/toastContext";
import { usePermissions } from "../../hooks/usePermissions";
import "./Workers.css";

type Person={id:number;username:string;full_name:string;role:"manager"|"lead"|"worker";status:string;worker_code?:string|null;phone?:string|null;department?:string|null;position?:string|null;training_percent?:number;process_ids?:string|null;process_names?:string|null;created_at?:string};
type Process={id:number;process_name:string;process_code?:string};
type FormState={id?:number;role:"lead"|"worker";username:string;password:string;full_name:string;worker_code:string;phone:string;department:string;position:string;training_percent:string;process_ids:number[];status:"active"|"inactive"};
const emptyForm:FormState={role:"lead",username:"",password:"",full_name:"",worker_code:"",phone:"",department:"Sản xuất",position:"Tổ trưởng",training_percent:"100",process_ids:[],status:"active"};
const roleText=(r:string)=>r==="lead"?"Tổ trưởng":r==="worker"?"Công nhân":"Quản lý";
const statusText=(s:string)=>s==="active"?"Đang hoạt động":"Ngừng hoạt động";
const processIds=(v?:string|null)=>String(v||"").split(",").map(Number).filter(n=>Number.isInteger(n)&&n>0);
const activityAction=(action:string)=>String(action||"").toUpperCase()==="LOGOUT"?"Đăng xuất":"Đăng nhập";

export default function Workers(){
 const {can}=usePermissions(); const {showToast}=useToast(); const canCreate=can("USER_CREATE"),canEdit=can("USER_EDIT");
 const [people,setPeople]=useState<Person[]>([]),[processes,setProcesses]=useState<Process[]>([]),[activities,setActivities]=useState<ActivityItem[]>([]),[loading,setLoading]=useState(true),[activityLoading,setActivityLoading]=useState(false),[tab,setTab]=useState("overview"),[keyword,setKeyword]=useState(""),[modal,setModal]=useState<FormState|null>(null),[saving,setSaving]=useState(false);
 const [transferBusy,setTransferBusy]=useState(false),[transferMessage,setTransferMessage]=useState("");
 const fileInputRef=useRef<HTMLInputElement>(null);
 const load=async()=>{setLoading(true);try{const [u,p]=await Promise.all([api.get("/users"),api.get("/users/options/processes")]);setPeople(u.data?.data||[]);setProcesses(p.data?.data||[]);}catch{showToast("Không thể tải dữ liệu nhân sự","error");}finally{setLoading(false);}};
 const loadActivities=async()=>{setActivityLoading(true);try{const rows=await getActivities({limit:100});setActivities(rows.filter(row=>["LOGIN","LOGOUT"].includes(String(row.action||"").toUpperCase())));}catch{showToast("Không thể tải lịch sử đăng nhập/đăng xuất","error");}finally{setActivityLoading(false);}};
 useEffect(()=>{void load();},[]);
 useEffect(()=>{if(tab==="activity")void loadActivities();},[tab]);
 const leads=useMemo(()=>people.filter(p=>p.role==="lead"),[people]),workers=useMemo(()=>people.filter(p=>p.role==="worker"),[people]);
 const filter=(rows:Person[])=>rows.filter(p=>[p.username,p.full_name,p.worker_code,p.phone,p.process_names,p.department].join(" ").toLowerCase().includes(keyword.toLowerCase()));
 const workerGroups=useMemo(()=>processes.map(p=>({process:p,workers:workers.filter(w=>processIds(w.process_ids).includes(p.id))})),[processes,workers]);
 const create=(role:"lead"|"worker")=>setModal({...emptyForm,role,position:role==="worker"?"Công nhân":"Tổ trưởng"});
 const edit=(p:Person)=>setModal({id:p.id,role:p.role==="lead"?"lead":"worker",username:p.username||"",password:"",full_name:p.full_name||"",worker_code:p.worker_code||"",phone:p.phone||"",department:p.department||"Sản xuất",position:p.position||roleText(p.role),training_percent:String(p.training_percent??100),process_ids:processIds(p.process_ids),status:p.status==="inactive"?"inactive":"active"});
 const save=async()=>{if(!modal)return;setSaving(true);try{const body:any={username:modal.username,full_name:modal.full_name,status:modal.status,process_ids:modal.process_ids};if(modal.password)body.password=modal.password;if(modal.role==="worker"){Object.assign(body,{worker_code:modal.worker_code,phone:modal.phone,department:modal.department,position:modal.position,training_percent:Number(modal.training_percent)});}if(modal.id)await api.put(`/users/${modal.id}`,body);else{body.role=modal.role;body.password=modal.password;await api.post("/users",body);}showToast(modal.id?"Đã cập nhật nhân sự":"Đã thêm nhân sự","success");setModal(null);await load();}catch(e:any){showToast(e?.response?.data?.message||"Không thể lưu nhân sự","error");}finally{setSaving(false);}};
 const remove=async(p:Person)=>{if(!canEdit)return;if(!window.confirm(`Xóa ${roleText(p.role)} ${p.full_name}? Tài khoản sẽ chuyển sang Ngừng hoạt động để bảo toàn lịch sử.`))return;try{await api.put(`/users/${p.id}`,{status:"inactive"});showToast("Đã xóa khỏi danh sách hoạt động","success");await load();}catch(e:any){showToast(e?.response?.data?.message||"Không thể xóa nhân sự","error");}};
 const exportExcel=async()=>{setTransferBusy(true);setTransferMessage("");try{const response=await api.get("/users/export/excel",{responseType:"blob"});const blob=new Blob([response.data],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=`KTC_NhanSu_${new Date().toISOString().slice(0,10)}.xlsx`;document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url);setTransferMessage("Đã xuất dữ liệu nhân sự.");}catch(e:any){setTransferMessage(e?.response?.data?.message||"Không thể xuất Excel nhân sự.");}finally{setTransferBusy(false);}};
 const importExcel=()=>fileInputRef.current?.click();
 const handleImportFile=async(file:File|null)=>{if(!file)return;if(!/\.xlsx$/i.test(file.name)){setTransferMessage("Chỉ hỗ trợ file Excel .xlsx.");if(fileInputRef.current)fileInputRef.current.value="";return;}setTransferBusy(true);setTransferMessage("");try{const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result||""));reader.onerror=()=>reject(reader.error||new Error("Không đọc được file"));reader.readAsDataURL(file);});const response=await api.post("/users/import/excel",{file_base64:base64});setTransferMessage(response.data?.message||"Đã nhập Excel nhân sự.");await load();}catch(e:any){const data=e?.response?.data;setTransferMessage(data?.errors?.length?`${data.message||"File không hợp lệ"} ${data.errors.slice(0,2).join("; ")}`:(data?.message||"Không thể nhập Excel nhân sự."));}finally{setTransferBusy(false);if(fileInputRef.current)fileInputRef.current.value="";}};
 return <section className="personnel-page manager-page">
  <header className="personnel-header"><div><h1>Nhân sự</h1><p>Quản lý nhân sự trong hệ thống: quản lý, tổ trưởng và công nhân</p></div>{canCreate&&<div className="personnel-header-actions"><button className="personnel-primary" onClick={()=>create("lead")}><Plus size={17}/> Thêm tổ trưởng</button><button className="personnel-secondary" onClick={()=>create("worker")}><Plus size={16}/> Thêm công nhân</button></div>}</header>
  <nav className="personnel-tabs">{[["overview","Tổng quan"],["leads","Quản lý tổ trưởng"],["workers","Danh sách công nhân"],["activity","Lịch sử hoạt động"]].map(([k,t])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{t}</button>)}</nav>
  <div className="personnel-toolbar"><div className="personnel-search"><Search size={17}/><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="Tìm mã, tên, bộ phận..."/></div><div className="personnel-transfer-actions"><button type="button" className="personnel-secondary" disabled={transferBusy} onClick={()=>void exportExcel()}><Download size={15}/> Xuất Excel</button>{canCreate&&<button type="button" className="personnel-primary" disabled={transferBusy} onClick={importExcel}><Upload size={15}/> Nhập Excel</button>}<input ref={fileInputRef} type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" hidden onChange={e=>void handleImportFile(e.target.files?.[0]||null)}/></div></div>
  {transferMessage&&<div className={`personnel-transfer-message ${transferMessage.toLowerCase().includes("không")?"error":"success"}`}><FileSpreadsheet size={14}/><span>{transferMessage}</span></div>}
  {loading?<div className="personnel-state">Đang tải dữ liệu nhân sự...</div>:<>
   {tab==="overview"&&<><section className="personnel-kpis"><div><Users/><span>Tài khoản quản lý</span><b>{people.filter(p=>p.role==="manager").length}</b><small>Quản lý</small></div><div><Users/><span>Tổ trưởng</span><b>{leads.filter(p=>p.status==="active").length} / 3</b><small>Đã tạo tối đa</small></div><div><UserRound/><span>Công nhân</span><b>{workers.filter(p=>p.status==="active").length}</b><small>Đang hoạt động</small></div><div><Users/><span>Công đoạn phụ trách</span><b>{processes.length}</b><small>Tổng số</small></div><article><strong>Quy định nhân sự</strong><p>✓ Mỗi tài khoản quản lý được tạo tối đa 3 tổ trưởng.</p><p>✓ Tổ trưởng quản lý công nhân theo công đoạn được giao.</p><p>✓ Lịch sử đăng nhập/đăng xuất được lưu trong hệ thống.</p></article></section><div className="personnel-grid"><section className="personnel-card"><CardHead title={`Tổ trưởng của bạn (${leads.length}/3)`} sub="Danh sách tổ trưởng được tạo và quản lý"/><PersonTable rows={filter(leads)} canEdit={canEdit} onEdit={edit} onDelete={remove} role="lead"/></section><section className="personnel-card"><CardHead title="Công nhân theo công đoạn" sub="Tổng số công nhân theo công đoạn"/><WorkerProcessTable rows={workerGroups}/></section><section className="personnel-card personnel-grid-wide"><CardHead title="Lịch sử đăng nhập / đăng xuất gần đây" sub="Theo dõi các phiên đăng nhập của tài khoản nhân sự"/><Activity rows={activities.slice(0,5)}/></section></div></>}
   {tab==="leads"&&<section className="personnel-card"><CardHead title="Quản lý tổ trưởng" sub="Thêm, sửa, xóa tổ trưởng"/><PersonTable rows={filter(leads)} canEdit={canEdit} onEdit={edit} onDelete={remove} role="lead"/></section>}
   {tab==="workers"&&<section className="personnel-card"><CardHead title={`Danh sách công nhân (${workers.length})`} sub="Quản lý thông tin tài khoản, học việc và công đoạn phụ trách"/><PersonTable rows={filter(workers)} canEdit={canEdit} onEdit={edit} onDelete={remove} role="worker"/></section>}
   {tab==="activity"&&<section className="personnel-card"><CardHead title="Lịch sử đăng nhập / đăng xuất" sub="Nhật ký phiên đăng nhập của các tài khoản nhân sự"/>{activityLoading?<div className="personnel-state compact">Đang tải lịch sử...</div>:<Activity rows={activities}/>}</section>}
  </>}
  {modal&&<div className="personnel-modal-backdrop"><div className="personnel-modal"><div className="modal-head"><div><h2>{modal.id?"Sửa":"Thêm"} {roleText(modal.role)}</h2><p>Thông tin được lưu trực tiếp vào hệ thống.</p></div><button onClick={()=>setModal(null)}><X size={19}/></button></div><div className="modal-grid"><label>Họ và tên<input value={modal.full_name} onChange={e=>setModal({...modal,full_name:e.target.value})}/></label><label>Tên đăng nhập<input value={modal.username} onChange={e=>setModal({...modal,username:e.target.value})}/></label><label>Mật khẩu{modal.id&&<small> (để trống nếu không đổi)</small>}<input type="password" value={modal.password} onChange={e=>setModal({...modal,password:e.target.value})} placeholder="Tối thiểu 6 ký tự"/></label>{modal.role==="worker"&&<><label>Mã công nhân<input value={modal.worker_code} onChange={e=>setModal({...modal,worker_code:e.target.value})}/></label><label>Số điện thoại<input value={modal.phone} onChange={e=>setModal({...modal,phone:e.target.value})}/></label><label>Bộ phận<input value={modal.department} onChange={e=>setModal({...modal,department:e.target.value})}/></label><label>Vị trí<input value={modal.position} onChange={e=>setModal({...modal,position:e.target.value})}/></label><label>% học việc<input type="number" min="0" max="100" value={modal.training_percent} onChange={e=>setModal({...modal,training_percent:e.target.value})}/></label></>}<label>Trạng thái<select value={modal.status} onChange={e=>setModal({...modal,status:e.target.value as "active"|"inactive"})}><option value="active">Đang hoạt động</option><option value="inactive">Ngừng hoạt động</option></select></label><div className="modal-processes"><span>Công đoạn phụ trách</span><div>{processes.map(p=><label key={p.id}><input type="checkbox" checked={modal.process_ids.includes(p.id)} onChange={e=>setModal({...modal,process_ids:e.target.checked?[...modal.process_ids,p.id]:modal.process_ids.filter(id=>id!==p.id)})}/>{p.process_name}</label>)}</div></div></div><div className="modal-actions"><button onClick={()=>setModal(null)}>Hủy</button><button className="personnel-primary" disabled={saving} onClick={()=>void save()}>{saving?"Đang lưu...":"Lưu thay đổi"}</button></div></div></div>}
 </section>;
}
function CardHead({title,sub}:{title:string;sub:string}){return <div className="card-head"><div><h2>{title}</h2><p>{sub}</p></div></div>}
function PersonTable({rows,canEdit,onEdit,onDelete,role}:{rows:Person[];canEdit:boolean;onEdit:(p:Person)=>void;onDelete:(p:Person)=>void;role:"lead"|"worker"}){const worker=role==="worker";return <div className="personnel-table-wrap"><table className="personnel-table"><thead><tr><th>STT</th><th>{worker?"Công nhân":"Tổ trưởng"}</th><th>Mã</th><th>Công đoạn phụ trách</th>{worker&&<th>% học việc</th>}<th>Số điện thoại</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{rows.length?rows.map((p,i)=><tr key={p.id}><td>{i+1}</td><td><strong>{p.full_name}</strong><small>{p.username}</small></td><td>{p.worker_code||`TT${String(i+1).padStart(3,"0")}`}</td><td>{p.process_names||"Chưa phân công"}</td>{worker&&<td><span className={`training-pill ${Number(p.training_percent??100)>=100?"complete":"learning"}`}>{Number(p.training_percent??100)}%</span></td>}<td>{p.phone||"---"}</td><td><span className={`person-status ${p.status}`}>{statusText(p.status)}</span></td><td><div className="row-actions">{canEdit&&<><button title="Sửa" onClick={()=>onEdit(p)}><Pencil size={15}/></button><button className="danger" title="Xóa" onClick={()=>onDelete(p)}><Trash2 size={15}/></button></>}</div></td></tr>):<tr><td colSpan={worker?8:7} className="empty">Không có dữ liệu</td></tr>}</tbody></table></div>}
function WorkerProcessTable({rows}:{rows:{process:Process;workers:Person[]}[]}){return <div className="personnel-table-wrap"><table className="personnel-table"><thead><tr><th>Công đoạn</th><th>Số công nhân</th><th>Đang hoạt động</th><th>Trạng thái</th></tr></thead><tbody>{rows.map(r=><tr key={r.process.id}><td><strong>{r.process.process_name}</strong></td><td>{r.workers.length}</td><td>{r.workers.filter(w=>w.status==="active").length}</td><td><span className="person-status active">Đang theo dõi</span></td></tr>)}<tr className="total-row"><td>Tổng cộng</td><td>{rows.reduce((n,r)=>n+r.workers.length,0)}</td><td>{rows.reduce((n,r)=>n+r.workers.filter(w=>w.status==="active").length,0)}</td><td>—</td></tr></tbody></table></div>}
function Activity({rows}:{rows:ActivityItem[]}){return <div className="activity-list">{rows.length?rows.map((p,i)=>{const logout=String(p.action||"").toUpperCase()==="LOGOUT";return <div key={`${p.id}-${i}`}><span className={`activity-dot ${logout?"logout":"login"}`}>{logout?<LogOut size={13}/>:<LogIn size={13}/>}</span><div><strong>{p.full_name||p.username||"Tài khoản"}</strong><p>{activityAction(p.action)} · {roleText(p.role||"")}{p.ip_address?` · ${p.ip_address}`:""}</p></div><time>{p.created_at?new Date(p.created_at).toLocaleString("vi-VN"):"—"}</time></div>;}) : <div className="activity-empty">Chưa có lịch sử đăng nhập / đăng xuất</div>}</div>}
