'use strict';
const ExcelJS = require('exceljs');
const monthly = require('./monthlyWorkbookLocal.cjs');
const { canonicalDefect } = require('../../backend/utils/reportDetailNormalizer');

const GC = Object.freeze({ STT: 1, WORKER: 2, NAME: 3, DATE: 31, DED_TOTAL: 10, DED_FIRST: 11, DED_LAST: 26, OK: 33, NG: 34, DEF_FIRST: 36, DEF_LAST: 54 });
const FE_DEFECTS = [
  ['CAT01','Cao su không đứt'],['CAT02','Cắt lẹm'],['CAT03','Cắt phạm'],['CAT04','Cao su ngắn'],['CAT05','Cao su dài'],
  ['CAT06','Bavia cao su'],['CAT07','Phế phẩm chỉnh máy'],['CAT08','Lỗi cao su ( NCC )'],['CAT09','Lẫn cao su'],['CAT10','Khác'],
  ['LONG01','Không qua dưỡng'],['LONG02','Cao su vỡ'],['LONG03','Trục xước'],['LONG04','Trục gãy, cong'],['LONG05','Thiếu cao su'],
  ['LONG06','Lẫn trục'],['LONG07','Lẫn cao su'],['LONG08','Khác'],['XOAY','Cao su xoay']
];
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[đĐ]/g,'d').replace(/[^A-Za-z0-9]+/g,'_').replace(/^_+|_+$/g,'').toUpperCase();
const num=v=>{const n=Number(v);return Number.isFinite(n)?n:0};
const arr=(r,k)=>{for(const n of (k==='defect'?['defects','defectDetails','defect_details','defectRows','defect_rows']:['deductions','deductionDetails','deduction_details','deductionRows','deduction_rows']))if(Array.isArray(r?.[n]))return r[n];return[]};
const val=(x,k)=>num(k==='defect'?(x?.quantity??x?.defect_quantity??x?.ng_quantity??x?.qty??x?.count??x?.value):(x?.hours??x?.deduction_hours??x?.duration_hours??x?.time_hours??x?.value));
function detailKeys(x,k){return(k==='defect'?[x?.defect_type_id,x?.defect_type_code,x?.defect_code,x?.defect_type_name,x?.defect_name,x?.type_code,x?.type_name,x?.code,x?.name]:[x?.deduction_type_id,x?.deduction_type_code,x?.deduction_code,x?.deduction_type_name,x?.deduction_name,x?.type_code,x?.type_name,x?.code,x?.name]).filter(v=>v!=null&&String(v)!=='').map(norm)}
function canonicalCode(x){try{return canonicalDefect(x).defect_code}catch{return null}}
function types(data,k){const a=k==='defect'?data?.defectTypes:data?.deductionTypes;return(Array.isArray(a)?[...a]:[]).sort((a,b)=>(Number(a?.sort_order)||999999)-(Number(b?.sort_order)||999999)||Number(a?.id||0)-Number(b?.id||0))}
function matches(item,type,k){if(!type)return false;const id=k==='defect'?item?.defect_type_id:item?.deduction_type_id;if(id!=null&&type.id!=null&&String(id)===String(type.id))return true;const a=new Set(detailKeys(item,k));const b=(k==='defect'?[type.id,type.code,type.defect_code,type.defect_type_code,type.name,type.defect_name,type.defect_type_name]:[type.id,type.code,type.deduction_code,type.name,type.deduction_name]).filter(v=>v!=null&&String(v)!=='').map(norm);return b.some(x=>a.has(x))}
function reportRows(sheet){return[...(sheet._rows||[])].filter(r=>{const v=r?.getCell(GC.STT)?.value;return typeof v==='number'&&Number.isFinite(v)&&v>0}).sort((a,b)=>a.number-b.number)}
function date(v){if(v instanceof Date&&!Number.isNaN(v.getTime()))return v;const m=String(v??'').slice(0,10).match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?new Date(+m[1],+m[2]-1,+m[3]):null}
function setHeader(sheet,c,text){const x=sheet.getCell(3,c);x.value=text;x.alignment={...(x.alignment||{}),horizontal:'center',vertical:'middle',wrapText:true,shrinkToFit:false};x.font={...(x.font||{}),bold:true}}
function fix(wb,payload){const sheet=wb.getWorksheet('Cắt lồng')||wb.getWorksheet('CẮT LỒNG')||wb.worksheets[0];const data=payload?.processes?.GC;const reports=Array.isArray(data?.reports)?[...data.reports]:[];if(!sheet||!reports.length)return;reports.sort((a,b)=>String(a?.work_date||'').localeCompare(String(b?.work_date||''))||String(a?.approved_at||a?.created_at||'').localeCompare(String(b?.approved_at||b?.created_at||''))||Number(a?.id||0)-Number(b?.id||0));const ds=types(data,'deduction'),rows=reportRows(sheet);let i=0,last='',seq=0;for(const row of rows){if(i>=reports.length)break;const r=reports[i],d=String(r?.work_date||'').slice(0,10);if(d!==last){seq=0;const p1=sheet.getRow(row.number-1),p2=sheet.getRow(row.number-2),dr=p1?.getCell(1)?.value instanceof Date?p1:(p2?.getCell(1)?.value instanceof Date?p2:p1);if(dr){dr.getCell(1).value=date(d);dr.getCell(1).numFmt='d/m/yyyy';dr.height=Math.max(Number(dr.height||0),22)}last=d}seq++;row.getCell(GC.STT).value=seq;row.getCell(GC.WORKER).value=r?.worker_code??'';row.getCell(GC.NAME).value=r?.full_name??r?.worker_name??'';for(let j=0;j<ds.length&&GC.DED_FIRST+j<=GC.DED_LAST;j++)row.getCell(GC.DED_FIRST+j).value=arr(r,'deduction').filter(x=>matches(x,ds[j],'deduction')).reduce((s,x)=>s+val(x,'deduction'),0);for(let j=0;j<FE_DEFECTS.length;j++)row.getCell(GC.DEF_FIRST+j).value=arr(r,'defect').filter(x=>canonicalCode(x)===FE_DEFECTS[j][0]).reduce((s,x)=>s+val(x,'defect'),0);row.getCell(GC.DED_TOTAL).value=num(r?.deduction_time??r?.deduction_hours);row.getCell(GC.NG).value=num(r?.tt_ng??r?.ng_quantity??r?.ng);row.getCell(GC.DATE).value=date(r?.work_date);i++}for(let j=0;j<ds.length&&GC.DED_FIRST+j<=GC.DED_LAST;j++)setHeader(sheet,GC.DED_FIRST+j,String(ds[j]?.name||ds[j]?.deduction_name||ds[j]?.code||'Trừ giờ'));for(let j=0;j<FE_DEFECTS.length;j++)setHeader(sheet,GC.DEF_FIRST+j,FE_DEFECTS[j][1]);sheet.getRow(3).height=68;console.log('[KTC-EXCEL-V6] GC_DB_DETAIL_LAYOUT',JSON.stringify({reports:reports.length,mappedRows:i,deductionTypes:ds.length,defectTypes:FE_DEFECTS.length}))}
let active=null;const desc=Object.getOwnPropertyDescriptor(ExcelJS.Workbook.prototype,'xlsx');if(desc?.get&&!ExcelJS.Workbook.prototype.__ktcV6Installed){const getter=desc.get;Object.defineProperty(ExcelJS.Workbook.prototype,'xlsx',{configurable:desc.configurable,enumerable:desc.enumerable,get(){const x=getter.call(this);if(!x||x.__ktcV6Wrapped)return x;const write=x.writeBuffer?.bind(x);if(write)x.writeBuffer=async(...a)=>{if(active?.processes?.GC?.reports)fix(this,active);return write(...a)};Object.defineProperty(x,'__ktcV6Wrapped',{value:true});return x}});Object.defineProperty(ExcelJS.Workbook.prototype,'__ktcV6Installed',{value:true})}
const ob=monthly.buildProcessWorkbookLocal,os=monthly.buildSplitMonthlyWorkbooksLocal;if(typeof ob==='function')monthly.buildProcessWorkbookLocal=async a=>{const p=active;active=a?.payload||null;try{return await ob(a)}finally{active=p}};if(typeof os==='function')monthly.buildSplitMonthlyWorkbooksLocal=async a=>{const p=active;active=a?.payload||null;try{return await os(a)}finally{active=p}};module.exports=monthly;
