'use strict';
const ExcelJS=require('exceljs');
const Module=require('node:module');
const originalLoad=Module._load;
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').trim().toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim();
const text=v=>v==null?'':String(v).trim();
const number=v=>{const n=Number(v);return Number.isFinite(n)?n:null;};
const dateValue=v=>{if(!v||v instanceof Date)return v;const s=String(v).slice(0,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return v;const[y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d);};
function headers(sheet){const m=new Map();for(let c=1;c<=sheet.columnCount;c++){const h=norm(sheet.getCell(5,c).value);if(h)m.set(h,c);}return m;}
function put(sheet,hs,row,aliases,value,fmt){for(const a of aliases){const c=hs.get(norm(a));if(c){sheet.getCell(row,c).value=value;if(fmt)sheet.getCell(row,c).numFmt=fmt;return true;}}return false;}
function machine(r){const a=(Array.isArray(r?.machineLines)?r.machineLines:[]).map(x=>text(x?.machine_code??x?.machine_no??x?.machine_name)).filter(Boolean);return a.length?[...new Set(a)].join(', '):text(r?.machine_no??r?.machine_code??r?.machine);}
function product(r){const a=(Array.isArray(r?.machineLines)?r.machineLines:[]).map(x=>text(x?.product_code??x?.product_name)).filter(Boolean);return a.length?[...new Set(a)].join(', '):text(r?.product_code??r?.product_name??r?.product);}
function details(r,kind){const key=kind==='deduction'?'deductions':'defects';const idKey=kind==='deduction'?'deduction_type_id':'defect_type_id';const codeKey=kind==='deduction'?'deduction_type_code':'defect_type_code';const nameKey=kind==='deduction'?'deduction_type_name':'defect_type_name';const valueKey=kind==='deduction'?'hours':'quantity';const out=new Map();for(const x of Array.isArray(r?.[key])?r[key]:[]){const val=number(x?.[valueKey])??0;for(const k of [number(x?.[idKey])>0?`ID:${number(x[idKey])}`:'',norm(x?.[codeKey]??x?.code),norm(x?.[nameKey]??x?.name)].filter(Boolean))out.set(k,(out.get(k)||0)+val);}return out;}
function typeMap(pd,kind){const key=kind==='deduction'?'deductionTypes':'defectTypes';const codeKey=kind==='deduction'?'deduction_code':'defect_code';const nameKey=kind==='deduction'?'deduction_name':'defect_name';const out=new Map();for(const x of Array.isArray(pd?.[key])?pd[key]:[]){const id=number(x?.id);if(!(id>0))continue;for(const k of [norm(x?.[codeKey]??x?.code),norm(x?.[nameKey]??x?.name??x?.label)].filter(Boolean))out.set(k,`ID:${id}`);}return out;}
function rowsFor(sheet,hs,reports){const byId=new Map(reports.map(r=>[number(r?.id),r]));const idCol=hs.get('ID')||hs.get('MA BAO CAO')||hs.get('REPORT ID');const workerCol=hs.get('MA NV')||hs.get('MA CONG NHAN');const dateCol=hs.get('NGAY')||hs.get('NGAY LAM VIEC');const sttCol=hs.get('STT');const used=new Set();const out=[];for(let row=6;row<=sheet.rowCount;row++){let r=null;if(idCol){const id=number(sheet.getCell(row,idCol).value);if(id>0)r=byId.get(id)||null;}if(!r&&workerCol){const w=norm(sheet.getCell(row,workerCol).value);if(w){const ds=dateCol?String(sheet.getCell(row,dateCol).value??'').slice(0,10):'';r=reports.find(x=>!used.has(number(x?.id))&&norm(x?.worker_code)===w&&(!ds||String(x?.work_date??'').slice(0,10)===ds))||null;}}if(!r&&sttCol){const stt=number(sheet.getCell(row,sttCol).value);if(stt>0&&stt<=reports.length)r=reports[stt-1];}if(!r)continue;used.add(number(r?.id));out.push([row,r]);}return out;}
function patchSheet(sheet,pd,reports){if(!reports?.length||sheet.state!=='visible'||sheet.name.startsWith('_'))return;const hs=headers(sheet);if(!hs.size)return;const dmTypes=typeMap(pd,'deduction'),dfTypes=typeMap(pd,'defect');for(const[row,r]of rowsFor(sheet,hs,reports)){put(sheet,hs,row,['ID','Mã báo cáo','Report ID'],number(r.id));put(sheet,hs,row,['Ngày','Ngày làm việc'],dateValue(r.work_date),'dd/mm/yyyy');put(sheet,hs,row,['Mã NV','Mã công nhân'],text(r.worker_code));put(sheet,hs,row,['Tên NV','Tên công nhân','Họ tên'],text(r.full_name??r.worker_name??r.worker_full_name));put(sheet,hs,row,['Ca'],text(r.shift));put(sheet,hs,row,['Loại thao tác'],text(r.operation_type));put(sheet,hs,row,['Chế độ'],text(r.operation_mode));put(sheet,hs,row,['Máy','Mã máy'],machine(r));put(sheet,hs,row,['Mã SP','Mã sản phẩm','Sản phẩm'],product(r));put(sheet,hs,row,['% học việc','% Học việc'],number(r.training_percent));put(sheet,hs,row,['Định mức','Định mức/H'],number(r.standard_output??r.standard_output_per_hour));put(sheet,hs,row,['Tổng thời gian'],number(r.total_time));put(sheet,hs,row,['Thời gian chạy thực tế','Thời gian thực tế'],number(r.actual_time));put(sheet,hs,row,['Tổng thời gian trừ','Thời gian trừ'],number(r.deduction_time));put(sheet,hs,row,['OK','SL OK','Sản lượng OK'],number(r.tt_ok??r.ok_quantity));put(sheet,hs,row,['NG','SL NG','Tổng NG'],number(r.tt_ng??r.total_ng??r.ng_quantity));put(sheet,hs,row,['SP công nhân nhập','Sản lượng thực tế','Sản lượng','Output'],number(r.actual_output));const ds=details(r,'deduction'),fs=details(r,'defect');for(const[h,c]of hs){const dk=dmTypes.get(h);if(dk)sheet.getCell(row,c).value=ds.get(dk)??0;const fk=dfTypes.get(h);if(fk)sheet.getCell(row,c).value=fs.get(fk)??0;}}}
async function patchWorkbook(buffer,payload,code){if(!buffer||payload?.dataSource!=='tidb.production_reports.approved')return buffer;const wb=new ExcelJS.Workbook();await wb.xlsx.load(buffer);const pd=code?payload?.processes?.[code]:null;if(pd?.reports){for(const s of wb.worksheets)patchSheet(s,pd,pd.reports);}else{for(const[dataCode,data]of Object.entries(payload?.processes||{})){if(!data?.reports)continue;for(const s of wb.worksheets){const sn=norm(s.name),cn=norm(dataCode);if(sn===cn||sn.includes(cn)||cn.includes(sn))patchSheet(s,data,data.reports);}}}return Buffer.from(await wb.xlsx.writeBuffer());}
function patchModule(mod){if(!mod||mod.__ktcDbTruthExcelPatched)return mod;for(const name of ['buildSplitMonthlyWorkbooksLocal','buildProcessWorkbookLocal']){const fn=mod[name];if(typeof fn!=='function')continue;mod[name]=async(args={})=>{const result=await fn(args);if(Array.isArray(result?.processes)){for(const item of result.processes)if(item?.buffer)item.buffer=await patchWorkbook(item.buffer,args.payload,item.processCode);}else if(result?.buffer)result.buffer=await patchWorkbook(result.buffer,args.payload,args.processCode);return result;};}Object.defineProperty(mod,'__ktcDbTruthExcelPatched',{value:true});return mod;}
Module._load=function(request,parent,isMain){const loaded=originalLoad.call(this,request,parent,isMain);if(typeof request==='string'&&/monthlyWorkbookLocal\.cjs$/.test(request))return patchModule(loaded);return loaded;};
