'use strict';
const Module=require('node:module');
const ExcelJS=require('exceljs');
const C={STT:1,WORKER:2,NAME:3,MACHINE:4,SHIFT:5,TRAINING:6,TOTAL:7,ACTUAL:8,CM:9,DEDTOTAL:10,DEDF:11,DEDL:26,PRODUCT:27,STD:28,OUT:29,TT:30,DATE:31,OUTPH:32,OK:33,NG:34,NGR:35,DEFF:36,DEFL:54};
const DED=['Thiếu sản lượng','Bật máy, xét máy','Chuyển mã','Chỉnh máy','Chờ chỉnh máy','Mất điện','Mất khí','Chờ hàng','Bảo dưỡng máy','Nghỉ giải lao','Giao ca','Dừng máy đi hỗ trợ','Giặt cs/cân cs, tuốt-tái pp, GL','5s','Học việc, đào tạo','Đi muộn về sớm'];
const DEF=['KQD','Vỡ cao su','K xước cong gãy','Cao su xoay','Cắt không đứt','bavia','CSH','ppcm','KT lớn','KT nhỏ','LCS','cắt lẹm','rách nvl','Chân ngắn dài','sót via','fure trục','lẫn cs','bavia cắt hụt','thiếu cao su'];
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').replace(/[^a-zA-Z0-9]+/g,'').toUpperCase();
const txt=v=>v==null?'':String(v).trim();
const num=v=>{if(v==null||v==='')return null;const n=Number(String(v).replace(/,/g,''));return Number.isFinite(n)?n:null;};
const dt=v=>{if(!v)return null;if(v instanceof Date&&!Number.isNaN(v.getTime()))return v;const s=String(v).trim().slice(0,10);if(/^\d{4}-\d{2}-\d{2}$/.test(s)){const[y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)}const x=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);return x?new Date(+x[3],+x[2]-1,+x[1]):null;};
const dk=v=>{const d=dt(v);return d?`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`:''};
function extra(r){if(!r?.extra_data)return{};if(typeof r.extra_data==='object'&&!Array.isArray(r.extra_data))return r.extra_data;try{const x=JSON.parse(String(r.extra_data));return x&&typeof x==='object'&&!Array.isArray(x)?x:{}}catch{return{}}}
function items(r,k){const x=k==='d'?r?.deductions:r?.defects;if(Array.isArray(x))return x;const e=extra(r);const a=k==='d'?[e.deductions,e.deductionDetails,e.timeDeductions]:[e.defects,e.defectDetails,e.ngDetails];return a.find(Array.isArray)||[]}
function aliases(x,k,t){const code=k==='d'?(x?.deduction_code??x?.deduction_type_code??x?.code):(x?.defect_code??x?.defect_type_code??x?.code);const name=k==='d'?(x?.deduction_name??x?.deduction_type_name??x?.name):(x?.defect_name??x?.defect_type_name??x?.name);return[code,name,t?.code,t?.name,t?.deduction_code,t?.deduction_name,t?.defect_code,t?.defect_name].filter(Boolean).map(norm)}
function detail(r,p,h,k){const target=norm(h),types=k==='d'?(p?.deductionTypes||[]):(p?.defectTypes||[]);let total=0,found=false;for(const x of items(r,k)){const id=num(k==='d'?(x?.deduction_type_id??x?.deductionTypeId??x?.type_id):(x?.defect_type_id??x?.defectTypeId??x?.type_id));const t=id==null?null:types.find(y=>Number(y?.id)===id);if(!aliases(x,k,t).includes(target))continue;const keys=k==='d'?['hours','deduction_hours','duration_hours','time_hours','value']:['quantity','defect_quantity','ng_quantity','qty','count','value'];let val=0;for(const key of keys){const n=num(x?.[key]);if(n!=null){val=n;break}}total+=val;found=true}return found?total:null}
function machine(r){const a=(Array.isArray(r?.machineLines)?r.machineLines:[]).map(x=>txt(x?.machine_code??x?.machine_no??x?.machine_name)).filter(Boolean);return a.length?[...new Set(a)].join(', '):txt(r?.machine_no??r?.machine_code)}
function product(r){const a=(Array.isArray(r?.machineLines)?r.machineLines:[]).map(x=>txt(x?.product_code??x?.product_name)).filter(Boolean);return a.length?[...new Set(a)].join(', '):txt(r?.product_code??r?.product_name)}
function shift(r){const e=extra(r);return txt(r?.shift??r?.ca??e.shift??e.ca)}
function cm(r){const e=extra(r);for(const v of[r?.changeover_count,r?.change_machine_count,r?.so_lan_cm,r?.changeovers,e.changeover_count,e.change_machine_count,e.so_lan_cm,e.changeovers]){const n=num(v);if(n!=null)return n}return null}
function style(a,b){b.font=a.font?{...a.font}:b.font;b.fill=a.fill?JSON.parse(JSON.stringify(a.fill)):b.fill;b.border=a.border?JSON.parse(JSON.stringify(a.border)):b.border;b.alignment=a.alignment?{...a.alignment}:b.alignment;b.protection=a.protection?{...a.protection}:b.protection;b.numFmt=a.numFmt}
function rowStyle(a,b,n){b.height=a.height;for(let c=1;c<=n;c++)style(a.getCell(c),b.getCell(c))}
function clear(r,n){for(let c=1;c<=n;c++)r.getCell(c).value=null}
function formats(s,r){s.getCell(r,C.TRAINING).numFmt='0';for(const c of[C.TOTAL,C.ACTUAL,C.CM,C.DEDTOTAL,...Array.from({length:16},(_,i)=>C.DEDF+i)])s.getCell(r,c).numFmt='0.##';for(const c of[C.STD,C.OUT])s.getCell(r,c).numFmt='#,##0.##';s.getCell(r,C.TT).numFmt='0%';s.getCell(r,C.DATE).numFmt='d-mmm';s.getCell(r,C.OUTPH).numFmt='0.##';for(const c of[C.OK,C.NG,...Array.from({length:19},(_,i)=>C.DEFF+i)])s.getCell(r,c).numFmt='#,##0';s.getCell(r,C.NGR).numFmt='0.00%'}
function headers(s){const h={1:'STT',2:'Mã số nhân viên',3:'Tên',4:'Số máy',5:'ca',6:'%\nhọc việc',7:'Thời gian\nLàm',8:'Thời gian\nLàm việc',9:'Số lần\nCM',10:'Tổng TG trừ giờ',27:'SP',28:'Định mức',29:'TT',30:'%TT',31:'Ngày/Tháng',32:'TT/h',33:'OK',34:'tổng NG',35:'%NG'};DED.forEach((v,i)=>h[C.DEDF+i]=v);DEF.forEach((v,i)=>h[C.DEFF+i]=v);for(const[k,v]of Object.entries(h))s.getCell(3,+k).value=v}
function write(s,r,x,p,i){s.getCell(r,C.STT).value=i;s.getCell(r,C.WORKER).value=txt(x?.worker_code);s.getCell(r,C.NAME).value=txt(x?.full_name??x?.worker_name);s.getCell(r,C.MACHINE).value=machine(x);s.getCell(r,C.SHIFT).value=shift(x);s.getCell(r,C.TRAINING).value=num(x?.training_percent);s.getCell(r,C.TOTAL).value=num(x?.total_time??x?.working_time);s.getCell(r,C.ACTUAL).value=num(x?.actual_time??x?.working_time??x?.total_time);s.getCell(r,C.CM).value=cm(x);s.getCell(r,C.PRODUCT).value=product(x);s.getCell(r,C.STD).value=num(x?.standard_output??x?.standard);s.getCell(r,C.OUT).value=num(x?.actual_output??x?.output??x?.adjusted_output??x?.tt_ok);s.getCell(r,C.DATE).value=dt(x?.work_date);s.getCell(r,C.OK).value=num(x?.tt_ok??x?.ok_quantity??x?.ok);DED.forEach((h,i)=>s.getCell(r,C.DEDF+i).value=detail(x,p,h,'d'));DEF.forEach((h,i)=>s.getCell(r,C.DEFF+i).value=detail(x,p,h,'f'));s.getCell(r,C.DEDTOTAL).value={formula:`SUM(K${r}:Z${r})`};s.getCell(r,C.TT).value={formula:`IFERROR(AC${r}/AB${r},0)`};s.getCell(r,C.OUTPH).value={formula:`IFERROR(AC${r}/H${r},0)`};s.getCell(r,C.NG).value={formula:`SUM(AJ${r}:BB${r})`};s.getCell(r,C.NGR).value={formula:`IFERROR(AH${r}/(AG${r}+AH${r}),0)`};formats(s,r)}
function rebuild(buf,p){const reports=[...(p?.reports||[])].sort((a,b)=>dk(a?.work_date).localeCompare(dk(b?.work_date))||txt(a?.worker_code).localeCompare(txt(b?.worker_code),'vi',{numeric:true})||Number(a?.id||0)-Number(b?.id||0));return(async()=>{const wb=new ExcelJS.Workbook();await wb.xlsx.load(buf);const s=wb.getWorksheet('Cắt lồng')||wb.worksheets[0];if(!s)throw new Error('Không tìm thấy sheet Cắt lồng');const max=C.DEFL;let old=4;for(let r=5;r<=s.rowCount;r++){let used=false;for(let c=1;c<=max;c++){const v=s.getCell(r,c).value;if(v!==null&&v!==undefined&&v!==''){used=true;break}}if(used)old=r}const ds=s.getRow(Math.min(6,old));const ss=s.getRow(5);for(let r=5;r<=old;r++)clear(s.getRow(r),max);headers(s);let row=5,seq=0,last='';for(const x of reports){const d=dk(x?.work_date);if(!d)continue;if(d!==last){last=d;seq=0;rowStyle(ss,s.getRow(row),max);clear(s.getRow(row),max);const c=s.getCell(row,C.STT);c.value=dt(d);c.numFmt='d/m/yyyy';c.font={...c.font,bold:true};c.alignment={...c.alignment,horizontal:'left',vertical:'center'};row++}seq++;rowStyle(ds,s.getRow(row),max);clear(s.getRow(row),max);write(s,row,x,p,seq);row++}s.getCell(4,1).value='Tổng';for(const c of[C.TOTAL,C.ACTUAL,C.CM,C.DEDTOTAL,...Array.from({length:16},(_,i)=>C.DEDF+i),C.STD,C.OUT,C.OK,C.NG,...Array.from({length:19},(_,i)=>C.DEFF+i)]){const L=s.getColumn(c).letter;s.getCell(4,c).value={formula:`SUM(${L}5:${L}${row-1})`}}s.getCell(4,C.TT).value={formula:'IFERROR(AC4/AB4,0)'};s.getCell(4,C.OUTPH).value={formula:'IFERROR(AC4/H4,0)'};s.getCell(4,C.NGR).value={formula:'IFERROR(AH4/(AG4+AH4),0)'};formats(s,4);s.freezePanes='A6';s.autoFilter=null;for(let r=row;r<=old;r++)clear(s.getRow(r),max);return Buffer.from(await wb.xlsx.writeBuffer())})()}
function patch(m){if(!m||m.__ktcGcFinalDbTruthV4)return m;const orig=m.buildProcessWorkbookLocal,split=m.buildSplitMonthlyWorkbooksLocal;if(typeof orig!=='function'||typeof split!=='function')throw new Error('Không tìm thấy builder Excel GC');m.buildProcessWorkbookLocal=async(args={})=>{const res=await orig(args);if(String(args.processCode||'').toUpperCase()==='GC'&&res?.buffer&&args?.payload?.processes?.GC?.reports){res.buffer=await rebuild(res.buffer,args.payload.processes.GC);res.reportCount=args.payload.processes.GC.reports.length;res.requestedYearMonth=String(args.date||'').slice(0,7)}return res};m.buildSplitMonthlyWorkbooksLocal=async(args={})=>{const res=await split(args);if(res?.processes?.length&&args?.payload?.processes?.GC?.reports){for(const item of res.processes){if(String(item?.processCode||'').toUpperCase()==='GC'&&item?.buffer)item.buffer=await rebuild(item.buffer,args.payload.processes.GC)}}return res};Object.defineProperty(m,'__ktcGcFinalDbTruthV4',{value:true});return m}
require('./excelExportContractPatch.v3.cjs');
const mp=require.resolve('./monthlyWorkbookLocal.cjs');
const m=patch(require(mp));if(require.cache[mp])require.cache[mp].exports=m;
module.exports=m;
