'use strict';

// DB-truth Excel patch: keep the existing workbook/template, but overwrite
// exported cells from the approved report payload returned by TiDB.
const Module = require('node:module');
const ExcelJS = require('exceljs');
const { dialog } = require('electron');
const originalLoad = Module._load;
const originalFetch = globalThis.fetch;

const norm = v => String(v ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').trim().toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim();
const text = v => v == null ? '' : String(v).trim();
const num = v => { if(v == null || v === '') return null; const n=Number(v); return Number.isFinite(n)?n:null; };
const dateValue = v => { if(v instanceof Date || !v) return v; const s=String(v).slice(0,10); if(!/^\d{4}-\d{2}-\d{2}$/.test(s)) return v; const [y,m,d]=s.split('-').map(Number); return new Date(y,m-1,d); };
function headers(sheet){ const m=new Map(); for(let c=1;c<=sheet.columnCount;c++){const h=norm(sheet.getCell(5,c).value); if(h)m.set(h,c);} return m; }
function put(sheet,hs,row,names,value,fmt){ for(const n of names){const c=hs.get(norm(n)); if(c){sheet.getCell(row,c).value=value; if(fmt)sheet.getCell(row,c).numFmt=fmt; return true;}} return false; }
function lines(r){return Array.isArray(r?.machineLines)?r.machineLines:[];}
function machine(r){const a=lines(r).map(x=>text(x.machine_code??x.machine_no??x.machine_name)).filter(Boolean);return a.length?[...new Set(a)].join(', '):text(r.machine_no??r.machine_code??r.machine);}
function product(r){const a=lines(r).map(x=>text(x.product_code??x.product_name)).filter(Boolean);return a.length?[...new Set(a)].join(', '):text(r.product_code??r.product_name??r.product);}
function detailMap(r,kind){const out=new Map();const arr=Array.isArray(r?.[kind==='deduction'?'deductions':'defects'])?r[kind==='deduction'?'deductions':'defects']:[];for(const x of arr){const id=num(x?.[kind==='deduction'?'deduction_type_id':'defect_type_id']);const code=text(x?.[kind==='deduction'?'deduction_type_code':'defect_type_code']??x?.code);const name=text(x?.[kind==='deduction'?'deduction_type_name':'defect_type_name']??x?.name);const value=num(x?.[kind==='deduction'?'hours':'quantity'])??0;for(const k of [id?`ID:${id}`:'',norm(code),norm(name)].filter(Boolean))out.set(k,(out.get(k)||0)+value);}return out;}
function typeMap(pd,kind){const arr=Array.isArray(pd?.[kind==='deduction'?'deductionTypes':'defectTypes'])?pd[kind==='deduction'?'deductionTypes':'defectTypes']:[];const m=new Map();for(const x of arr){const id=num(x?.id);if(!id)continue;const code=text(x?.[kind==='deduction'?'deduction_code':'defect_code']??x?.code);const name=text(x?.[kind==='deduction'?'deduction_name':'defect_name']??x?.name??x?.label);if(code)m.set(norm(code),`ID:${id}`);if(name)m.set(norm(name),`ID:${id}`);}return m;}
function rowMatches(sheet,row,hs,r,byId){const idCol=hs.get('ID')||hs.get('MA BAO CAO')||hs.get('REPORT ID');if(idCol){const id=Number(sheet.getCell(row,idCol).value);if(id>0)return byId.get(id)||null;}const workerCol=hs.get('MA NV')||hs.get('MA CONG NHAN');if(workerCol){const w=norm(sheet.getCell(row,workerCol).value);if(w){const dateCol=hs.get('NGAY')||hs.get('NGAY LAM VIEC')||hs.get('THOI GIAN');for(const x of byId.values()){if(norm(x.worker_code)!==w)continue;if(!dateCol)return x;const cell=sheet.getCell(row,dateCol).value;if(!cell||String(cell).slice(0,10)===String(x.work_date).slice(0,10))return x;}}}return null;}
function patchSheet(sheet,reports,pd){if(sheet.state!=='visible'||sheet.name.startsWith('_'))return;const hs=headers(sheet);if(!hs.size)return;const byId=new Map(reports.map(r=>[Number(r.id),r]));const dTypes=typeMap(pd,'deduction'),fTypes=typeMap(pd,'defect');for(let row=6;row<=sheet.rowCount;row++){const r=rowMatches(sheet,row,hs,null,byId);if(!r)continue;put(sheet,hs,row,['ID','Mã báo cáo','Report ID'],num(r.id));put(sheet,hs,row,['Ngày','Ngày làm việc'],dateValue(r.work_date),'dd/mm/yyyy');put(sheet,hs,row,['Mã NV','Mã công nhân'],text(r.worker_code));put(sheet,hs,row,['Tên NV','Tên công nhân','Họ tên'],text(r.full_name??r.worker_name??r.worker_full_name));put(sheet,hs,row,['Ca'],text(r.shift));put(sheet,hs,row,['Máy','Mã máy'],machine(r));put(sheet,hs,row,['Mã SP','Mã sản phẩm','Sản phẩm'],product(r));put(sheet,hs,row,['% học việc','% Học việc'],num(r.training_percent));put(sheet,hs,row,['Định mức','Định mức/H'],num(r.standard_output??r.standard_output_per_hour));put(sheet,hs,row,['Tổng thời gian'],num(r.total_time));put(sheet,hs,row,['Thời gian chạy thực tế','Thời gian thực tế'],num(r.actual_time));put(sheet,hs,row,['Tổng thời gian trừ','Thời gian trừ'],num(r.deduction_time));put(sheet,hs,row,['OK','SL OK','Sản lượng OK'],num(r.tt_ok??r.ok_quantity));put(sheet,hs,row,['NG','SL NG','Tổng NG'],num(r.tt_ng??r.total_ng??r.ng_quantity));put(sheet,hs,row,['SP công nhân nhập','Sản lượng thực tế','Sản lượng','Output'],num(r.actual_output));const dm=detailMap(r,'deduction'),fm=detailMap(r,'defect');for(const [h,c] of hs){const dk=dTypes.get(h);if(dk)sheet.getCell(row,c).value=dm.get(dk)??0;const fk=fTypes.get(h);if(fk)sheet.getCell(row,c).value=fm.get(fk)??0;}}}
async function patchBuffer(buffer,payload,code){const pd=payload?.processes?.[code];if(!pd||!Array.isArray(pd.reports))return buffer;const wb=new ExcelJS.Workbook();await wb.xlsx.load(buffer);for(const s of wb.worksheets)patchSheet(s,pd.reports,pd);return Buffer.from(await wb.xlsx.writeBuffer());}
function makeResponse(buffer,fileName){return new Response(buffer,{status:200,headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(fileName)}`,'Cache-Control':'private, no-store','X-KTC-Excel-Backend':'desktop-db-truth'}});}
async function fetchData(apiUrl,auth,date){const r=await originalFetch(`${apiUrl}/reports/export-excel/company-data?date=${encodeURIComponent(date)}`,{headers:{Authorization:auth,Accept:'application/json'}});if(!r.ok)throw new Error(`company-data HTTP ${r.status}`);const j=await r.json();if(!j?.success||!j?.data?.processes)throw new Error('Backend không trả payload company-data hợp lệ.');return j.data;}
function auth(init){const h=init?.headers||{};return typeof h.get==='function'?h.get('authorization')||'':h.authorization||h.Authorization||'';}
async function intercept(url,init){const u=new URL(url),body=typeof init.body==='string'?JSON.parse(init.body||'{}'):(init.body||{}),date=String(body.date||'').trim();if(!date)throw new Error('Thiếu ngày xuất Excel.');const token=auth(init);if(!token)throw new Error('Thiếu token đăng nhập.');const payload=await fetchData(u.origin,token,date);const monthly=require('./monthlyWorkbookLocal.cjs');if(u.pathname.endsWith('/reports/export-excel')){const b=await monthly.buildMonthlySummaryWorkbookLocal({date,payload});return makeResponse(await patchBuffer(b.buffer,payload,null),b.fileName||`00_TONG_HOP_SAN_XUAT_${date.slice(5,7)}-${date.slice(0,4)}.xlsx`);}const pid=Number(body.processId);const list=await (await originalFetch(`${u.origin}/reports/export-excel/processes?date=${encodeURIComponent(date)}`,{headers:{Authorization:token,Accept:'application/json'}})).json();const info=(list.data||[]).find(x=>Number(x?.id??x?.processId??x?.process_id)===pid);if(!info)throw new Error(`Không tìm thấy processId=${pid}.`);const code=String(info.processCode??info.process_code??info.code??'').trim();const b=await monthly.buildProcessWorkbookLocal({date,payload,processCode:code});return makeResponse(await patchBuffer(b.buffer,payload,code),b.fileName||`Bao-cao-${code}-${date.slice(5,7)}-${date.slice(0,4)}.xlsx`);}
function install(){if(globalThis.__KTC_DB_TRUTH_EXCEL_PATCH__)return;globalThis.fetch=async function(input,init={}){const url=typeof input==='string'?input:input?.url||'';const method=String(init?.method||(typeof input!=='string'?input?.method:'GET')||'GET').toUpperCase();if(method==='POST'&&/\/reports\/export-excel(?:\/process)?(?:\?|$)/.test(String(url))){try{return await intercept(String(url),init);}catch(e){console.error('[KTC] DB_TRUTH_EXCEL_EXPORT_FAILED',e);try{await dialog.showMessageBox({type:'error',title:'Lỗi xuất Excel',message:'Không thể xuất Excel theo dữ liệu DB.',detail:String(e?.stack||e).slice(0,5000)});}catch{}throw e;}}return originalFetch(input,init);};globalThis.__KTC_DB_TRUTH_EXCEL_PATCH__=true;}
function patchMonthly(mod){if(!mod||mod.__ktcDbTruthPatched)return mod;for(const name of ['buildSplitMonthlyWorkbooksLocal','buildProcessWorkbookLocal']){const fn=mod[name];if(typeof fn!=='function')continue;mod[name]=async(args={})=>{const result=await fn(args);if(Array.isArray(result?.processes)){for(const p of result.processes)if(p?.buffer)p.buffer=await patchBuffer(p.buffer,args.payload,p.processCode);}else if(result?.buffer)result.buffer=await patchBuffer(result.buffer,args.payload,args.processCode);return result;};}Object.defineProperty(mod,'__ktcDbTruthPatched',{value:true});return mod;}
install();Module._load=function(request,parent,isMain){const loaded=originalLoad.call(this,request,parent,isMain);if(typeof request==='string'&&/monthlyWorkbookLocal\.cjs$/.test(request))return patchMonthly(loaded);return loaded;};
