'use strict';

const Module = require('node:module');
const fs = require('node:fs/promises');
const path = require('node:path');
const ExcelJS = require('exceljs');
const JSZip = require('jszip');
const originalLoad = Module._load;

const TEMPLATE_NAME='bao-cao-cat-long-export.xlsx';
const SHEET_NAME='Cắt lồng';
const HEADER_ROW=5;
const DAY_ANCHOR_FIRST=6;
const DAY_BLOCK_SIZE=191;
const DATA_OFFSET=1;
const DATA_CAPACITY=188;

const log=(event,data={})=>{try{const m=process.memoryUsage();console.log('[KTC-EXCEL-TEMPLATE]',event,JSON.stringify({elapsedMs:Math.round(Number(process.hrtime.bigint())/1e6),rssMB:Math.round(m.rss/1048576),heapMB:Math.round(m.heapUsed/1048576),...data}));}catch(_){}};
const text=v=>v==null?'':String(v);
const num=v=>{const n=Number(text(v).replace(/,/g,'').trim());return Number.isFinite(n)?n:0;};
const norm=v=>text(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').replace(/[^A-Za-z0-9]+/g,'_').replace(/^_+|_+$/g,'').toUpperCase();
function dateKey(v){if(!v)return'';if(typeof v==='string'&&/^\d{4}-\d{2}-\d{2}/.test(v))return v.slice(0,10);const d=new Date(v);if(Number.isNaN(d.getTime()))return'';return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function excelDate(v){const k=dateKey(v);if(!k)return null;const[a,b,c]=k.split('-').map(Number);return new Date(a,b-1,c);}
function machine(r){const a=text(r.machine_no||r.machine_code).trim();const xs=Array.isArray(r.machine_lines)?r.machine_lines:Array.isArray(r.machines)?r.machines:[];return[...new Set([a,...xs.map(x=>text(x?.machine_no||x?.machine_code||x?.code).trim()).filter(Boolean)].filter(Boolean))].join(', ');}
const sum=(xs,k)=>(xs||[]).reduce((a,x)=>a+num(x?.[k]),0);
function metrics(r){const ok=num(r.tt_ok??r.ok_quantity??r.ok),ng=sum(r.defects,'quantity'),actual=num(r.actual_time??r.working_time??r.work_time),ded=sum(r.deductions,'hours'),total=num(r.total_time)||actual+ded,standard=num(r.standard_output??r.standard_output_per_hour??r.standard),training=Math.min(100,Math.max(0,num(r.training_percent??100)));const countedNg=(r.defects||[]).reduce((a,x)=>norm(x.defect_code||x.code||x.defect_name)==='KQD'&&Number(r.exclude_kqd_from_tt||0)===1?a:a+num(x.quantity),0);const output=r.actual_output==null||text(r.actual_output).trim()===''?ok+countedNg:num(r.actual_output),perHour=actual>0?output/actual:0;return{ok,ng,actual,ded,total,standard,training,output,perHour,achievement:standard>0?perHour/standard:0,ngRate:ok+ng>0?ng/(ok+ng):0};}
function valid(r){return Boolean(r&&text(r.worker_code).trim()&&text(r.product_code||r.product_name).trim()&&dateKey(r.work_date));}
function sorted(rs){return[...(rs||[])].filter(valid).sort((a,b)=>dateKey(a.work_date).localeCompare(dateKey(b.work_date))||text(a.entry_date||a.created_at||a.approved_at).localeCompare(text(b.entry_date||b.created_at||b.approved_at))||text(a.worker_code).localeCompare(text(b.worker_code),undefined,{numeric:true})||Number(a.id||0)-Number(b.id||0));}

async function sanitizeTemplate(buffer){const zip=await JSZip.loadAsync(buffer);const f=zip.file('xl/workbook.xml');if(!f||!(await f.async('string')).includes('Cắt lồng'))return buffer;let parts=0,rels=0,sheets=0;for(const n of Object.keys(zip.files)){if(/^xl\/comments\d+\.xml$/i.test(n)||/^xl\/drawings\/vmlDrawing\d+\.vml$/i.test(n)){zip.remove(n);parts++;}}for(const n of Object.keys(zip.files)){if(!/^xl\/worksheets\/_rels\/sheet\d+\.xml\.rels$/i.test(n))continue;const x=zip.file(n);if(!x)continue;const s=await x.async('string'),t=s.replace(/<Relationship\b[^>]*\bType="[^"]*(?:comments|vmlDrawing)[^"]*"[^>]*\/?>/gi,'');if(t!==s){zip.file(n,t);rels++;}}for(const n of Object.keys(zip.files)){if(!/^xl\/worksheets\/sheet\d+\.xml$/i.test(n))continue;const x=zip.file(n);if(!x)continue;const s=await x.async('string'),t=s.replace(/<legacyDrawing\b[^>]*\/?>/gi,'');if(t!==s){zip.file(n,t);sheets++;}}if(!parts&&!rels&&!sheets){log('TEMPLATE_SANITIZE_NOT_NEEDED');return buffer;}const out=await zip.generateAsync({type:'nodebuffer',compression:'DEFLATE',compressionOptions:{level:6}});log('TEMPLATE_SANITIZED',{removedParts:parts,rewrittenRels:rels,rewrittenSheets:sheets,bytesBefore:buffer.length,bytesAfter:out.length});return out;}

const aliases={STT:'STT',TIME:'THOI_GIAN_NHAP',WORKER:'MA_NV',NAME:'TEN_NV',SHIFT:'CA',OP:'LOAI_THAO_TAC',MODE:'CHE_DO',MACHINE:'MAY',PRODUCT:'MA_SP',TRAINING:'HOCPV',STANDARD:'DINH_MUC',TOTAL:'TONG_THOI_GIAN',ACTUAL:'THOI_GIAN_THUC_TE',DEDUCTION_TOTAL:'TONG_THOI_GIAN_TRU',OUTPUT:'SAN_LUONG_THUC_TE',OK:'DAT',NG:'NG',NGRATE:'TY_LE_NG',RATE:'NANG_SUAT',ACH:'TY_LE_DAT'};
function headerKey(v){const h=norm(v);for(const[k,x]of Object.entries(aliases))if(h===x)return k;if(h==='THOI_GIAN_NHAP_LIEU')return'TIME';if(h==='MA_NHAN_VIEN')return'WORKER';if(h==='TEN_NHAN_VIEN')return'NAME';if(h==='LOAI_THAO_TAC')return'OP';if(h==='MA_MAY')return'MACHINE';if(h==='MA_SAN_PHAM')return'PRODUCT';if(h==='HOC_VIEC'||h==='HOC_VIEC_PERCENT')return'TRAINING';if(h==='THUC_TE')return'OUTPUT';if(h==='DAT_NANG_SUAT')return'ACH';if(h==='NG_RATE')return'NGRATE';return h;}
function headerMap(sheet){const m=new Map();for(let c=1;c<=sheet.columnCount;c++){const h=sheet.getRow(HEADER_ROW).getCell(c).value;if(text(h).trim())m.set(c,headerKey(h));}return m;}
function detail(r,header,type){const target=norm(header);const items=type==='deduction'?(r.deductions||[]):(r.defects||[]);return items.reduce((a,x)=>{const code=norm(x.deduction_code||x.defect_code||x.code||x.deduction_name||x.defect_name),name=norm(x.deduction_name||x.defect_name||x.code||x.deduction_code||x.defect_code);return a+(code===target||name===target?num(type==='deduction'?x.hours:x.quantity):0);},0);}
function writeReport(row,r,i,map){const m=metrics(r);for(const[c,key]of map){const cell=row.getCell(c);switch(key){case'STT':cell.value=i;break;case'TIME':cell.value=excelDate(r.entry_date||r.created_at||r.approved_at||r.work_date);cell.numFmt='dd/mm/yyyy hh:mm';break;case'WORKER':cell.value=text(r.worker_code);break;case'NAME':cell.value=text(r.full_name||r.worker_name||r.worker_full_name||r.user_full_name);break;case'SHIFT':cell.value=text(r.shift).toUpperCase();break;case'OP':cell.value=text(r.operation_type||r.work_type||r.operation||'CẮT');break;case'MODE':cell.value=text(r.mode||r.work_mode||r.production_mode||'TAY').toUpperCase();break;case'MACHINE':cell.value=machine(r);break;case'PRODUCT':cell.value=text(r.product_code||r.product_name);break;case'TRAINING':cell.value=m.training/100;cell.numFmt='0%';break;case'STANDARD':cell.value=m.standard;cell.numFmt='#,##0.00';break;case'TOTAL':cell.value=m.total;cell.numFmt='0.00';break;case'ACTUAL':cell.value=m.actual;cell.numFmt='0.00';break;case'DEDUCTION_TOTAL':cell.value=m.ded;cell.numFmt='0.00';break;case'OUTPUT':cell.value=m.output;break;case'OK':cell.value=m.ok;break;case'NG':cell.value=m.ng;break;case'NGRATE':cell.value=m.ngRate;cell.numFmt='0.00%';break;case'RATE':cell.value=m.perHour;break;case'ACH':cell.value=m.achievement;cell.numFmt='0.00%';break;default:cell.value=detail(r,key,'deduction')||detail(r,key,'defect');break;}}}

async function buildGcFromTemplate(args){const started=Number(process.hrtime.bigint())/1e6;const reports=sorted(args?.payload?.processes?.GC?.reports||[]);const templatePath=path.join(args.appPath,'assets','templates',TEMPLATE_NAME);log('BUILD_START',{date:args.date,reportCount:reports.length,templatePath});const raw=await fs.readFile(templatePath);log('TEMPLATE_READ_DONE',{ms:Math.round(Number(process.hrtime.bigint())/1e6-started),bytes:raw.length});const safe=await sanitizeTemplate(raw);const wb=new ExcelJS.Workbook();const loadStart=Number(process.hrtime.bigint())/1e6;await wb.xlsx.load(safe);log('TEMPLATE_LOAD_DONE',{ms:Math.round(Number(process.hrtime.bigint())/1e6-loadStart),totalMs:Math.round(Number(process.hrtime.bigint())/1e6-started),sheetCount:wb.worksheets.length,sheets:wb.worksheets.map(s=>({name:s.name,rows:s.rowCount,cols:s.columnCount}))});const target=wb.getWorksheet(SHEET_NAME)||wb.worksheets[0];if(!target)throw new Error('Template không có sheet Cắt lồng.');for(const s of[...wb.worksheets])if(s.id!==target.id)wb.removeWorksheet(s.id);const map=headerMap(target);log('TEMPLATE_HEADER_MAP',{columns:[...map.entries()]});const byDay=new Map();for(const r of reports){const d=Number(dateKey(r.work_date).slice(8,10));if(!byDay.has(d))byDay.set(d,[]);byDay.get(d).push(r);}const injectStart=Number(process.hrtime.bigint())/1e6;for(let day=1;day<=31;day++){const anchor=DAY_ANCHOR_FIRST+(day-1)*DAY_BLOCK_SIZE,start=anchor+DATA_OFFSET,end=start+DATA_CAPACITY-1,recs=byDay.get(day)||[];if(recs.length>DATA_CAPACITY)throw new Error(`Ngày ${day} có ${recs.length} báo cáo, vượt sức chứa ${DATA_CAPACITY} dòng của template Cắt lồng.`);const dateRow=target.getRow(anchor);dateRow.getCell(1).value=recs.length?excelDate(`${String(args.date).slice(0,7)}-${String(day).padStart(2,'0')}`):null;dateRow.getCell(1).numFmt='dd/mm/yyyy';for(let rn=start;rn<=end;rn++){const row=target.getRow(rn);for(let c=2;c<=target.columnCount;c++)row.getCell(c).value=null;row.hidden=rn>=start+recs.length;}recs.forEach((r,i)=>writeReport(target.getRow(start+i),r,i+1,map));}log('DATA_INJECT_DONE',{ms:Math.round(Number(process.hrtime.bigint())/1e6-injectStart),reportCount:reports.length});wb.calcProperties.fullCalcOnLoad=false;wb.calcProperties.forceFullCalc=false;wb.calcProperties.calcMode='auto';const writeStart=Number(process.hrtime.bigint())/1e6;const buffer=Buffer.from(await wb.xlsx.writeBuffer());log('WRITE_BUFFER_DONE',{ms:Math.round(Number(process.hrtime.bigint())/1e6-writeStart,totalMs:Math.round(Number(process.hrtime.bigint())/1e6-started),bytes:buffer.length});return{buffer,result:{code:'GC',sheet:target.name,reportCount:reports.length},processCode:'GC',processName:'CẮT/LỒNG',fileName:`04_CAT_LONG_${String(args.date).slice(5,7)}-${String(args.date).slice(0,4)}.xlsx`,reportCount:reports.length,formulaReplacementCount:0,templateKind:'ONE_SHEET_TEMPLATE_INJECT'};}

function patchMonthly(mod){if(!mod||mod.__ktcV3MonthlyPatched)return mod;const original=mod.buildProcessWorkbookLocal;if(typeof original!=='function'){log('PATCH_FAILED',{reason:'buildProcessWorkbookLocal_missing'});return mod;}mod.buildProcessWorkbookLocal=async args=>String(args?.processCode||'').trim().toUpperCase()==='GC'?buildGcFromTemplate(args):original(args);mod.buildSplitMonthlyWorkbooksLocal=async args=>{const processes=[];for(const[code,data]of Object.entries(args?.payload?.processes||{}))if(Array.isArray(data?.reports)&&data.reports.length)processes.push(await mod.buildProcessWorkbookLocal({...args,processCode:code}));return{summary:null,processes};};Object.defineProperty(mod,'__ktcV3MonthlyPatched',{value:true});log('MONTHLY_PATCH_INSTALLED_V3');return mod;}
Module._load=function(request,parent,isMain){const loaded=originalLoad.call(this,request,parent,isMain);if(typeof request==='string'&&/monthlyWorkbookLocal\.cjs$/.test(request))return patchMonthly(loaded);return loaded;};
log('EXCEL_EXPORT_V3_READY');
