'use strict';
const fs=require('fs'),os=require('os'),path=require('path'),ExcelJS=require('exceljs');
const monthly=require('./monthlyWorkbookLocal.cjs');
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[đĐ]/g,'d').replace(/[^A-Za-z0-9]/g,'').toUpperCase();
const num=v=>{const n=Number(String(v??'').replace(/,/g,'').trim());return Number.isFinite(n)?n:0};
const D=['Thiếu sản lượng','Bật máy, xét máy','Chuyển mã','Chỉnh máy','Chờ chỉnh máy','Mất điện','Mất khí','Chờ hàng','Bảo dưỡng máy','Nghỉ giải lao','Giao ca','Dừng máy đi hỗ trợ','Giặt cs/cân cs, tuốt-tái pp, GL','5S','Học việc, đào tạo','Đi muộn về sớm'];
const F=['KQD','Vỡ cao su','K xước cong gãy','Cao su xoay','Cắt không đứt','bavia','CSH','ppcm','KT lớn','KT nhỏ','LCS','cắt lẹm','rách nvl','Chân ngắn dài','sót via','fure trục','lẫn cs','bavia cắt hụt','thiếu cao su'];
const fields=(x,k)=>k==='d'?[x?.deduction_code,x?.deduction_type_code,x?.code,x?.deduction_name,x?.deduction_type_name,x?.name]:[x?.defect_code,x?.defect_type_code,x?.code,x?.defect_name,x?.defect_type_name,x?.name];
const match=(h,x,k)=>{h=norm(h);return fields(x,k).some(v=>{v=norm(v);return v&&(h===v||(v.length>3&&h.includes(v))||(v.length>3&&v.includes(h)))})};
const val=(x,k)=>num(k==='d'?x?.hours:x?.quantity);
const reports=p=>{const a=[...(p?.processes?.GC?.reports||[])];a.sort((x,y)=>String(x?.work_date||'').localeCompare(String(y?.work_date||''))||String(x?.approved_at||x?.created_at||'').localeCompare(String(y?.approved_at||y?.created_at||''))||num(x?.id)-num(y?.id));return a};
const isReportRow=r=>{const a=r?.getCell(1)?.value,b=r?.getCell(2)?.value;return typeof a==='number'&&Number.isFinite(a)&&a>=1&&b!=null&&String(b).trim()!==''};
const copyRowStyle=(from,to)=>{to.height=from.height;to.hidden=false;to.outlineLevel=from.outlineLevel||0;for(let c=1;c<=Math.max(from.cellCount,to.cellCount,219);c++){const a=from.getCell(c),b=to.getCell(c);if(a.hasStyle){b.font=a.font?{...a.font,color:a.font.color?{...a.font.color}:undefined}:b.font;b.fill=a.fill?JSON.parse(JSON.stringify(a.fill)):b.fill;b.border=a.border?JSON.parse(JSON.stringify(a.border)):b.border;b.alignment=a.alignment?{...a.alignment}:b.alignment;b.protection=a.protection?{...a.protection}:b.protection;if(a.numFmt)b.numFmt=a.numFmt}}};
async function patch(buf,p){const input=Buffer.isBuffer(buf)?buf:Buffer.from(buf);const tmp=path.join(os.tmpdir(),`ktc-gc-${process.pid}-${Date.now()}.xlsx`);fs.writeFileSync(tmp,input);try{const wb=new ExcelJS.Workbook();await wb.xlsx.readFile(tmp);const s=wb.getWorksheet('Cắt lồng')||wb.getWorksheet('CẮT LỒNG')||wb.worksheets[0];if(!s)return input;const rs=reports(p);let rr=()=>[...(s._rows||[])].filter(isReportRow).sort((a,b)=>a.number-b.number);let rows=rr();
if(rows.length!==rs.length){const before=rows.length,target=rs.length,action=before<target?'insert':'shrink';if(before<target){const last=rows.length?rows[rows.length-1]:s.getRow(6);const at=last.number+1;for(let i=before;i<target;i++){const r=s.insertRow(at+(i-before),[]);copyRowStyle(last,r)}}else{for(let i=before-1;i>=target;i--)s.spliceRows(rows[i].number,1)}rows=rr();console.log('[KTC-EXCEL-TEMPLATE] GC_ROW_RESIZE',JSON.stringify({before,after:rows.length,dbReports:target,action}));}
if(rows.length!==rs.length)throw new Error(`GC report row mismatch after resize: template=${rows.length}, db=${rs.length}`);
let ds=0,ng=0,td=0,tn=0,nd=0,nf=0;for(let i=0;i<rs.length;i++){const x=rs[i],r=rows[i],dd=Array.isArray(x.deductions)?x.deductions:[],ff=Array.isArray(x.defects)?x.defects:[];for(let j=0;j<D.length;j++){let v=0;for(const z of dd)if(match(D[j],z,'d'))v+=val(z,'d');r.getCell(11+j).value=v;ds+=v;if(v)nd++}for(let j=0;j<F.length;j++){let v=0;for(const z of ff)if(match(F[j],z,'f'))v+=val(z,'f');r.getCell(36+j).value=v;ng+=v;if(v)nf++}r.getCell(9).value=num(x?.changeover_count??x?.change_machine_count??x?.so_lan_cm);r.getCell(10).value=num(x?.deduction_time);r.getCell(34).value=num(x?.tt_ng);td+=num(x?.deduction_time);tn+=num(x?.tt_ng)}console.log('[KTC-EXCEL-TEMPLATE] DB_DETAIL_PATCHED_V8',JSON.stringify({reports:rs.length,rows:rows.length,patched:rs.length,nonzeroDeductionCells:nd,nonzeroDefectCells:nf,detailDeductionSum:ds,detailNgSum:ng,totalDeductionSum:td,totalNgSum:tn}));return Buffer.from(await wb.xlsx.writeBuffer())}finally{try{fs.unlinkSync(tmp)}catch{}}}
const op=monthly.buildProcessWorkbookLocal,osplit=monthly.buildSplitMonthlyWorkbooksLocal;
if(typeof op==='function')monthly.buildProcessWorkbookLocal=async a=>{const r=await op(a);if(String(a?.processCode||'').toUpperCase()==='GC'&&r?.buffer)r.buffer=await patch(r.buffer,a?.payload||{});return r};
if(typeof osplit==='function')monthly.buildSplitMonthlyWorkbooksLocal=async a=>{const r=await osplit(a);for(const x of r?.processes||[])if(String(x?.processCode||'').toUpperCase()==='GC'&&x?.buffer)x.buffer=await patch(x.buffer,a?.payload||{});return r};
module.exports=monthly;
