'use strict';
const fs=require('node:fs/promises');
const path=require('node:path');
const ExcelJS=require('exceljs');
const Module=require('node:module');
const originalLoad=Module._load;
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').trim().toUpperCase().replace(/[^A-Z0-9]+/g,' ').trim();
const text=v=>v==null?'':String(v).trim();
const number=v=>{const n=Number(v);return Number.isFinite(n)?n:null;};
const dateValue=v=>{if(!v||v instanceof Date)return v;const s=String(v).slice(0,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return v;const[y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d);};
function headers(sheet){const m=new Map();for(let c=1;c<=sheet.columnCount;c++){const h=norm(sheet.getCell(5,c).value);if(h)m.set(h,c);}return m;}
function put(sheet,hs,row,aliases,value,fmt){for(const a of aliases){const c=hs.get(norm(a));if(c){sheet.getCell(row,c).value=value;if(fmt)sheet.getCell(row,c).numFmt=fmt;return true;}}return false;}
function machine(r){const a=(Array.isArray(r?.machineLines)?r.machineLines:[]).map(x=>text(x?.machine_code??x?.machine_no??x?.machine_name)).filter(Boolean);return a.length?[...new Set(a)].join(', '):text(r?.machine_no??r?.machine_code??r?.machine);}
function product(r){const a=(Array.isArray(r?.machineLines)?r.machineLines:[]).map(x=>text(x?.product_code??x?.product_name)).filter(Boolean);return a.length?[...new Set(a)].join(', '):text(r?.product_code??r?.product_name??r?.product);}
function detailItems(r,kind){return Array.isArray(r?.[kind==='deduction'?'deductions':'defects'])?r[kind==='deduction'?'deductions':'defects']:[];}
function detailAliases(x,kind){const id=number(x?.[kind==='deduction'?'deduction_type_id':'defect_type_id']);const code=text(x?.[kind==='deduction'?'deduction_type_code':'defect_type_code']??x?.code);const name=text(x?.[kind==='deduction'?'deduction_type_name':'defect_type_name']??x?.name);return [id>0?`ID:${id}`:'',norm(code),norm(name)].filter(Boolean);}
function detailValue(x,kind){return number(x?.[kind==='deduction'?'hours':'quantity'])??number(x?.[kind==='deduction'?'deduction_hours':'defect_quantity'])??0;}
function typeMap(pd,kind){const key=kind==='deduction'?'deductionTypes':'defectTypes';const codeKey=kind==='deduction'?'deduction_code':'defect_code';const nameKey=kind==='deduction'?'deduction_name':'defect_name';const out=new Map();for(const x of Array.isArray(pd?.[key])?pd[key]:[]){const id=number(x?.id);if(!(id>0))continue;for(const k of [norm(x?.[codeKey]??x?.code),norm(x?.[nameKey]??x?.name??x?.label)].filter(Boolean))out.set(k,`ID:${id}`);}return out;}
function detailForHeader(report,pd,header,kind){const wanted=norm(header);if(!wanted)return 0;const typeIds=typeMap(pd,kind);const direct=typeIds.get(wanted);let total=0;for(const x of detailItems(report,kind)){const aliases=detailAliases(x,kind);const matched=direct?aliases.includes(direct):aliases.some(a=>a===wanted||a.includes(wanted)||wanted.includes(a));if(matched)total+=detailValue(x,kind);}return total;}
function rowsFor(sheet,hs,reports){const byId=new Map(reports.map(r=>[number(r?.id),r]));const idCol=hs.get('ID')||hs.get('MA BAO CAO')||hs.get('REPORT ID');const workerCol=hs.get('MA NV')||hs.get('MA CONG NHAN');const dateCol=hs.get('NGAY')||hs.get('NGAY LAM VIEC');const sttCol=hs.get('STT');const used=new Set();const out=[];for(let row=6;row<=sheet.rowCount;row++){let r=null;if(idCol){const id=number(sheet.getCell(row,idCol).value);if(id>0)r=byId.get(id)||null;}if(!r&&workerCol){const w=norm(sheet.getCell(row,workerCol).value);if(w){const ds=dateCol?String(sheet.getCell(row,dateCol).value??'').slice(0,10):'';r=reports.find(x=>!used.has(number(x?.id))&&norm(x?.worker_code)===w&&(!ds||String(x?.work_date??'').slice(0,10)===ds))||null;}}if(!r&&sttCol){const stt=number(sheet.getCell(row,sttCol).value);if(stt>0&&stt<=reports.length)r=reports[stt-1];}if(!r)continue;used.add(number(r?.id));out.push([row,r]);}return out;}
function patchSheet(sheet,pd,reports){if(!reports?.length||sheet.state!=='visible'||sheet.name.startsWith('_'))return;const hs=headers(sheet);if(!hs.size)return;for(const[row,r]of rowsFor(sheet,hs,reports)){put(sheet,hs,row,['ID','Mã báo cáo','Report ID'],number(r.id));put(sheet,hs,row,['Ngày','Ngày làm việc'],dateValue(r.work_date),'dd/mm/yyyy');put(sheet,hs,row,['Mã NV','Mã công nhân'],text(r.worker_code));put(sheet,hs,row,['Tên NV','Tên công nhân','Họ tên'],text(r.full_name??r.worker_name??r.worker_full_name));put(sheet,hs,row,['Ca'],text(r.shift));put(sheet,hs,row,['Loại thao tác'],text(r.operation_type));put(sheet,hs,row,['Chế độ'],text(r.operation_mode));put(sheet,hs,row,['Máy','Mã máy'],machine(r));put(sheet,hs,row,['Mã SP','Mã sản phẩm','Sản phẩm'],product(r));put(sheet,hs,row,['% học việc','% Học việc'],number(r.training_percent));put(sheet,hs,row,['Định mức','Định mức/H'],number(r.standard_output??r.standard_output_per_hour));put(sheet,hs,row,['Tổng thời gian'],number(r.total_time));put(sheet,hs,row,['Thời gian chạy thực tế','Thời gian thực tế'],number(r.actual_time));put(sheet,hs,row,['Tổng thời gian trừ','Thời gian trừ'],number(r.deduction_time));put(sheet,hs,row,['OK','SL OK','Sản lượng OK'],number(r.tt_ok??r.ok_quantity));put(sheet,hs,row,['NG','SL NG','Tổng NG'],number(r.tt_ng??r.total_ng??r.ng_quantity));put(sheet,hs,row,['SP công nhân nhập','Sản lượng thực tế','Sản lượng','Output'],number(r.actual_output));for(const[h,c]of hs){if(h.startsWith('_'))continue;const d=detailForHeader(r,pd,h,'deduction');const f=detailForHeader(r,pd,h,'defect');if(d||detailItems(r,'deduction').length)if(d>0||typeMap(pd,'deduction').has(h))sheet.getCell(row,c).value=d;if(f||detailItems(r,'defect').length)if(f>0||typeMap(pd,'defect').has(h))sheet.getCell(row,c).value=f;}}}
async function applyGcTemplate(generatedBuffer){const templatePath=path.join(__dirname,'..','assets','templates','bao-cao-cat-long-export.xlsx');try{await fs.access(templatePath);}catch{return generatedBuffer;}const src=new ExcelJS.Workbook();await src.xlsx.load(generatedBuffer);const tpl=new ExcelJS.Workbook();await tpl.xlsx.readFile(templatePath);const sourceSheets=src.worksheets.filter(s=>s.state==='visible');for(const source of sourceSheets){const target=tpl.getWorksheet(source.name)||tpl.worksheets.find(s=>s.state==='visible');if(!target)continue;for(let r=6;r<=target.rowCount;r++){for(let c=1;c<=target.columnCount;c++){const cell=target.getCell(r,c);if(!cell.isMerged)cell.value=null;}}for(let r=1;r<=source.rowCount;r++){const sr=source.getRow(r);const tr=target.getRow(r);if(r>target.rowCount)target.getRow(r);tr.height=sr.height;for(let c=1;c<=source.columnCount;c++){const sc=source.getCell(r,c),tc=target.getCell(r,c);if(tc.isMerged&&!tc.master)continue;if(sc.value!==undefined)tc.value=sc.value;}}}return Buffer.from(await tpl.xlsx.writeBuffer());}
async function patchWorkbook(buffer,payload,code){if(!buffer||payload?.dataSource!=='tidb.production_reports.approved')return buffer;const wb=new ExcelJS.Workbook();await wb.xlsx.load(buffer);const pd=code?payload?.processes?.[code]:null;if(pd?.reports){for(const s of wb.worksheets)patchSheet(s,pd,pd.reports);}else{for(const[dataCode,data]of Object.entries(payload?.processes||{})){if(!data?.reports)continue;for(const s of wb.worksheets){const sn=norm(s.name),cn=norm(dataCode);if(sn===cn||sn.includes(cn)||cn.includes(sn))patchSheet(s,data,data.reports);}}}return Buffer.from(await wb.xlsx.writeBuffer());}
async function makeNoopSummary(date,payload,processes){const wb=new ExcelJS.Workbook();wb.addWorksheet('THÁNG');const [year,month]=String(payload?.yearMonth||date).slice(0,7).split('-');return{buffer:Buffer.from(await wb.xlsx.writeBuffer()),fileName:processes[0]?.fileName||`00_TONG_HOP_SAN_XUAT_${month}-${year}.xlsx`,formulaReplacementCount:0};}
function patchMonthly(mod){if(!mod||mod.__ktcDbTruthExcelPatched)return mod;const originalSplit=mod.buildSplitMonthlyWorkbooksLocal;const originalProcess=mod.buildProcessWorkbookLocal;if(typeof originalSplit==='function'&&typeof originalProcess==='function'){mod.buildSplitMonthlyWorkbooksLocal=async(args={})=>{const processes=[];const entries=Object.entries(args.payload?.processes||{}).filter(([,data])=>Array.isArray(data?.reports)&&data.reports.length>0);for(const[code]of entries){const item=await originalProcess({...args,processCode:code});if(item?.buffer){item.buffer=await patchWorkbook(item.buffer,args.payload,code);if(String(code).toUpperCase()==='GC')item.buffer=await applyGcTemplate(item.buffer);}processes.push({...item,processCode:code});}const summary=await makeNoopSummary(args.date,args.payload,processes);return{summary,processes};};mod.buildProcessWorkbookLocal=async(args={})=>{const result=await originalProcess(args);if(result?.buffer){result.buffer=await patchWorkbook(result.buffer,args.payload,args.processCode);if(String(args.processCode||'').toUpperCase()==='GC')result.buffer=await applyGcTemplate(result.buffer);}return result;};}Object.defineProperty(mod,'__ktcDbTruthExcelPatched',{value:true});return mod;}
function monthOnlyLayout(mod){if(!mod||mod.__ktcMonthOnlyLayoutPatched)return mod;const safeFile=mod.safeFile||((v,f)=>v||f);mod.getCompanyMonthTarget=async({root,date,fileName})=>{const[year,month]=String(date).split('-');const normalized=safeFile(fileName,`A+B ${month}-${year}.xlsx`);const folder=path.join(root,year,month);await fs.mkdir(folder,{recursive:true});return{layout:'YEAR_MONTH_COMPANY_FILE',folder,filePath:path.join(folder,normalized),fileName:normalized,processFolder:null};};mod.getProcessMonthTarget=async({root,date,processCode,processName,fileName})=>{const[year,month]=String(date).split('-');const normalized=safeFile(fileName,`Bao-cao-${norm(processName||processCode)}-${month}-${year}.xlsx`);const folder=path.join(root,year,month);await fs.mkdir(folder,{recursive:true});return{layout:'YEAR_MONTH_PROCESS_FILE',folder,filePath:path.join(folder,normalized),fileName:normalized,processFolder:null};};Object.defineProperty(mod,'__ktcMonthOnlyLayoutPatched',{value:true});return mod;}
async function cleanupLegacy(root){const processNames=new Set(['Gia công','Mài - Đo','Mài','Đo','Kiểm 1','Kiểm 2','Ép','Cán','Xử lý bavia']);const moveFile=async(src,target)=>{await fs.mkdir(path.dirname(target),{recursive:true});try{await fs.access(target);await fs.rm(src,{force:true});}catch{try{await fs.rename(src,target);}catch{}}};const years=await fs.readdir(root,{withFileTypes:true}).catch(()=>[]);for(const y of years){if(!y.isDirectory()||!/^\d{4}$/.test(y.name))continue;const yf=path.join(root,y.name);const entries=await fs.readdir(yf,{withFileTypes:true}).catch(()=>[]);for(const e of entries){if(e.isDirectory()&&processNames.has(e.name)){const pf=path.join(yf,e.name);const files=await fs.readdir(pf,{withFileTypes:true}).catch(()=>[]);for(const f of files){if(!f.isFile()||!f.name.toLowerCase().endsWith('.xlsx'))continue;const m=f.name.match(/(?:THANG|_|-)(0[1-9]|1[0-2])-(\d{4})/i);if(!m||m[2]!==y.name)continue;await moveFile(path.join(pf,f.name),path.join(yf,m[1],f.name));}await fs.rm(pf,{recursive:true,force:true}).catch(()=>{});continue;}if(!/^\d{2}$/.test(e.name)||!e.isDirectory())continue;const mf=path.join(yf,e.name);const subs=await fs.readdir(mf,{withFileTypes:true}).catch(()=>[]);for(const sub of subs){if(!sub.isDirectory()||!processNames.has(sub.name))continue;const sf=path.join(mf,sub.name);const files=await fs.readdir(sf,{withFileTypes:true}).catch(()=>[]);for(const f of files){if(f.isFile()&&f.name.toLowerCase().endsWith('.xlsx'))await moveFile(path.join(sf,f.name),path.join(mf,f.name));}await fs.rm(sf,{recursive:true,force:true}).catch(()=>{});}}}}
function patchPaths(mod){return monthOnlyLayout(mod);}
Module._load=function(request,parent,isMain){const loaded=originalLoad.call(this,request,parent,isMain);if(typeof request!=='string')return loaded;if(/monthlyWorkbookLocal\.cjs$/.test(request))return patchMonthly(loaded);if(/excelDualLayout\.cjs$/.test(request))return patchPaths(loaded);return loaded;};
(async()=>{try{const root=String(process.env.KTC_EXPORT_ROOT||'\\\\KTCNAS\\Public\\3. SẢN XUẤT-製造\\Linh tinh').trim();await cleanupLegacy(root);}catch(e){console.warn('[KTC] legacy Excel folder cleanup skipped:',e?.message||e);}})();
