const express=require('express');
const router=express.Router();
const controller=require('../controllers/adminMasterController');
const verifyToken=require('../middleware/authMiddleware');
const checkRole=require('../middleware/roleMiddleware');
const permission=require('../middleware/permissionMiddleware');
router.use(verifyToken,checkRole('admin','manager','lead'));
router.get('/:resource',permission('MASTER_VIEW'),controller.list);
router.post('/:resource',permission('MASTER_EDIT'),controller.create);
router.put('/:resource/:id',permission('MASTER_EDIT'),controller.update);
router.delete('/:resource/:id',permission('MASTER_EDIT'),controller.remove);
router.put('/workers/:id/profile',permission('MASTER_EDIT'),controller.updateWorker);
router.put('/workers/:id/processes',permission('MASTER_EDIT'),controller.setWorkerProcesses);
module.exports=router;
