const router=require('express').Router();
const auth=require('../middleware/authMiddleware');
const role=require('../middleware/roleMiddleware');
const permission=require('../middleware/permissionMiddleware');
const c=require('../controllers/machineProductionEventController');
const roles=role('admin','manager','lead');
router.get('/',auth,roles,permission('REPORT_PENDING_VIEW','REPORT_APPROVED_VIEW'),c.list);
router.get('/:id',auth,roles,permission('REPORT_PENDING_VIEW','REPORT_APPROVED_VIEW'),c.get);
router.post('/',auth,roles,permission('REPORT_APPROVE'),c.create);
router.put('/:id',auth,roles,permission('REPORT_APPROVE'),c.update);
router.post('/:id/link-participants',auth,roles,permission('REPORT_APPROVE'),c.link);
router.post('/:id/approve',auth,roles,permission('REPORT_APPROVE'),c.approve);
module.exports=router;
